;;; aob-acp-session-conformance-tests.el --- session methods as the ACP spec has them -*- lexical-binding: t; -*-

;;; Code:

(require 'ert)
(require 'cl-lib)
(require 'aob)
(require 'aob-acp)
(require 'aob-btw)

(setq aob-acp-persist-file (make-temp-file "aob-conformance-" nil ".eld"))

(defmacro aob-conformance--with (var init &rest body)
  "Bind VAR to an idle session over a cat connection whose initialize gave INIT."
  (declare (indent 2))
  `(let* ((aob-acp-persist-file (make-temp-file "aob-conformance-" nil ".eld"))
          (proc (make-process :name "aob-conformance-cat" :command '("cat")
                              :connection-type 'pipe :noquery t))
          (,var (aob-create-session :id "acp:conf:1" :backend 'acp
                                    :name "conf:1" :project "/tmp/proj/"
                                    :dir "/tmp/proj/" :state 'idle)))
     (unwind-protect
         (progn
           (process-put proc 'aob-sessions (make-hash-table :test #'equal))
           (process-put proc 'aob-next-id (list 0))
           (process-put proc 'aob-pending (make-hash-table :test #'eql))
           (process-put proc 'aob-json-buf (generate-new-buffer " *aob-conf-json*"))
           (when ,init (process-put proc 'aob-init (list 'done ,init)))
           (setf (aob-session-conn ,var) proc)
           (aob-session-put ,var :agent "claude")
           (aob-session-put ,var :acp-id "sess-test")
           (aob-acp--register proc "sess-test" ,var)
           (cl-letf (((symbol-function 'message) #'ignore))
             ,@body))
       (ignore-errors (kill-buffer (process-get proc 'aob-json-buf)))
       (ignore-errors (delete-process proc))
       (when (aob-session-get (aob-session-id ,var))
         (aob-remove-session ,var))
       (delete-file aob-acp-persist-file))))

(defun aob-conformance--feed (s json)
  (aob-acp--filter (aob-session-conn s) (concat json "\n")))

(defun aob-conformance--caps (&rest keys)
  "An initialize result whose sessionCapabilities hold KEYS, each an empty object."
  (list :agentCapabilities
        (list :sessionCapabilities (apply #'append (mapcar (lambda (k) (list k nil)) keys)))))

(ert-deftest aob-conformance-fork-only-when-advertised ()
  (aob-conformance--with s (aob-conformance--caps :close)
    (let (opened)
      (cl-letf (((symbol-function 'aob-acp--open)
                 (lambda (&rest args) (push args opened) s)))
        (should (string-match-p
                 "claude does not offer session/fork"
                 (cadr (should-error (aob-acp-fork s) :type 'user-error))))
        (should-not opened)
        (process-put (aob-session-conn s) 'aob-init
                     (list 'done (aob-conformance--caps :fork)))
        (aob-acp-fork s)
        (should (= 1 (length opened)))
        (should-not (nth 6 (car opened))))))
  (aob-conformance--with src (aob-conformance--caps :close)
    (let ((popup (lambda () (when-let* ((b (get-buffer aob-btw-buffer-name)))
                              (with-current-buffer b (buffer-string))))))
      (unwind-protect
          (progn
            (should-not (aob-btw-ask src "and?"))
            (should (string-match-p "does not offer session/fork" (funcall popup))))
        (when-let* ((b (get-buffer aob-btw-buffer-name))) (kill-buffer b))))))

(ert-deftest aob-conformance-fork-waits-for-an-unknown-initialize ()
  (aob-conformance--with s nil
    (let (prepare)
      (cl-letf (((symbol-function 'aob-acp--open)
                 (lambda (&rest args) (setq prepare (nth 6 args)) s))
                ((symbol-function 'aob-acp--live-conn)
                 (lambda (&rest _) (aob-session-conn s))))
        (aob-acp-fork s)
        (should (functionp prepare))
        (let (said)
          (process-put (aob-session-conn s) 'aob-init
                       (list 'done (aob-conformance--caps :close)))
          (funcall prepare s (lambda (err) (setq said err)))
          (should (string-match-p "does not offer session/fork"
                                  (plist-get said :message)))
          (process-put (aob-session-conn s) 'aob-init
                       (list 'done (aob-conformance--caps :fork)))
          (setq said 'unset)
          (funcall prepare s (lambda (err) (setq said err)))
          (should-not said))))))

(ert-deftest aob-conformance-close-only-when-advertised ()
  (dolist (case (list (list (aob-conformance--caps :close) t)
                      (list (aob-conformance--caps :fork) nil)))
    (aob-conformance--with s (car case)
      (let (sent closed)
        (aob-session-put s :on-close
                         (lambda (&rest args)
                           (should-not (aob-session-get (aob-session-id s)))
                           (push args closed)))
        (cl-letf (((symbol-function 'aob-acp--request)
                   (lambda (_s method params &rest _) (push (cons method params) sent)))
                  ((symbol-function 'aob-acp--notify) #'ignore)
                  ((symbol-function 'aob-acp--conn-cleanup) #'ignore)
                  ((symbol-function 'aob-acp--reap-worktree) #'ignore))
          (aob-acp--kill s))
        (if (cadr case)
            (progn (should (assoc "session/close" sent))
                   (should-not closed))
          (should-not (assoc "session/close" sent))
          (should (equal closed '((nil nil)))))))))

(ert-deftest aob-conformance-close-that-cannot-go-still-says-closed-once ()
  (aob-conformance--with s (aob-conformance--caps :close)
    (let (closed later)
      (aob-session-put s :on-close (lambda (&rest args) (push args closed)))
      (cl-letf (((symbol-function 'aob-acp--request)
                 (lambda (_s _method _params cb) (setq later cb) (error "pipe gone")))
                ((symbol-function 'aob-acp--notify) #'ignore)
                ((symbol-function 'aob-acp--conn-cleanup) #'ignore)
                ((symbol-function 'aob-acp--reap-worktree) #'ignore))
        (aob-acp--kill s))
      (should (equal closed '((nil nil))))
      (funcall later nil '(:message "late"))
      (should (= 1 (length closed)))))
  (aob-conformance--with s (aob-conformance--caps :close)
    (let (closed sent)
      (aob-session-put s :on-close (lambda (&rest args) (push args closed)))
      (delete-process (aob-session-conn s))
      (cl-letf (((symbol-function 'aob-acp--request)
                 (lambda (_s method &rest _) (push method sent)))
                ((symbol-function 'aob-acp--conn-cleanup) #'ignore)
                ((symbol-function 'aob-acp--reap-worktree) #'ignore))
        (aob-acp--kill s))
      (should-not sent)
      (should (equal closed '((nil nil)))))))

(ert-deftest aob-conformance-list-only-when-advertised-and-follows-cursors ()
  (let (asked got)
    (cl-letf (((symbol-function 'aob-acp--request-proc)
               (lambda (_proc method params cb)
                 (push (cons method params) asked)
                 (let ((cursor (plist-get params :cursor)))
                   (funcall cb
                            (pcase cursor
                              ('nil '(:sessions ((:sessionId "a")) :nextCursor "c1"))
                              ("c1" '(:sessions ((:sessionId "b")) :nextCursor "c2"))
                              ("c2" '(:sessions ((:sessionId "c")))))
                            nil))))
              ((symbol-function 'message) #'ignore))
      (aob-acp--list-sessions 'proc (aob-conformance--caps :fork) "claude" "/p"
                              (lambda (res _) (setq got res)))
      (should-not asked)
      (should-not got)
      (aob-acp--list-sessions 'proc (aob-conformance--caps :list) "claude" "/p"
                              (lambda (res _) (setq got res)))
      (should (equal (mapcar (lambda (x) (plist-get x :sessionId)) (plist-get got :sessions))
                     '("a" "b" "c")))
      (should (equal (mapcar (lambda (a) (plist-get (cdr a) :cursor)) (reverse asked))
                     '(nil "c1" "c2")))))
  (let ((pages 0) got)
    (cl-letf (((symbol-function 'aob-acp--request-proc)
               (lambda (_proc _method _params cb)
                 (cl-incf pages)
                 (funcall cb '(:sessions ((:sessionId "x")) :nextCursor "again") nil))))
      (aob-acp--list-sessions 'proc (aob-conformance--caps :list) "claude" "/p"
                              (lambda (res _) (setq got res)))
      (should (= pages aob-acp--list-page-cap))
      (should (= (length (plist-get got :sessions)) aob-acp--list-page-cap)))))

(ert-deftest aob-conformance-fork-mcp-servers-follow-the-initialize ()
  (let ((aob-acp-mcp-servers (list (list :name "side" :url "http://127.0.0.1:1/mcp"))))
    (should-not (aob-acp--mcp-takes-p 'http nil))
    (should-not (aob-acp--mcp-takes-p 'sse nil))
    (aob-conformance--with s (aob-conformance--caps :fork)
      (let (open)
        (cl-letf (((symbol-function 'aob-acp--open)
                   (lambda (&rest args) (setq open (nth 4 args)) s)))
          (aob-acp-fork s))
        (should (equal (append (plist-get (cadr (funcall open '(:agentCapabilities
                                                                 (:mcpCapabilities (:stdio t)))))
                                          :mcpServers)
                               nil)
                       nil))
        (should (equal (mapcar (lambda (e) (plist-get e :name))
                               (plist-get (cadr (funcall open '(:agentCapabilities
                                                                (:mcpCapabilities (:http t)))))
                                          :mcpServers))
                       '("side")))))))

(ert-deftest aob-conformance-model-switch-prefers-the-config-option ()
  (aob-conformance--with s nil
    (let (sent)
      (cl-letf (((symbol-function 'aob-acp--request)
                 (lambda (_s method params cb)
                   (push (cons method params) sent)
                   (funcall cb (when (equal method "session/set_config_option")
                                 '(:configOptions ((:id "pick" :category "model" :currentValue "b"
                                                    :options ((:value "a") (:value "b"))))))
                            nil))))
        (aob-acp--config-apply s '((:id "pick" :category "model" :currentValue "a"
                                    :options ((:value "a") (:value "b")))))
        (aob-session-put s :models '(:currentModelId "a" :availableModels ((:modelId "a") (:modelId "b"))))
        (aob-acp--set-model s "b")
        (should (equal (caar sent) "session/set_config_option"))
        (should (equal (plist-get (cdar sent) :configId) "pick"))
        (should (equal (plist-get (seq-find (lambda (e) (equal (plist-get e :title) "model: b"))
                                            (aob-session-events s))
                                  :via)
                       "session/set_config_option"))
        (setq sent nil)
        (aob-session-put s :models '(:currentModelId "b" :availableModels ((:modelId "a") (:modelId "b"))))
        (aob-acp--config-apply s nil)
        (aob-acp--set-model s "a")
        (should-not sent)))))

(ert-deftest aob-conformance-model-path-is-kept-only-when-a-request-went-out ()
  (aob-conformance--with s nil
    (let (sent)
      (aob-acp--config-apply s '((:id "model" :type "boolean" :currentValue t)))
      (cl-letf (((symbol-function 'aob-acp--request)
                 (lambda (_s method &rest _) (push method sent)))
                ((symbol-function 'aob-acp--declares-boolean-options-p) #'ignore))
        (aob-acp--set-model s nil))
      (should-not sent)
      (should-not (aob-session-ref s :model-via))
      (aob-acp--config-apply s '((:id "model" :currentValue "a"
                                  :options ((:value "a") (:value "b")))))
      (cl-letf (((symbol-function 'aob-acp--request)
                 (lambda (&rest _) (error "pipe gone"))))
        (should-error (aob-acp--set-model s "b")))
      (should-not (aob-session-ref s :model-via)))))

(ert-deftest aob-conformance-stdio-commands-go-absolute ()
  (let ((aob-acp-mcp-servers (list (list :name "found" :command "node" :args '("x"))
                                   (list :name "lost" :command "nowhere-bin")
                                   (list :name "abs" :command "/bin/cat")))
        (init '(:agentCapabilities (:mcpCapabilities (:http t)))))
    (cl-letf (((symbol-function 'executable-find)
               (lambda (cmd &rest _) (and (equal cmd "node") "/opt/bin/node")))
              ((symbol-function 'aob-acp-project-mcp-servers) #'ignore))
      (let* ((aob-acp--mcp-dropped nil)
             (sent (append (aob-acp--mcp-servers init "/tmp/proj/") nil)))
        (should (equal (mapcar (lambda (e) (plist-get e :command)) sent)
                       '("/opt/bin/node" "/bin/cat")))
        (should (equal aob-acp--mcp-dropped '(("lost" . "nowhere-bin")))))
      (let ((sent (append (aob-acp--mcp-servers init "/ssh:host:/proj/") nil)))
        (should (equal (mapcar (lambda (e) (plist-get e :command)) sent)
                       '("node" "nowhere-bin" "/bin/cat"))))
      (aob-conformance--with s nil
        (aob-acp--warn-mcp-dropped s '(("lost" . "nowhere-bin")))
        (aob-acp--warn-mcp-dropped s '(("lost" . "nowhere-bin")))
        (should (= 1 (seq-count (lambda (e) (equal (plist-get e :title)
                                                   "mcp server lost left out: nowhere-bin not found"))
                                (aob-session-events s))))))))

(ert-deftest aob-conformance-resource-uris-are-encoded-agent-paths ()
  (let* ((dir (make-temp-file "aob conf é" t))
         (abs (expand-file-name "a b#c.el" dir)))
    (unwind-protect
        (progn
          (write-region "x\n" nil abs nil 'silent)
          (let ((link (aob-acp--mention-block (cons "a b#c.el" abs) nil))
                (want (concat "file://"
                              (mapconcat #'url-hexify-string (split-string abs "/") "/"))))
            (should (equal (plist-get link :uri) want))
            (should-not (string-match-p " \\|#" (plist-get link :uri)))
            (should (string-match-p "%20" (plist-get link :uri)))
            (should (string-match-p "%C3%A9" (plist-get link :uri))))
          (aob-conformance--with s nil
            (let ((aob-dedupe-context t)
                  (block (aob-acp--mention-block (cons "a b#c.el" abs) t s)))
              (should (equal (plist-get block :type) "resource"))
              (aob-acp--tell-embeds s (vector block))
              (should (equal (plist-get (aob-acp--mention-block (cons "a b#c.el" abs) t s) :type)
                             "resource_link"))
              (should (equal (aob-acp--uri-file s (substring-no-properties
                                                   (plist-get (plist-get block :resource) :uri)))
                             abs)))))
      (delete-directory dir t)))
  (cl-letf (((symbol-function 'aob-acp--wire-dir)
             (lambda (d) (string-remove-prefix "/ssh:host:" d))))
    (should (equal (substring-no-properties (aob-acp--file-uri "/ssh:host:/home/u/my file.el"))
                   "file:///home/u/my%20file.el"))))

(ert-deftest aob-conformance-plan-update-reads-nested-entries ()
  (aob-conformance--with s nil
    (let ((items (lambda (s)
                   (plist-get (aob-session-ref s :plan-ev) :entries))))
      (aob-conformance--feed s "{\"jsonrpc\":\"2.0\",\"method\":\"session/update\",\"params\":{\"sessionId\":\"sess-test\",\"update\":{\"sessionUpdate\":\"plan_update\",\"plan\":{\"type\":\"items\",\"planId\":\"p\",\"entries\":[{\"content\":\"nested\",\"status\":\"in_progress\",\"priority\":\"high\"}]}}}}")
      (should (equal (mapcar (lambda (e) (plist-get e :content)) (funcall items s)) '("nested")))
      (aob-conformance--feed s "{\"jsonrpc\":\"2.0\",\"method\":\"session/update\",\"params\":{\"sessionId\":\"sess-test\",\"update\":{\"sessionUpdate\":\"plan_update\",\"plan\":{\"type\":\"markdown\",\"planId\":\"p\",\"markdown\":\"# hi\"}}}}")
      (should (equal (mapcar (lambda (e) (plist-get e :content)) (funcall items s)) '("nested")))
      (aob-conformance--feed s "{\"jsonrpc\":\"2.0\",\"method\":\"session/update\",\"params\":{\"sessionId\":\"sess-test\",\"update\":{\"sessionUpdate\":\"plan_update\"}}}")
      (should (equal (mapcar (lambda (e) (plist-get e :content)) (funcall items s)) '("nested")))
      (aob-conformance--feed s "{\"jsonrpc\":\"2.0\",\"method\":\"session/update\",\"params\":{\"sessionId\":\"sess-test\",\"update\":{\"sessionUpdate\":\"plan\",\"entries\":[{\"content\":\"flat\",\"status\":\"pending\",\"priority\":\"low\"}]}}}")
      (should (equal (mapcar (lambda (e) (plist-get e :content)) (funcall items s)) '("flat"))))))

(ert-deftest aob-conformance-boolean-config-goes-typed-and-false ()
  (aob-conformance--with s nil
    (let (sent)
      (aob-session-put s :config-options
                       '((:id "fast" :type "boolean" :currentValue t)
                         (:id "effort" :type "select" :currentValue "low"
                          :options ((:value "low") (:value "high")))))
      (cl-letf (((symbol-function 'aob-acp--request)
                 (lambda (_s method params _cb) (push (cons method params) sent)))
                ((symbol-function 'aob-acp--client-capabilities)
                 (lambda () (list :session (list :configOptions
                                                 (list :boolean (make-hash-table)))))))
        (aob-acp--set-config s "fast" nil)
        (aob-acp--set-config s "fast" :false)
        (aob-acp--set-config s "fast" t)
        (aob-acp--set-config s "effort" nil)
        (should (= 3 (length sent)))
        (dolist (wire (mapcar (lambda (c) (json-serialize (cdr c))) (cdr sent)))
          (should (string-match-p "\"type\":\"boolean\"" wire))
          (should (string-match-p "\"value\":false" wire)))
        (should (string-match-p "\"value\":true" (json-serialize (cdar sent)))))
      (setq sent nil)
      (cl-letf (((symbol-function 'aob-acp--request)
                 (lambda (_s method params _cb) (push (cons method params) sent)))
                ((symbol-function 'aob-acp--client-capabilities)
                 (lambda () (list :fs nil))))
        (aob-acp--set-config s "fast" :false)
        (aob-acp--want-config s '(:fast nil :effort "high"))
        (should (equal (mapcar (lambda (c) (json-serialize (cdr c))) sent)
                       '("{\"sessionId\":\"sess-test\",\"configId\":\"effort\",\"value\":\"high\"}")))))))

(ert-deftest aob-conformance-mode-goes-through-its-config-option ()
  (aob-conformance--with s nil
    (let (sent)
      (aob-session-put s :modes '(:currentModeId "default"
                                  :availableModes ((:id "default") (:id "plan"))))
      (aob-session-put s :mode-id "default")
      (aob-session-put s :config-options
                       '((:id "mode" :category "mode" :currentValue "default"
                          :options ((:value "default") (:value "plan")))))
      (cl-letf (((symbol-function 'aob-acp--request)
                 (lambda (_s method params cb)
                   (push (cons method params) sent)
                   (funcall cb '(:configOptions ((:id "mode" :category "mode" :currentValue "plan"
                                                  :options ((:value "default") (:value "plan")))))
                            nil))))
        (aob-acp--want-mode s "plan")
        (should (equal (mapcar #'car sent) '("session/set_config_option")))
        (should (equal (plist-get (cdar sent) :configId) "mode"))
        (should (equal (plist-get (cdar sent) :value) "plan"))
        (should (equal (aob-session-ref s :mode-id) "plan"))
        (setq sent nil)
        (aob-acp--want-mode s "nope")
        (should-not sent)))))

(ert-deftest aob-conformance-tool-call-name-beats-the-meta-key ()
  (should (equal (aob-acp--tool-name '(:name "Agent" :_meta (:claudeCode (:toolName "Read"))))
                 "Agent"))
  (should (equal (aob-acp--tool-name '(:_meta (:claudeCode (:toolName "Task")))) "Task"))
  (aob-conformance--with s nil
    (aob-conformance--feed s "{\"jsonrpc\":\"2.0\",\"method\":\"session/update\",\"params\":{\"sessionId\":\"sess-test\",\"update\":{\"sessionUpdate\":\"tool_call\",\"toolCallId\":\"t1\",\"name\":\"Agent\",\"title\":\"agent\",\"kind\":\"other\",\"status\":\"pending\",\"rawInput\":{\"description\":\"find the leak\"}}}}")
    (aob-conformance--feed s "{\"jsonrpc\":\"2.0\",\"method\":\"session/update\",\"params\":{\"sessionId\":\"sess-test\",\"update\":{\"sessionUpdate\":\"tool_call\",\"toolCallId\":\"t2\",\"name\":null,\"title\":\"agent\",\"kind\":\"other\",\"status\":\"pending\",\"rawInput\":{\"description\":\"from meta\"},\"_meta\":{\"claudeCode\":{\"toolName\":\"Task\"}}}}}")
    (let ((titles (mapcar (lambda (e) (plist-get e :title))
                          (seq-filter (lambda (e) (eq (plist-get e :type) 'tool))
                                      (aob-session-events s)))))
      (should (member "find the leak" titles))
      (should (member "from meta" titles)))))

(provide 'aob-acp-session-conformance-tests)
;;; aob-acp-session-conformance-tests.el ends here
