;;; code-verbs-tests.el --- Tests for ygg-code-verbs -*- lexical-binding: t; -*-

(require 'ert)
(require 'cl-lib)
(require 'yggdrasil)
(require 'layer-lsp)
(require 'layer-format)
(require 'layer-tramp)
(require 'yggdrasil-localleader)
(require 'layer-swift)
(require 'ygg-compose-preview)
(require 'ygg-code-verbs)

(defun code-verbs-tests--local (mode key)
  (lookup-key (ygg-localleader--get-map mode) (kbd key)))

(ert-deftest code-verbs-leader-keeps-its-old-keys ()
  (pcase-dolist (`(,key . ,command)
                 '(("a" . ygg-lsp-code-actions) ("c" . ygg-toggle-line-comment)
                   ("C" . ygg-toggle-block-comment) ("H" . ygg-multi-cursor-references)
                   ("r" . ygg-lsp-rename) ("o" . ygg-lsp-organize-imports)
                   ("x" . ygg-lsp-fix-all) ("f" . ygg-format-buffer) ("F" . ygg-format)
                   ("R" . ygg-ast-grep-rewrite) ("i" . ygg-toggle-inlay-hints)
                   ("n" . ygg-lsp-reconnect) ("S" . consult-eglot-symbols)
                   ("t" . ygg-lsp-type-definition) ("E" . ygg-diagnostic-line)
                   ("D" . flymake-show-buffer-diagnostics) ("h" . ygg-code-hydra/body)
                   ("d" . ygg-diag-hover-mode) ("s" . ygg-format-on-save-toggle)
                   ("p" . ygg-remote-provision-lsp)))
    (should (eq (lookup-key ygg-leader-code-map key) command)))
  (should (eq (lookup-key ygg-leader-code-map "e") ygg-leader-code-structural-map)))

(ert-deftest code-verbs-leader-binds-one-key-per-concept ()
  (pcase-dolist (`(,key . ,command)
                 '(("b" . ygg-code-build) ("l" . ygg-code-run) ("K" . ygg-code-clean)
                   ("u" . ygg-code-test-at-point) ("U" . ygg-code-test-file)
                   ("T" . ygg-code-test-all) ("P" . ygg-code-preview)
                   ("m" . ygg-code-device)))
    (should (eq (lookup-key ygg-leader-code-map key) command))))

(ert-deftest code-verbs-resolve-per-language ()
  (let ((default-directory temporary-file-directory))
    (pcase-dolist (`(,mode ,concept ,command)
                   '((swift-ts-mode build ygg-swift-build)
                     (swift-ts-mode run ygg-swift-run)
                     (swift-ts-mode clean ygg-swift-clean)
                     (swift-ts-mode test-at-point ygg-swift-test-at-point)
                     (swift-ts-mode test-all ygg-swift-test-all)
                     (swift-ts-mode preview ygg-swift-preview)
                     (rust-ts-mode build ygg-localleader-rust-build)
                     (rust-ts-mode run ygg-localleader-rust-run)
                     (rust-ts-mode test-all ygg-localleader-rust-test)
                     (dart-mode run ygg-localleader-flutter-run)
                     (dart-mode test-file ygg-localleader-flutter-test)
                     (dart-mode preview ygg-localleader-flutter-widget-preview)
                     (kotlin-ts-mode build ygg-localleader-kotlin-build)
                     (kotlin-ts-mode clean ygg-localleader-kotlin-clean)
                     (kotlin-ts-mode test-all ygg-localleader-kotlin-test)
                     (kotlin-ts-mode preview ygg-compose-preview)
                     (elixir-ts-mode test-at-point ygg-localleader-elixir-test-line)
                     (elixir-ts-mode test-file ygg-localleader-elixir-test)
                     (python-ts-mode run ygg-localleader-python-run)
                     (python-ts-mode test-file ygg-localleader-python-test)
                     (emacs-lisp-mode test-all ygg-localleader-elisp-run-tests)
                     (gfm-mode preview ygg-localleader-markdown-preview)
                     (dart-mode device ygg-device-pick)
                     (java-ts-mode device ygg-device-pick)
                     (python-ts-mode device nil)
                     (swift-ts-mode test-file nil)
                     (dart-mode build nil)
                     (go-ts-mode build nil)
                     (java-ts-mode build nil)))
      (should (eq (ygg-code-verbs-resolve concept mode) command)))))

(ert-deftest code-verbs-java-uses-gradle-only-under-a-gradle-build ()
  (let* ((root (file-name-as-directory (make-temp-file "code-verbs-" t)))
         (default-directory root))
    (unwind-protect
        (progn
          (should-not (ygg-code-verbs-resolve 'build 'java-ts-mode))
          (write-region "" nil (expand-file-name "settings.gradle.kts" root))
          (should (eq (ygg-code-verbs-resolve 'build 'java-ts-mode) 'ygg-localleader-kotlin-build))
          (should-not (ygg-code-verbs-resolve 'preview 'java-ts-mode)))
      (delete-directory root t))))

(ert-deftest code-verbs-missing-concept-says-so ()
  (with-temp-buffer
    (fundamental-mode)
    (should-error (ygg-code-build) :type 'user-error)
    (should (equal (cadr (should-error (ygg-code-test-file) :type 'user-error))
                   "No test file for fundamental-mode"))))

(ert-deftest code-verbs-dispatch-calls-the-backend ()
  (let (called)
    (cl-letf (((symbol-function 'ygg-localleader-rust-build)
               (lambda () (interactive) (setq called 'cargo))))
      (with-temp-buffer
        (setq major-mode 'rust-ts-mode)
        (ygg-code-build)))
    (should (eq called 'cargo))))

(ert-deftest code-verbs-moved-keys-leave-the-localleader ()
  (pcase-dolist (`(,modes . ,keys)
                 '(((swift-mode swift-ts-mode) "b" "r" "K" "t" "T" "p" "@")
                   ((rust-ts-mode) "r" "t")
                   ((dart-mode dart-ts-mode) "r" "t" "p" "@")
                   ((kotlin-mode kotlin-ts-mode) "b" "r" "t" "c" "p" "@")
                   ((java-mode java-ts-mode) "@")
                   ((elixir-mode elixir-ts-mode) "t" "T" "f")
                   ((python-mode python-ts-mode) "r" "t")
                   ((emacs-lisp-mode) "t")
                   ((markdown-mode gfm-mode) "p")))
    (dolist (mode modes)
      (dolist (key keys)
        (should-not (code-verbs-tests--local mode key))))))

(ert-deftest code-verbs-unique-keys-stay-local ()
  (pcase-dolist (`(,mode ,key ,command)
                 '((swift-ts-mode "R" ygg-swift-run-without-build)
                   (swift-ts-mode "k" ygg-swift-stop)
                   (swift-ts-mode "o" ygg-swift-show-console)
                   (swift-ts-mode "s" ygg-swift-select-scheme)
                   (swift-ts-mode "f w" ygg-swift-wrap)
                   (rust-ts-mode "c" ygg-localleader-rust-check)
                   (dart-mode "P" ygg-localleader-flutter-widget-preview-clean)
                   (kotlin-ts-mode "a" ygg-localleader-kotlin-assemble)
                   (kotlin-ts-mode "i" ygg-localleader-kotlin-install)
                   (kotlin-ts-mode "P" ygg-compose-preview-pick)
                   (elixir-ts-mode "i" ygg-localleader-elixir-iex)
                   (emacs-lisp-mode "e" eval-last-sexp)))
    (should (eq (code-verbs-tests--local mode key) command))))

(require 'dape)
(require 'layer-dap)

(defun code-verbs-tests--attach (mode endpoint &optional file)
  "The config the debug verb's attach hands dape in a MODE buffer for ENDPOINT."
  (let (started)
    (cl-letf (((symbol-function 'dape) (lambda (config) (setq started config))))
      (with-temp-buffer
        (setq major-mode mode buffer-file-name file)
        (ygg-dape--ex-attach endpoint)))
    started))

(ert-deftest code-verbs-debug-attach-reaches-the-adapter-it-is-given ()
  (pcase-dolist (`(,mode ,type) '((typescript-ts-mode "pwa-node")
                                  (rust-ts-mode "lldb-dap")
                                  (python-ts-mode "python")))
    (let ((config (code-verbs-tests--attach mode "10.0.0.5:4711")))
      (should (equal (list mode (plist-get config :type) (plist-get config 'host)
                           (plist-get config 'port) (plist-get config :request))
                     (list mode type "10.0.0.5" 4711 "attach")))
      (dolist (key '(command command-args ensure container remote-root adb-serial))
        (should-not (plist-member config key)))
      (should-not (memq (plist-get config 'fn)
                        '(ygg-dap-js-docker-resolve ygg-dap-js-remote-resolve
                          ygg-dap-lldb-attach-resolve))))))

(ert-deftest code-verbs-debug-attach-kotlin-goes-to-the-jvm-port ()
  (let ((config (code-verbs-tests--attach 'kotlin-ts-mode "localhost:5006")))
    (should (equal (plist-get config :port) 5006))
    (should (eq (plist-get config 'fn) #'ygg-dap-kotlin-connect))
    (cl-letf (((symbol-function 'ygg-dap-kotlin-server) (lambda (&rest _) 'server))
              ((symbol-function 'ygg-dap-kotlin--adapter-port) (lambda (_) 41999)))
      (let ((resolved (funcall (plist-get config 'fn) (copy-sequence config))))
        (should (equal (plist-get resolved :port) 5006))
        (should (equal (plist-get resolved 'port) 41999)))))
  (should-error (code-verbs-tests--attach 'kotlin-ts-mode "10.0.0.5:5006") :type 'user-error))

(ert-deftest code-verbs-debug-attach-java-goes-to-the-jvm-host-and-port ()
  (let* ((file (make-temp-file "Main" nil ".java"))
         (config (code-verbs-tests--attach 'java-ts-mode "10.0.0.5:8000" file)))
    (unwind-protect
        (progn
          (should (equal (list (plist-get config :hostName) (plist-get config :port)
                               (plist-get config :request) (plist-get config :filePath))
                         (list "10.0.0.5" 8000 "attach" file)))
          (should (eq (plist-get config 'fn) 'ygg-dap-java-attach-resolve))
          (cl-letf (((symbol-function 'ygg-dap-java--server) (lambda () 'jdtls))
                    ((symbol-function 'ygg-dap-java--start-session) (lambda (_) 47002)))
            (let ((resolved (funcall (plist-get config 'fn) (copy-sequence config))))
              (should (equal (plist-get resolved 'port) 47002))
              (should (equal (plist-get resolved :port) 8000)))))
      (when-let* ((buffer (get-file-buffer file))) (kill-buffer buffer))
      (delete-file file))))

;;; code-verbs-tests.el ends here
