;;; format-tests.el --- Tests for layer-format -*- lexical-binding: t; -*-

(require 'ert)
(require 'cl-lib)
(require 'yggdrasil)
(require 'layer-lsp)
(require 'layer-format)

(defconst format-tests--expected
  '((python-mode . ruff) (python-ts-mode . ruff)
    (rust-mode . rustfmt) (rust-ts-mode . rustfmt)
    (go-mode . gofmt) (go-ts-mode . gofmt)
    (swift-mode . swift-format) (swift-ts-mode . swift-format)
    (kotlin-mode . ktlint) (kotlin-ts-mode . ktlint)
    (java-mode . google-java-format) (java-ts-mode . google-java-format)
    (typescript-ts-mode . prettier-typescript) (tsx-ts-mode . prettier-typescript)
    (js-mode . prettier-javascript) (js-ts-mode . prettier-javascript)
    (jsx-ts-mode . prettier-javascript)
    (json-mode . jq) (json-ts-mode . jq)
    (css-mode . prettier-css) (css-ts-mode . prettier-css)
    (html-mode . prettier-html) (html-ts-mode . prettier-html)
    (yaml-mode . prettier-yaml) (yaml-ts-mode . prettier-yaml)
    (elixir-mode . mix-format) (elixir-ts-mode . mix-format) (heex-ts-mode . mix-format)
    (dart-mode . dart-format) (dart-ts-mode . dart-format)
    (c-mode . clang-format) (c-ts-mode . clang-format)
    (c++-mode . clang-format) (c++-ts-mode . clang-format)
    (ruby-mode . rubocop) (ruby-ts-mode . rubocop)
    (lua-mode . stylua) (lua-ts-mode . stylua)
    (sh-mode . shfmt) (bash-ts-mode . shfmt)
    (r-ts-mode . air)
    (markdown-mode . prettier-markdown) (gfm-mode . prettier-markdown)
    (conf-toml-mode . taplo) (toml-ts-mode . taplo)
    (sql-mode . pgformatter)
    (terraform-mode . terraform)
    (dockerfile-mode) (dockerfile-ts-mode))
  "Each language-server mode and the formatter it gets with no project config.")

(ert-deftest format-mode-table-covers-each-server-language ()
  (let ((alist (ygg-format--mode-alist)))
    (dolist (cell format-tests--expected)
      (should (assq (car cell) alist))
      (should (eq (alist-get (car cell) alist) (cdr cell))))))

(defun format-tests--in-project (files body)
  "Call BODY with the default directory in a temp project holding FILES.
FILES is a list of (PATH . CONTENTS)."
  (let* ((root (file-name-as-directory (make-temp-file "format-tests" t)))
         (default-directory root))
    (unwind-protect
        (progn
          (make-directory (expand-file-name ".git" root))
          (dolist (file files)
            (let ((path (expand-file-name (car file) root)))
              (make-directory (file-name-directory path) t)
              (with-temp-file path (insert (cdr file)))
              (when (string-match-p "/bin/" (car file))
                (set-file-modes path #o755))))
          (funcall body))
      (delete-directory root t))))

(defun format-tests--decision (mode)
  (ygg-format--decide-uncached (ygg-format--rows :formatter mode) default-directory))

(ert-deftest format-project-config-picks-the-tool ()
  (format-tests--in-project '(("biome.json" . "{}"))
    (lambda ()
      (should (equal (format-tests--decision 'tsx-ts-mode) '(biome . t)))
      (should (equal (format-tests--decision 'json-ts-mode) '(biome . t)))))
  (format-tests--in-project '((".prettierrc" . "{}"))
    (lambda ()
      (should (equal (format-tests--decision 'json-ts-mode) '(prettier-json . t)))
      (should (equal (format-tests--decision 'typescript-ts-mode) '(prettier-typescript . t)))))
  (format-tests--in-project '(("package.json" . "{\"prettier\": {\"semi\": false}}"))
    (lambda ()
      (should (equal (format-tests--decision 'json-mode) '(prettier-json . t)))))
  (format-tests--in-project nil
    (lambda ()
      (should (equal (format-tests--decision 'json-ts-mode) '(jq . t)))
      (should (equal (format-tests--decision 'python-ts-mode) '(ruff . t)))))
  (format-tests--in-project '(("pyproject.toml" . "[tool.black]\nline-length = 100\n"))
    (lambda ()
      (should (equal (format-tests--decision 'python-ts-mode) '(black . t)))))
  (format-tests--in-project '(("pyproject.toml" . "[tool.black]\n[tool.ruff]\n"))
    (lambda ()
      (should (equal (format-tests--decision 'python-ts-mode) '(ruff . t)))))
  (format-tests--in-project '(("Gemfile.lock" . "GEM\n  specs:\n    rubocop (1.0)\n    standard (1.0)\n"))
    (lambda ()
      (should (equal (format-tests--decision 'ruby-ts-mode) '(ruby-standard . t))))))

(ert-deftest format-foreign-projects-keep-their-style ()
  (format-tests--in-project nil
    (lambda ()
      (dolist (mode '(java-ts-mode kotlin-ts-mode swift-ts-mode c-ts-mode ruby-ts-mode sql-mode))
        (should-not (cdr (format-tests--decision mode))))
      (should (equal (format-tests--decision 'dockerfile-ts-mode) '(none)))))
  (format-tests--in-project
      '(("build.gradle.kts" . "spotless { java { googleJavaFormat() } }\n")
        (".editorconfig" . "[*.{kt,kts}]\nktlint_code_style = ktlint_official\n")
        (".swift-format" . "{}")
        (".clang-format" . "BasedOnStyle: LLVM\n")
        (".rubocop.yml" . "AllCops: {}\n"))
    (lambda ()
      (dolist (mode '(java-ts-mode kotlin-ts-mode swift-ts-mode c-ts-mode ruby-ts-mode))
        (should (cdr (format-tests--decision mode))))))
  (format-tests--in-project '((".swiftformat" . "--indent 2\n"))
    (lambda ()
      (should (equal (format-tests--decision 'swift-mode) '(swiftformat . t)))))
  (should (equal (ygg-format--decide-uncached (ygg-format--rows :formatter 'java-ts-mode) nil)
                 '(google-java-format)))
  (should (equal (ygg-format--decide-uncached (ygg-format--rows :formatter 'python-ts-mode) nil)
                 '(ruff . t))))

(ert-deftest format-lookups-stop-at-the-repository ()
  (format-tests--in-project '((".prettierrc" . "{}") (".clang-format" . "")
                              ("node_modules/.bin/ruff" . "#!/bin/sh\n")
                              ("inner/.git/HEAD" . "") ("inner/src/a.c" . ""))
    (lambda ()
      (let ((default-directory (expand-file-name "inner/src/" default-directory)))
        (should (equal (format-tests--decision 'json-ts-mode) '(jq . t)))
        (should-not (cdr (format-tests--decision 'c-ts-mode)))
        (should (equal (ygg-format--bin "ruff") "ruff"))))))

(ert-deftest format-nested-projects-decide-apart ()
  (format-tests--in-project '(("web/biome.json" . "{}") ("web/x.json" . "")
                              ("api/.prettierrc" . "{}") ("api/x.json" . ""))
    (lambda ()
      (let ((root default-directory))
        (clrhash ygg-format--decisions)
        (with-temp-buffer
          (setq major-mode 'json-ts-mode)
          (let ((default-directory (expand-file-name "web/" root)))
            (should (equal (ygg-format--decide) '(biome . t))))
          (let ((default-directory (expand-file-name "api/" root)))
            (should (equal (ygg-format--decide) '(prettier-json . t)))))))))

(ert-deftest format-project-binaries-come-first ()
  (format-tests--in-project '((".venv/bin/ruff" . "#!/bin/sh\n"))
    (lambda ()
      (should (equal (ygg-format--bin "ruff")
                     (expand-file-name ".venv/bin/ruff" default-directory)))))
  (format-tests--in-project '(("node_modules/.bin/prettier" . "#!/bin/sh\n") ("src/a.ts" . ""))
    (lambda ()
      (let ((default-directory (expand-file-name "src/" default-directory)))
        (should (string-suffix-p "node_modules/.bin/prettier" (ygg-format--bin "prettier"))))))
  (format-tests--in-project '(("Gemfile.lock" . "GEM\n  specs:\n    rubocop (1.0)\n"))
    (lambda ()
      (should (equal (ygg-format--bin "rubocop") '("bundle" "exec" "rubocop")))
      (should (equal (ygg-format--bin "standardrb" "standard") "standardrb"))))
  (format-tests--in-project nil
    (lambda ()
      (should (equal (ygg-format--bin "ruff") "ruff")))))

(ert-deftest format-linters-rejoin-only-their-modes ()
  (let ((linters (lambda (mode)
                   (mapcar (lambda (tool) (plist-get tool :linter))
                           (ygg-format--rows :linter mode)))))
    (should (equal (funcall linters 'python-ts-mode) '(flymake-collection-ruff)))
    (should (equal (funcall linters 'swift-ts-mode) '(ygg-format-swiftlint)))
    (should (equal (funcall linters 'gfm-mode) '(ygg-format-markdownlint)))
    (dolist (mode '(json-ts-mode yaml-ts-mode typescript-ts-mode rust-ts-mode go-ts-mode))
      (should-not (funcall linters mode)))))

;;; format-tests.el ends here
