;;; magit-review-tests.el --- sending a commit from magit to an agent -*- lexical-binding: t; -*-

;;; Code:

(let ((builds (expand-file-name "../elpaca/builds/"
                                (file-name-directory
                                 (or load-file-name buffer-file-name)))))
  (dolist (p '("magit" "magit-section" "compat" "dash" "llama" "cond-let"
               "transient" "with-editor"))
    (add-to-list 'load-path (expand-file-name p builds))))

(require 'ert)
(require 'cl-lib)
(require 'aob)
(require 'aob-acp)
(require 'magit)
(require 'ygg-magit-review)

(setq aob-acp-persist-file (make-temp-file "magit-review-sessions-" nil ".eld"))
(setq aob-acp-show-trace nil)

(defmacro magit-review-tests--with-repo (vars &rest body)
  "A three-commit temp repo; VARS binds (ROOT HASHES) with HASHES oldest first."
  (declare (indent 1))
  (let ((root (nth 0 vars)) (hashes (nth 1 vars)))
    `(let* ((process-environment
             (append '("GIT_CONFIG_GLOBAL=/dev/null" "GIT_CONFIG_NOSYSTEM=1")
                     process-environment))
            (,root (file-name-as-directory
                    (file-truename (make-temp-file "magit-review-" t))))
            (default-directory ,root)
            (magit-refresh-verbose nil)
            (ygg-magit-review--held (make-hash-table :test #'equal))
            (ygg-magit-review--sent (make-hash-table :test #'equal))
            ,hashes)
       (unwind-protect
           (progn
             (dolist (args '(("init" "-q" "-b" "main")
                             ("config" "user.name" "Review Test")
                             ("config" "user.email" "review@example.invalid")
                             ("config" "commit.gpgsign" "false")))
               (apply #'call-process "git" nil nil nil args))
             (dolist (n '(1 2 3))
               (with-temp-file (expand-file-name (format "f%d.txt" n) ,root)
                 (insert (format "line of file %d\n" n)))
               (call-process "git" nil nil nil "add" ".")
               (call-process "git" nil nil nil "commit" "-q" "-m"
                             (format "subject number %d" n))
               (setq ,hashes
                     (append ,hashes
                             (list (string-trim
                                    (with-output-to-string
                                      (with-current-buffer standard-output
                                        (call-process "git" nil t nil
                                                      "rev-parse" "HEAD"))))))))
             ,@body)
         (dolist (b (buffer-list))
           (when (with-current-buffer b (derived-mode-p 'magit-mode))
             (kill-buffer b)))
         (delete-directory ,root t)))))

(defmacro magit-review-tests--with-sessions (specs &rest body)
  "Register sessions from SPECS, each (ID DIR &optional HIDDEN), around BODY."
  (declare (indent 1))
  `(let ((aob--sessions (make-hash-table :test #'equal))
         (aob--order nil))
     (dolist (spec ,specs)
       (let ((s (aob-create-session :id (car spec) :backend 'acp
                                    :name (car spec) :project (cadr spec)
                                    :state 'idle)))
         (when (nth 2 spec) (aob-session-put s :hidden t))))
     ,@body))

(defun magit-review-tests--goto (text)
  (goto-char (point-min))
  (search-forward text)
  (beginning-of-line))

(ert-deftest magit-review-status-commit-at-point ()
  (magit-review-tests--with-repo (root hashes)
    (with-current-buffer (magit-status-setup-buffer root)
      (magit-review-tests--goto "subject number 2")
      (should (equal (ygg-magit-review--target) (nth 1 hashes))))))

(ert-deftest magit-review-log-commit-at-point ()
  (magit-review-tests--with-repo (root hashes)
    (with-current-buffer (magit-log-setup-buffer (list "main") nil nil)
      (magit-review-tests--goto "subject number 1")
      (should (equal (ygg-magit-review--target) (nth 0 hashes))))))

(ert-deftest magit-review-marked-range ()
  (magit-review-tests--with-repo (root hashes)
    (with-current-buffer (magit-log-setup-buffer (list "main") nil nil)
      (transient-mark-mode 1)
      (magit-review-tests--goto "subject number 3")
      (push-mark (point) t t)
      (magit-review-tests--goto "subject number 2")
      (should (equal (ygg-magit-review--target)
                     (format "%s^..%s" (nth 1 hashes) (nth 2 hashes)))))))

(ert-deftest magit-review-no-commit-refuses ()
  (magit-review-tests--with-repo (root hashes)
    (with-temp-file (expand-file-name "loose.txt" root) (insert "x\n"))
    (with-current-buffer (magit-status-setup-buffer root)
      (magit-review-tests--goto "Untracked files")
      (should (equal (cadr (should-error (ygg-magit-review--target)
                                         :type 'user-error))
                     "No commit at point")))))

(ert-deftest magit-review-prompt-carries-commit ()
  (magit-review-tests--with-repo (root hashes)
    (let ((p (ygg-magit-review-prompt root (nth 1 hashes))))
      (should (string-prefix-p ygg-magit-review-instructions p))
      (should (string-search (nth 1 hashes) p))
      (should (string-search "subject number 2" p))
      (should (string-search "+line of file 2" p))
      (should (string-search "<commit>" p))
      (should-not (string-search "left out" p))
      (should-not (string-search "not in" p)))))

(ert-deftest magit-review-prompt-range-and-elsewhere ()
  (magit-review-tests--with-repo (root hashes)
    (let ((p (ygg-magit-review-prompt
              root (format "%s^..%s" (nth 1 hashes) (nth 2 hashes)) "/far/away")))
      (should (string-search "<commits>" p))
      (should (string-search "subject number 2" p))
      (should (string-search "subject number 3" p))
      (should-not (string-search "subject number 1" p))
      (should (string-search "+line of file 3" p))
      (should (string-search "You work in /far/away" p)))))

(ert-deftest magit-review-range-from-root-commit ()
  (magit-review-tests--with-repo (root hashes)
    (let ((p (ygg-magit-review-prompt
              root (format "%s^..%s" (nth 0 hashes) (nth 2 hashes)))))
      (should (string-search "subject number 1" p))
      (should (string-search "+line of file 1" p))
      (should (string-search "+line of file 3" p))
      (should-not (string-search "fatal" p)))))

(ert-deftest magit-review-git-failure-refuses ()
  (magit-review-tests--with-repo (root hashes)
    (should-error (ygg-magit-review-prompt root "no-such-revision")
                  :type 'user-error)))

(ert-deftest magit-review-cap-notes-what-was-cut ()
  (magit-review-tests--with-repo (root hashes)
    (let* ((ygg-magit-review-max-chars 100)
           (full (ygg-magit-review--git root "show" "--stat" "--patch"
                                        "--format=fuller" (nth 2 hashes)))
           (p (ygg-magit-review-prompt root (nth 2 hashes))))
      (should (string-search (format "… %d more characters left out"
                                     (- (length full) 100))
                             p))
      (should-not (string-search "+line of file 3" p)))))

(ert-deftest magit-review-picker-orders-and-hides ()
  (magit-review-tests--with-repo (root hashes)
    (magit-review-tests--with-sessions
        (list (list "here" root)
              (list "hidden-here" root t)
              (list "elsewhere" "/tmp/other-project/"))
      (let* ((aob-acp-agents '(("claude" :command ("x")) ("codex" :command ("y"))))
             (cands (ygg-magit-review-candidates root))
             (names (mapcar (lambda (c) (if (or (eq (cdr c) 'review)
                                                (eq (car-safe (cdr c)) 'new))
                                            (car c)
                                          (aob-session-name (cdr c))))
                            cands)))
        (should (equal names '("new: review plan (preset review)"
                               "here" "elsewhere" "new: claude" "new: codex")))))))

(ert-deftest magit-review-live-session-gets-prompt ()
  (magit-review-tests--with-repo (root hashes)
    (magit-review-tests--with-sessions (list (list "here" root))
      (let (sent shown)
        (cl-letf (((symbol-function 'completing-read)
                   (lambda (_p table &rest _)
                     (car (all-completions "here" table))))
                  ((symbol-function 'aob-prompt)
                   (lambda (s text &rest _) (push (list s text aob-prompt-typed) sent)))
                  ((symbol-function 'aob-trace) (lambda (s) (push s shown))))
          (with-current-buffer (magit-status-setup-buffer root)
            (magit-review-tests--goto "subject number 3")
            (ygg-magit-review-commit)))
        (should (equal (aob-session-name (car (car sent))) "here"))
        (should (string-search (nth 2 hashes) (nth 1 (car sent))))
        (should-not (string-search "You work in" (nth 1 (car sent))))
        (should (nth 2 (car sent)))
        (should (equal shown (list (car (car sent)))))))))

(ert-deftest magit-review-new-agent-spawns-then-sends ()
  (magit-review-tests--with-repo (root hashes)
    (magit-review-tests--with-sessions nil
      (let ((aob-acp-agents '(("claude" :command ("x"))))
            spawned sent)
        (cl-letf (((symbol-function 'completing-read)
                   (lambda (&rest _) "new: claude"))
                  ((symbol-function 'aob-acp-spawn)
                   (lambda (agent &rest _)
                     (push (list agent aob-acp-start-dir default-directory) spawned)
                     (aob-create-session :id "fresh" :backend 'acp :name "fresh"
                                         :project aob-acp-start-dir
                                         :state 'starting)))
                  ((symbol-function 'aob-prompt)
                   (lambda (s text &rest _) (push (list s text) sent)))
                  ((symbol-function 'aob-trace) #'ignore))
          (with-current-buffer (magit-log-setup-buffer (list "main") nil nil)
            (magit-review-tests--goto "subject number 1")
            (ygg-magit-review-commit)))
        (should (equal spawned (list (list "claude" root root))))
        (should (equal (aob-session-name (car (car sent))) "fresh"))
        (should (string-search (nth 0 hashes) (nth 1 (car sent))))))))

;;; Comments held on diff lines

(require 'ygg-preset)

(defconst magit-review-tests--presets
  (expand-file-name "../presets/" (file-name-directory
                                   (or load-file-name buffer-file-name))))

(defun magit-review-tests--write (root file text)
  (with-temp-file (expand-file-name file root) (insert text)))

(defun magit-review-tests--commit (root message)
  "Commit everything in ROOT as MESSAGE; its full hash."
  (let ((default-directory root))
    (call-process "git" nil nil nil "add" ".")
    (call-process "git" nil nil nil "commit" "-q" "-m" message)
    (string-trim (with-output-to-string
                   (with-current-buffer standard-output
                     (call-process "git" nil t nil "rev-parse" "HEAD"))))))

(defun magit-review-tests--two-file-commit (root)
  "A fourth commit changing f1.txt and f2.txt; its hash."
  (magit-review-tests--write root "f1.txt" "changed line of file 1\n")
  (magit-review-tests--write root "f2.txt" "line of file 2\nsecond line of file 2\n")
  (magit-review-tests--commit root "subject number 4"))

(defun magit-review-tests--say (buf text)
  "Write TEXT into the compose draft BUF and send it."
  (with-current-buffer buf
    (erase-buffer)
    (insert text)
    (aob-compose-send)))

(defun magit-review-tests--drawn ()
  "The comment texts drawn in this buffer, in buffer order."
  (mapcar (lambda (o) (overlay-get o 'after-string))
          (sort (seq-filter (lambda (o) (overlay-get o 'ygg-magit-review))
                            (overlays-in (point-min) (point-max)))
                (lambda (a b) (< (overlay-start a) (overlay-start b))))))

(ert-deftest magit-review-comment-anchors-worktree-new-side ()
  (magit-review-tests--with-repo (root hashes)
    (magit-review-tests--write root "f2.txt" "line of file 2\nadded line\n")
    (with-current-buffer (magit-status-setup-buffer root)
      (magit-review-tests--goto "+added line")
      (let ((buf (ygg-magit-review-comment)))
        (magit-review-tests--say buf "why is this here\nsecond thought"))
      (let ((c (car (gethash root ygg-magit-review--held))))
        (should (equal (plist-get c :file) "f2.txt"))
        (should (equal (plist-get c :line) 2))
        (should (eq (plist-get c :side) 'new))
        (should (equal (plist-get c :commit) "working tree"))
        (should (string-search "+added line" (plist-get c :quote)))
        (should (string-search " line of file 2" (plist-get c :quote)))
        (should (equal (plist-get c :text) "why is this here\nsecond thought")))
      (should (string-search "second thought" (car (magit-review-tests--drawn))))
      (magit-refresh)
      (should (= (length (magit-review-tests--drawn)) 1))
      (should (string-search "why is this here" (car (magit-review-tests--drawn)))))))

(ert-deftest magit-review-keys-in-a-hunk ()
  (magit-review-tests--with-repo (root hashes)
    (magit-review-tests--write root "f2.txt" "line of file 2\nadded line\n")
    (with-current-buffer (magit-status-setup-buffer root)
      (magit-review-tests--goto "+added line")
      (should (eq (key-binding "C") #'ygg-magit-review-comment))
      (should (eq (key-binding ",") #'magit-commit-add-log))
      (magit-review-tests--goto "subject number 2")
      (should (eq (key-binding "C") #'magit-clone))
      (magit-review-tests--goto "+added line")
      (let ((buf (call-interactively (key-binding "C"))))
        (with-current-buffer buf
          (should ygg-magit-review-comment-mode)
          (should (equal aob-compose--tags '("ZZ holds" "C-RET sends all")))
          (should (eq (key-binding (kbd "<C-return>"))
                      #'ygg-magit-review-comment-send-now))
          (should (eq (key-binding (kbd "<s-return>"))
                      #'ygg-magit-review-comment-send-now)))
        (magit-review-tests--say buf "held by ZZ"))
      (should (equal (plist-get (car (gethash root ygg-magit-review--held)) :text)
                     "held by ZZ")))))

(ert-deftest magit-review-control-return-holds-and-sends-all ()
  (magit-review-tests--with-repo (root hashes)
    (magit-review-tests--write root "f2.txt" "line of file 2\nadded line\n")
    (magit-review-tests--write root "f3.txt" "line of file 3\nother line\n")
    (magit-review-tests--with-sessions (list (list "here" root))
      (let (sent picked)
        (cl-letf (((symbol-function 'completing-read)
                   (lambda (_p table &rest _)
                     (push (all-completions "" table) picked)
                     (car (all-completions "here" table))))
                  ((symbol-function 'aob-prompt)
                   (lambda (s text &rest _) (push (list s text) sent)))
                  ((symbol-function 'aob-trace) #'ignore))
          (with-current-buffer (magit-status-setup-buffer root)
            (magit-review-tests--goto "+other line")
            (ygg-magit-review--hold root (ygg-magit-review--anchor) "held before")
            (magit-review-tests--goto "+added line")
            (with-current-buffer (ygg-magit-review-comment)
              (erase-buffer)
              (insert "sent at once")
              (ygg-magit-review-comment-send-now))))
        (should (equal (car (car picked)) "new: review plan (preset review)"))
        (should (= (length sent) 1))
        (should (equal (aob-session-name (car (car sent))) "here"))
        (should (string-search "held before" (nth 1 (car sent))))
        (should (string-search "sent at once" (nth 1 (car sent))))
        (should (string-prefix-p ygg-magit-review-comments-instructions
                                 (nth 1 (car sent))))
        (should-not (gethash root ygg-magit-review--held))
        (should (= (length (gethash root ygg-magit-review--sent)) 2))))))

(ert-deftest magit-review-comment-anchors-commit-old-side ()
  (magit-review-tests--with-repo (root hashes)
    (let ((hash (magit-review-tests--two-file-commit root)))
      (with-current-buffer (magit-revision-setup-buffer hash nil nil)
        (magit-review-tests--goto "-line of file 1")
        (ygg-magit-review--hold root (ygg-magit-review--anchor) "keep this")
        (let ((c (car (gethash root ygg-magit-review--held))))
          (should (equal (plist-get c :file) "f1.txt"))
          (should (equal (plist-get c :line) 1))
          (should (eq (plist-get c :side) 'old))
          (should (equal (plist-get c :commit) hash))
          (should-not (plist-get c :diff)))))))

(ert-deftest magit-review-comment-off-a-diff-line-refuses ()
  (magit-review-tests--with-repo (root hashes)
    (with-current-buffer (magit-status-setup-buffer root)
      (magit-review-tests--goto "subject number 2")
      (should-error (ygg-magit-review--anchor) :type 'user-error))))

(ert-deftest magit-review-comments-survive-refresh-and-are-drawn ()
  (magit-review-tests--with-repo (root hashes)
    (let ((hash (magit-review-tests--two-file-commit root)))
      (with-current-buffer (magit-revision-setup-buffer hash nil nil)
        (magit-review-tests--goto "+second line of file 2")
        (ygg-magit-review--hold root (ygg-magit-review--anchor) "name it better")
        (should (string-search "name it better" (car (magit-review-tests--drawn))))
        (magit-refresh)
        (let ((drawn (magit-review-tests--drawn)))
          (should (= (length drawn) 1))
          (should (string-search "name it better" (car drawn))))
        (let ((o (seq-find (lambda (o) (overlay-get o 'ygg-magit-review))
                           (overlays-in (point-min) (point-max)))))
          (should (string-prefix-p "+second line of file 2"
                                   (buffer-substring (overlay-start o) (overlay-end o))))))
      (with-current-buffer (magit-status-setup-buffer root)
        (should-not (magit-review-tests--drawn))))))

(ert-deftest magit-review-list-drops-and-edits ()
  (magit-review-tests--with-repo (root hashes)
    (let ((hash (magit-review-tests--two-file-commit root)))
      (with-current-buffer (magit-revision-setup-buffer hash nil nil)
        (magit-review-tests--goto "+changed line of file 1")
        (ygg-magit-review--hold root (ygg-magit-review--anchor) "first comment")
        (magit-review-tests--goto "+second line of file 2")
        (ygg-magit-review--hold root (ygg-magit-review--anchor) "second comment")
        (with-current-buffer (ygg-magit-review-list)
          (should (derived-mode-p 'ygg-magit-review-list-mode))
          (should (string-search "f1.txt:1" (buffer-string)))
          (should (string-search "f2.txt:2" (buffer-string)))
          (goto-char (point-min))
          (ygg-magit-review-list-drop)
          (should-not (string-search "first comment" (buffer-string)))
          (goto-char (point-min))
          (magit-review-tests--say (ygg-magit-review-list-edit) "rewritten words"))
        (let ((cs (gethash root ygg-magit-review--held)))
          (should (= (length cs) 1))
          (should (equal (plist-get (car cs) :text) "rewritten words")))
        (should (equal (length (magit-review-tests--drawn)) 1))
        (should (string-search "rewritten words" (car (magit-review-tests--drawn))))))))

(ert-deftest magit-review-send-carries-every-comment-once-and-undoes ()
  (magit-review-tests--with-repo (root hashes)
    (let ((hash (magit-review-tests--two-file-commit root)))
      (with-current-buffer (magit-revision-setup-buffer hash nil nil)
        (magit-review-tests--goto "+second line of file 2")
        (ygg-magit-review--hold root (ygg-magit-review--anchor) "comment on f2")
        (magit-review-tests--goto "-line of file 1")
        (ygg-magit-review--hold root (ygg-magit-review--anchor) "comment on f1"))
      (magit-review-tests--write root "f3.txt" "line of file 3\nloose edit\n")
      (with-current-buffer (magit-status-setup-buffer root)
        (magit-review-tests--goto "+loose edit")
        (ygg-magit-review--hold root (ygg-magit-review--anchor) "comment on f3"))
      (magit-review-tests--with-sessions (list (list "here" root))
        (let (sent)
          (cl-letf (((symbol-function 'completing-read)
                     (lambda (_p table &rest _) (car (all-completions "here" table))))
                    ((symbol-function 'aob-prompt)
                     (lambda (s text &rest _) (push (list s text) sent)))
                    ((symbol-function 'aob-trace) #'ignore))
            (with-current-buffer (magit-status-setup-buffer root)
              (magit-review-tests--goto "Recent commits")
              (ygg-magit-review-commit)))
          (should (= (length sent) 1))
          (let ((m (nth 1 (car sent))))
            (should (string-prefix-p ygg-magit-review-comments-instructions m))
            (should (< (string-search "## f1.txt" m) (string-search "## f2.txt" m)
                       (string-search "## f3.txt" m)))
            (dolist (text '("comment on f1" "comment on f2" "comment on f3"
                            "f1.txt:1 (removed line)" "f2.txt:2 · " "> +loose edit"))
              (should (string-search text m)))
            (should (string-search (concat "f3.txt:2 · working tree") m))
            (should (= (magit-review-tests--count m "<commit>\n") 1))
            (should (= (magit-review-tests--count m "<diff>\n") 1))
            (should (string-search (concat "commit " hash) m))
            (should (string-search "+loose edit" (substring m (string-search "<diff>" m))))
            (should-not (string-search "Review this commit" m)))))
      (should-not (gethash root ygg-magit-review--held))
      (with-current-buffer (ygg-magit-review-list)
        (should (string-search "u brings back the 3 sent" (buffer-string)))
        (ygg-magit-review-list-undo)
        (should (= (length (gethash root ygg-magit-review--held)) 3))
        (should-error (ygg-magit-review-list-undo) :type 'user-error)))))

(defun magit-review-tests--count (string needle)
  (let ((start 0) (n 0))
    (while (setq start (string-search needle string start))
      (setq n (1+ n) start (1+ start)))
    n))

(ert-deftest magit-review-send-without-comments-reviews-the-commit ()
  (magit-review-tests--with-repo (root hashes)
    (magit-review-tests--with-sessions (list (list "here" root))
      (let (sent)
        (cl-letf (((symbol-function 'completing-read)
                   (lambda (_p table &rest _) (car (all-completions "here" table))))
                  ((symbol-function 'aob-prompt)
                   (lambda (_s text &rest _) (push text sent)))
                  ((symbol-function 'aob-trace) #'ignore))
          (with-current-buffer (magit-status-setup-buffer root)
            (magit-review-tests--goto "subject number 2")
            (ygg-magit-review-commit)))
        (should (string-prefix-p ygg-magit-review-instructions (car sent)))
        (should (string-search (nth 1 hashes) (car sent)))
        (should-not (string-search "<review-comments>" (car sent)))
        (should-not (gethash root ygg-magit-review--sent))))))

(ert-deftest magit-review-first-choice-spawns-under-review-preset ()
  (magit-review-tests--with-repo (root hashes)
    (let ((hash (magit-review-tests--two-file-commit root))
          (ygg-preset-user-directory (make-temp-file "magit-review-presets-" t)))
      (with-current-buffer (magit-revision-setup-buffer hash nil nil)
        (magit-review-tests--goto "+second line of file 2")
        (ygg-magit-review--hold root (ygg-magit-review--anchor) "plan this @build")
        (magit-review-tests--with-sessions (list (list "here" root))
          (let* (spawned prompted
                 (aob-compose-spawn-function
                  (lambda (text &rest _)
                    (push (list text aob-compose--dir aob-prompt-typed) spawned)
                    (aob-create-session :id "planner" :backend 'acp :name "planner"
                                        :project aob-compose--dir :state 'starting))))
            (cl-letf (((symbol-function 'completing-read)
                       (lambda (_p table &rest _) (car (all-completions "" table))))
                      ((symbol-function 'ygg-aob--expand-presets)
                       (lambda (text)
                         (let ((known (ygg-preset-list default-directory)))
                           (dolist (p known text)
                             (when (string-search (concat "@" (ygg-preset-name p)) text)
                               (setq text (format "%s\n\n<preset name=\"%s\">\n%s\n</preset>"
                                                  text (ygg-preset-name p)
                                                  (ygg-preset-body p))))))))
                      ((symbol-function 'aob-prompt)
                       (lambda (&rest args) (push args prompted)))
                      ((symbol-function 'aob-trace) #'ignore))
              (ygg-magit-review-commit))
            (should (= (length spawned) 1))
            (pcase-let ((`(,text ,dir ,typed) (car spawned)))
              (should (string-prefix-p "@review " text))
              (should (string-search "<preset name=\"review\">" text))
              (should-not (string-search "<preset name=\"build\">" text))
              (should (string-search "plan this @build" text))
              (should (equal dir root))
              (should typed))
            (should-not prompted)
            (should-not (gethash root ygg-magit-review--held))))))))

(ert-deftest magit-review-preset-parses-like-spec ()
  (let* ((dir magit-review-tests--presets)
         (keys (lambda (file)
                 (let ((fields (car (ygg-preset--parse (expand-file-name file dir))))
                       out)
                   (while fields (push (pop fields) out) (pop fields))
                   (nreverse out))))
         (review (ygg-preset--parse (expand-file-name "review.md" dir))))
    (should (equal (funcall keys "review.md") (funcall keys "spec.md")))
    (should (equal (plist-get (car review) :name) "review"))
    (should (member (plist-get (car review) :mode) ygg-preset-modes))
    (should (string-search "todo_write" (cdr review)))
    (should (< (with-temp-buffer
                 (insert-file-contents (expand-file-name "review.md" dir))
                 (buffer-size))
               2000))))

(provide 'magit-review-tests)
;;; magit-review-tests.el ends here
