;;; ts-server-tests.el --- Tests for the TypeScript server choice -*- lexical-binding: t; -*-

(require 'ert)
(require 'cl-lib)
(require 'eglot)
(require 'yggdrasil)
(require 'layer-lsp)
(require 'layer-rass)

(defmacro ts-tests--with-binaries (binaries &rest body)
  "Run BODY where only BINARIES are runnable."
  (declare (indent 1))
  `(cl-letf (((symbol-function 'ygg-lsp--executable)
              (lambda (name) (and (member name ,binaries) (concat "/bin/" name))))
             ((symbol-function 'file-executable-p)
              (lambda (file) (and (member "tsc" ,binaries) (string-suffix-p "/tsc" file)))))
     ,@body))

(defmacro ts-tests--with-server-command (command &rest body)
  "Run BODY with every server's process command being COMMAND."
  (declare (indent 1))
  `(cl-letf (((symbol-function 'jsonrpc--process) (lambda (_) 'process))
             ((symbol-function 'process-command) (lambda (_) ,command)))
     ,@body))

(ert-deftest ts-server-defaults-to-typescript-language-server ()
  (should (eq (default-value 'ygg-lsp-ts-server) 'tsls))
  (ts-tests--with-binaries '("typescript-language-server" "vtsls" "bunx")
    (let ((ygg-lsp-ts-server 'tsls))
      (should (equal (ygg-lsp-ts-command)
                     `("typescript-language-server" "--stdio"
                       :initializationOptions ,ygg-lsp--tsls-initialization-options))))))

(ert-deftest ts-server-tsls-starts-with-inlay-hints-and-no-typing-acquisition ()
  (let ((options ygg-lsp--tsls-initialization-options))
    (should (eq (plist-get options :disableAutomaticTypingAcquisition) t))
    (should (equal (plist-get (plist-get options :preferences) :includeInlayParameterNameHints)
                   "all"))
    (should (eq (plist-get (plist-get options :preferences) :providePrefixAndSuffixTextForRename)
                :json-false))))

(ert-deftest ts-server-falls-back-along-the-chain ()
  (let ((ygg-lsp-ts-server 'tsls))
    (ts-tests--with-binaries '("vtsls" "bunx")
      (should (equal (ygg-lsp-ts-command) '("vtsls" "--stdio"))))
    (ts-tests--with-binaries '("bunx")
      (should (equal (ygg-lsp-ts-command) '("bunx" "@vtsls/language-server" "--stdio"))))
    (ts-tests--with-binaries '()
      (should-not (ygg-lsp-ts-command))))
  (let ((ygg-lsp-ts-server 'vtsls))
    (ts-tests--with-binaries '("typescript-language-server" "vtsls")
      (should (equal (ygg-lsp-ts-command) '("vtsls" "--stdio"))))
    (ts-tests--with-binaries '("typescript-language-server" "bunx")
      (should (equal (car (ygg-lsp-ts-command)) "typescript-language-server")))))

(ert-deftest ts-server-tsgo-runs-its-own-tsc-and-falls-back ()
  (let ((ygg-lsp-ts-server 'tsgo)
        (ygg-lsp-tsgo-program "/opt/tsgo/node_modules/.bin/tsc"))
    (ts-tests--with-binaries '("tsc" "typescript-language-server")
      (should (equal (ygg-lsp-ts-command)
                     '("/opt/tsgo/node_modules/.bin/tsc" "--lsp" "--stdio"))))
    (ts-tests--with-binaries '("typescript-language-server")
      (should (equal (car (ygg-lsp-ts-command)) "typescript-language-server")))))

(ert-deftest ts-server-kind-is-read-through-rass ()
  (ts-tests--with-server-command
      '("rass" "/x/rass-typescript.py" "--" "typescript-language-server" "--stdio"
        "--" "vscode-eslint-language-server" "--stdio")
    (should (eq (ygg-lsp-ts-server-kind 'server) 'tsls)))
  (ts-tests--with-server-command '("bunx" "@vtsls/language-server" "--stdio")
    (should (eq (ygg-lsp-ts-server-kind 'server) 'vtsls)))
  (ts-tests--with-server-command '("/Users/me/.bun/bin/vtsls" "--stdio")
    (should (eq (ygg-lsp-ts-server-kind 'server) 'vtsls)))
  (ts-tests--with-server-command '("/opt/tsgo/node_modules/.bin/tsc" "--lsp" "--stdio")
    (should (eq (ygg-lsp-ts-server-kind 'server) 'tsgo)))
  (ts-tests--with-server-command '("rust-analyzer")
    (should-not (ygg-lsp-ts-server-kind 'server))))

(ert-deftest ts-server-workspace-configuration-completes-function-calls ()
  (should (functionp (default-value 'eglot-workspace-configuration)))
  (cl-letf (((symbol-function 'eglot--major-modes) (lambda (_) '(tsx-ts-mode))))
    (let ((default-directory temporary-file-directory))
      (ts-tests--with-server-command
          '("rass" "--" "typescript-language-server" "--stdio" "--" "vscode-eslint-language-server")
        (should (equal (plist-get (funcall (default-value 'eglot-workspace-configuration) 'server)
                                  :completions)
                       '(:completeFunctionCalls t))))
      (ts-tests--with-server-command '("vtsls" "--stdio")
        (let ((settings (funcall (default-value 'eglot-workspace-configuration) 'server)))
          (should (equal (plist-get settings :vtsls) '(:autoUseWorkspaceTsdk t)))
          (should-not (plist-get settings :completions))))
      (ts-tests--with-server-command '("typescript-language-server" "--stdio")
        (should-not (plist-get (funcall (default-value 'eglot-workspace-configuration) 'server)
                               :vtsls))))))

(ert-deftest ts-server-source-definition-asks-each-server-its-own-way ()
  (let (sent)
    (cl-letf (((symbol-function 'eglot--TextDocumentPositionParams)
               (lambda () '(:textDocument (:uri "file:///a.ts") :position (:line 1 :character 2))))
              ((symbol-function 'jsonrpc-request)
               (lambda (_server method params &rest keys)
                 (push (list method params (plist-get keys :timeout)) sent)
                 [])))
      (ts-tests--with-server-command '("typescript-language-server" "--stdio")
        (ygg-lsp--ts-source-locations 'server))
      (ts-tests--with-server-command '("vtsls" "--stdio")
        (ygg-lsp--ts-source-locations 'server))
      (ts-tests--with-server-command '("/opt/tsgo/tsc" "--lsp" "--stdio")
        (ygg-lsp--ts-source-locations 'server)))
    (setq sent (nreverse sent))
    (should (equal (car sent)
                   '(:workspace/executeCommand
                     (:command "_typescript.goToSourceDefinition"
                      :arguments ["file:///a.ts" (:line 1 :character 2)])
                     60)))
    (should (equal (plist-get (nth 1 (nth 1 sent)) :command) "typescript.goToSourceDefinition"))
    (should (equal (car (nth 2 sent)) :custom/textDocument/sourceDefinition))
    (should (equal (nth 2 (nth 2 sent)) 60))))

(ert-deftest ts-server-source-definition-sits-under-the-server-extras ()
  (require 'yggdrasil-localleader)
  (dolist (mode '(js-mode js-ts-mode typescript-ts-mode tsx-ts-mode))
    (let ((binding (lookup-key (ygg-localleader--get-map mode) (kbd "m s"))))
      (should (eq (if (consp binding) (cdr binding) binding)
                  #'ygg-lsp-ts-source-definition)))))

;;; ts-server-tests.el ends here
