;;; ygg-dart-sdk-tests.el --- Dart resolves onto the Flutter SDK's Dart -*- lexical-binding: t; -*-

(setq load-prefer-newer t)
(require 'ert)
(require 'cl-lib)
(require 'yggdrasil)
(require 'layer-lsp)
(require 'layer-dap)
(require 'dape)

(defun ygg-dart-sdk-tests--script (file body)
  (make-directory (file-name-directory file) t)
  (with-temp-file file (insert "#!/bin/sh\n" body "\n"))
  (set-file-modes file #o755)
  file)

(defmacro ygg-dart-sdk-tests--world (vars &rest body)
  "Run BODY in a fake mise world; VARS is (TMP SHIMS PROJECT INSTALL COUNTER)."
  (declare (indent 1))
  (pcase-let ((`(,tmp ,shims ,project ,install ,counter) vars))
    `(let* ((,tmp (file-name-as-directory (file-truename (make-temp-file "ygg-dart" t))))
            (,shims (concat ,tmp "mise/shims/"))
            (,project (concat ,tmp "proj/"))
            (,install (concat ,tmp "mise/installs/flutter/1.0/"))
            (,counter (concat ,tmp "calls"))
            (ygg-lsp--dart-which-cache (make-hash-table :test 'equal))
            (exec-path (list (concat ,tmp "bin") ,shims))
            (process-environment (cons (concat "PATH=" ,tmp "bin:" ,shims) process-environment)))
       (make-directory ,project t)
       (with-temp-file (concat ,project ".tool-versions") (insert "flutter 1.0\n"))
       (ygg-dart-sdk-tests--script (concat ,install "bin/dart") "exit 0")
       (ygg-dart-sdk-tests--script (concat ,tmp "bin/mise")
                                   (format "echo x >> %s\necho %sbin/dart" ,counter ,install))
       (make-directory ,shims t)
       (make-symbolic-link (concat ,tmp "bin/mise") (concat ,shims "dart") t)
       (unwind-protect (progn ,@body)
         (delete-directory ,tmp t)))))

(defun ygg-dart-sdk-tests--cache-dart (install)
  (ygg-dart-sdk-tests--script (concat install "bin/cache/dart-sdk/bin/dart") "exit 0"))

(defun ygg-dart-sdk-tests--calls (counter)
  (if (file-exists-p counter)
      (with-temp-buffer (insert-file-contents counter) (count-lines (point-min) (point-max)))
    0))

(ert-deftest ygg-dart-sdk-tests-mise-shim-resolves-to-cached-sdk-dart ()
  (ygg-dart-sdk-tests--world (tmp shims project install counter)
    (let ((cached (ygg-dart-sdk-tests--cache-dart install)))
      (should (equal (ygg-lsp--dart-sdk-dart project) cached)))))

(ert-deftest ygg-dart-sdk-tests-missing-cache-falls-back-to-wrapper ()
  (ygg-dart-sdk-tests--world (tmp shims project install counter)
    (should (equal (ygg-lsp--dart-sdk-dart project) (concat install "bin/dart")))))

(ert-deftest ygg-dart-sdk-tests-fvm-wins-over-mise ()
  (ygg-dart-sdk-tests--world (tmp shims project install counter)
    (ygg-dart-sdk-tests--cache-dart install)
    (let* ((fvm (concat tmp "fvm-sdk/"))
           (fvm-dart (ygg-dart-sdk-tests--cache-dart fvm)))
      (make-directory (concat project ".fvm") t)
      (make-symbolic-link fvm (concat project ".fvm/flutter_sdk"))
      (make-directory (concat project "apps/a") t)
      (should (equal (file-truename (ygg-lsp--dart-sdk-dart (concat project "apps/a")))
                     (file-truename fvm-dart)))
      (should (= 0 (ygg-dart-sdk-tests--calls counter))))))

(ert-deftest ygg-dart-sdk-tests-plain-dart-is-returned-as-is ()
  (ygg-dart-sdk-tests--world (tmp shims project install counter)
    (let ((plain (ygg-dart-sdk-tests--script (concat tmp "plain/bin/dart") "exit 0")))
      (ygg-dart-sdk-tests--script (concat tmp "bin/mise") (format "echo %s" plain))
      (should (equal (ygg-lsp--dart-sdk-dart project) plain)))))

(ert-deftest ygg-dart-sdk-tests-mise-failure-keeps-the-shim ()
  (ygg-dart-sdk-tests--world (tmp shims project install counter)
    (ygg-dart-sdk-tests--script (concat tmp "bin/mise") "exit 1")
    (should (equal (ygg-lsp--dart-sdk-dart project) (concat shims "dart")))))

(ert-deftest ygg-dart-sdk-tests-second-call-hits-the-cache ()
  (ygg-dart-sdk-tests--world (tmp shims project install counter)
    (ygg-dart-sdk-tests--cache-dart install)
    (ygg-lsp--dart-sdk-dart project)
    (ygg-lsp--dart-sdk-dart (concat project "sub/"))
    (should (= 1 (ygg-dart-sdk-tests--calls counter)))
    (sleep-for 1.1)
    (with-temp-file (concat project ".tool-versions") (insert "flutter 2.0\n"))
    (ygg-lsp--dart-sdk-dart project)
    (should (= 2 (ygg-dart-sdk-tests--calls counter)))))

(ert-deftest ygg-dart-sdk-tests-contact-shape ()
  (ygg-dart-sdk-tests--world (tmp shims project install counter)
    (let ((cached (ygg-dart-sdk-tests--cache-dart install))
          (default-directory project))
      (should (equal (seq-take (ygg-lsp-dart-contact) 3)
                     (list cached "language-server" "--protocol=lsp"))))))

(ert-deftest ygg-dart-sdk-tests-dape-dart-command-resolves-the-same ()
  (ygg-dart-sdk-tests--world (tmp shims project install counter)
    (let ((cached (ygg-dart-sdk-tests--cache-dart install))
          (default-directory project)
          (command (plist-get (cdr (assq 'dart dape-configs)) 'command)))
      (should (functionp command))
      (cl-letf (((symbol-function 'dape-command-cwd) (lambda () project)))
        (should (equal (funcall command) cached))))))

;;; ygg-dart-sdk-tests.el ends here
