;;; ygg-git-worktree-tests.el --- a compared side run in a worktree -*- lexical-binding: t; -*-

;;; Code:

(let* ((here (file-name-directory (or load-file-name buffer-file-name)))
       (builds (expand-file-name "../elpaca/builds/" here)))
  (dolist (p '("magit" "magit-section" "compat" "dash" "llama" "cond-let"
               "transient" "with-editor"))
    (add-to-list 'load-path (expand-file-name p builds))))

(require 'ert)
(require 'cl-lib)
(require 'magit)
(require 'ygg-git-compare)
(require 'ygg-git-worktree)

(defun ygg-git-worktree-tests--git (dir &rest args)
  (let ((default-directory dir))
    (with-temp-buffer
      (unless (zerop (apply #'call-process "git" nil t nil args))
        (error "git %S failed: %s" args (buffer-string)))
      (string-trim (buffer-string)))))

(defmacro ygg-git-worktree-tests--with-repo (vars &rest body)
  "A repo at OUTER/main on main, with a branch feature one commit ahead.
VARS binds (OUTER ROOT).  Spaces, tasks and wt are stubbed out;
`opened' holds the directories spaces were opened on and `asked' the
questions put, answered from `answers'."
  (declare (indent 1))
  (let ((outer (nth 0 vars)) (root (nth 1 vars)))
    `(let* ((process-environment
             (append '("GIT_CONFIG_GLOBAL=/dev/null" "GIT_CONFIG_NOSYSTEM=1")
                     process-environment))
            (,outer (file-name-as-directory
                     (file-truename (make-temp-file "ygg-compare-worktree-" t))))
            (,root (file-name-as-directory (expand-file-name "main" ,outer)))
            (default-directory (progn (make-directory ,root) ,root))
            (magit-refresh-verbose nil)
            (opened nil)
            (asked nil)
            (answers nil)
            (real-executable-find (symbol-function 'executable-find)))
       (unwind-protect
           (cl-letf (((symbol-function 'executable-find)
                      (lambda (cmd &rest args)
                        (unless (equal cmd "wt")
                          (apply real-executable-find cmd args))))
                     ((symbol-function 'ygg-space-new-on)
                      (lambda (dir) (push dir opened)))
                     ((symbol-function 'ygg-task--collect) #'ignore)
                     ((symbol-function 'y-or-n-p)
                      (lambda (prompt) (push prompt asked) (pop answers))))
             (cl-flet ((git (dir &rest args)
                         (apply #'ygg-git-worktree-tests--git dir args)))
               (git ,root "init" "-q" "-b" "main")
               (git ,root "config" "user.name" "Compare Test")
               (git ,root "config" "user.email" "compare@example.invalid")
               (git ,root "config" "commit.gpgsign" "false")
               (with-temp-file (expand-file-name "a.txt" ,root) (insert "1\n"))
               (git ,root "add" ".")
               (git ,root "commit" "-q" "-m" "base")
               (git ,root "checkout" "-q" "-b" "feature")
               (with-temp-file (expand-file-name "a.txt" ,root) (insert "2\n"))
               (git ,root "commit" "-q" "-am" "feature")
               (git ,root "checkout" "-q" "main")
               ,@body))
         (delete-directory ,outer t)))))

(defun ygg-git-worktree-tests--compare (root b-spec)
  "A compare buffer in ROOT of main against B-SPEC."
  (let ((buf (generate-new-buffer " *compare*")))
    (with-current-buffer buf
      (setq default-directory root)
      (setq-local ygg-git-compare--root root
                  ygg-git-compare--a-spec '(rev . "main")
                  ygg-git-compare--b-spec b-spec
                  ygg-git-compare--a (ygg-git-compare-resolve '(rev . "main"))
                  ygg-git-compare--b (ygg-git-compare-resolve b-spec)))
    buf))

(defun ygg-git-worktree-tests--finish (proc)
  (with-timeout (20 (error "git did not finish"))
    (while (or (process-live-p proc) (process-get proc 'pending))
      (accept-process-output proc 0.05))
    (accept-process-output nil 0.1)))

(defun ygg-git-worktree-tests--spin (root b-spec)
  (let ((buf (ygg-git-worktree-tests--compare root b-spec)))
    (unwind-protect
        (with-current-buffer buf
          (when-let* ((proc (call-interactively #'ygg-git-worktree-run)))
            (ygg-git-worktree-tests--finish proc)))
      (kill-buffer buf))))

(defun ygg-git-worktree-tests--list (root)
  (let ((default-directory root))
    (mapcar (lambda (w) (list (directory-file-name (nth 0 w)) (nth 2 w) (nth 4 w)))
            (magit-list-worktrees))))

(ert-deftest ygg-git-worktree-branch-side ()
  (ygg-git-worktree-tests--with-repo (outer root)
    (ygg-git-worktree-tests--spin root '(rev . "feature"))
    (let ((path (expand-file-name "main.feature" outer)))
      (should (member (list path "feature" nil)
                      (ygg-git-worktree-tests--list root)))
      (should (equal opened (list path)))
      (should (equal (let ((default-directory root)) (ygg-git-worktree--made))
                     (list path))))))

(ert-deftest ygg-git-worktree-commit-side-is-detached ()
  (ygg-git-worktree-tests--with-repo (outer root)
    (let* ((sha (git root "rev-parse" "feature"))
           (short (git root "rev-parse" "--short" "feature")))
      (ygg-git-worktree-tests--spin root (cons 'rev sha))
      (let ((path (expand-file-name (concat "main." short) outer)))
        (should (member (list path nil t) (ygg-git-worktree-tests--list root)))
        (should (equal (git path "rev-parse" "HEAD") sha))
        (should (equal opened (list path)))))))

(ert-deftest ygg-git-worktree-reused-not-duplicated ()
  (ygg-git-worktree-tests--with-repo (outer root)
    (let ((sha (git root "rev-parse" "feature")))
      (ygg-git-worktree-tests--spin root '(rev . "feature"))
      (ygg-git-worktree-tests--spin root '(rev . "feature"))
      (ygg-git-worktree-tests--spin root (cons 'rev sha))
      (ygg-git-worktree-tests--spin root (cons 'rev sha))
      (should (= (length (ygg-git-worktree-tests--list root)) 3))
      (should (= (length opened) 4))
      (should (equal (nth 0 opened) (nth 1 opened)))
      (should (equal (nth 2 opened) (nth 3 opened))))))

(ert-deftest ygg-git-worktree-worktree-side-opened-as-is ()
  (ygg-git-worktree-tests--with-repo (outer root)
    (let ((tree (expand-file-name "elsewhere" outer)))
      (git root "worktree" "add" "-q" tree "feature")
      (should-not (ygg-git-worktree-tests--spin
                   root (cons 'worktree (file-name-as-directory tree))))
      (should (= (length (ygg-git-worktree-tests--list root)) 2))
      (should (equal (mapcar #'directory-file-name opened) (list tree))))))

(ert-deftest ygg-git-worktree-remove-clean ()
  (ygg-git-worktree-tests--with-repo (outer root)
    (ygg-git-worktree-tests--spin root '(rev . "feature"))
    (let ((path (expand-file-name "main.feature" outer)))
      (setq answers '(t))
      (ygg-git-worktree-tests--finish (ygg-git-worktree-remove path))
      (should (= (length asked) 1))
      (should-not (file-exists-p path))
      (should (equal (ygg-git-worktree-tests--list root)
                     (list (list (directory-file-name root) "main" nil))))
      (should-not (ygg-git-worktree--made))
      (should (equal (git root "rev-parse" "--verify" "feature")
                     (git root "rev-parse" "feature"))))))

(ert-deftest ygg-git-worktree-remove-dirty-asks-twice ()
  (ygg-git-worktree-tests--with-repo (outer root)
    (ygg-git-worktree-tests--spin root '(rev . "feature"))
    (let ((path (expand-file-name "main.feature" outer)))
      (with-temp-file (expand-file-name "a.txt" path) (insert "dirty\n"))
      (setq answers '(nil))
      (should-error (ygg-git-worktree-remove path) :type 'user-error)
      (should (= (length asked) 1))
      (should (string-match-p "1 uncommitted change" (car asked)))
      (should (file-exists-p path))
      (setq asked nil answers '(t nil))
      (should-error (ygg-git-worktree-remove path) :type 'user-error)
      (should (= (length asked) 2))
      (should (file-exists-p path))
      (setq asked nil answers '(t t))
      (ygg-git-worktree-tests--finish (ygg-git-worktree-remove path))
      (should (= (length asked) 2))
      (should-not (file-exists-p path)))))

(ert-deftest ygg-git-worktree-remove-refused-while-compared ()
  (ygg-git-worktree-tests--with-repo (outer root)
    (ygg-git-worktree-tests--spin root '(rev . "feature"))
    (let* ((path (expand-file-name "main.feature" outer))
           (buf (ygg-git-worktree-tests--compare
                 root (cons 'worktree (file-name-as-directory path)))))
      (unwind-protect
          (should-error (ygg-git-worktree-remove path) :type 'user-error)
        (kill-buffer buf))
      (should-not asked)
      (should (file-exists-p path)))))

(ert-deftest ygg-git-worktree-remove-offers-made-first ()
  (ygg-git-worktree-tests--with-repo (outer root)
    (git root "worktree" "add" "-q" (expand-file-name "other" outer) "-b" "other")
    (ygg-git-worktree-tests--spin root '(rev . "feature"))
    (let (offered default)
      (cl-letf (((symbol-function 'completing-read)
                 (lambda (_prompt table _pred _req _init _hist def &rest _)
                   (setq offered (all-completions "" table) default def)
                   def)))
        (should (equal (ygg-git-worktree--read-removable)
                       (expand-file-name "main.feature" outer))))
      (should (equal default (expand-file-name "main.feature" outer)))
      (should (equal offered (list (expand-file-name "main.feature" outer)
                                   (expand-file-name "other" outer)))))))

(ert-deftest ygg-git-worktree-at-point ()
  (ygg-git-worktree-tests--with-repo (outer root)
    (let ((section nil) (rev nil))
      (cl-letf (((symbol-function 'magit-section-value-if)
                 (lambda (type) (and (eq type (car section)) (cdr section))))
                ((symbol-function 'magit-branch-or-commit-at-point) (lambda () rev))
                ((symbol-function 'ygg-git-compare--read)
                 (lambda (&rest _) '(rev . "read"))))
        (should (equal (ygg-git-worktree--spec-at-point) '(rev . "read")))
        (setq rev "feature")
        (should (equal (ygg-git-worktree--spec-at-point) '(rev . "feature")))
        (setq section (cons 'worktree "/some/tree/"))
        (should (equal (ygg-git-worktree--spec-at-point) '(worktree . "/some/tree/")))
        (let ((buf (ygg-git-worktree-tests--compare root '(rev . "main"))))
          (unwind-protect
              (with-current-buffer buf
                (should (equal (ygg-git-worktree--spec-at-point) '(rev . "main"))))
            (kill-buffer buf)))))))

(ert-deftest ygg-git-worktree-remove-at-point ()
  (ygg-git-worktree-tests--with-repo (outer root)
    (git root "worktree" "add" "-q" (expand-file-name "other" outer) "-b" "other")
    (let ((path (expand-file-name "other" outer)))
      (setq answers '(t))
      (cl-letf (((symbol-function 'magit-section-value-if)
                 (lambda (type) (and (eq type 'worktree) (file-name-as-directory path)))))
        (ygg-git-worktree-tests--finish (call-interactively #'ygg-git-worktree-remove)))
      (should-not (file-exists-p path))
      (cl-letf (((symbol-function 'magit-section-value-if)
                 (lambda (type) (and (eq type 'worktree) root))))
        (should-error (call-interactively #'ygg-git-worktree-remove) :type 'user-error)))))

;;; In magit status

(defun ygg-git-worktree-tests--rows (root)
  "Magit status of ROOT with only the worktrees section, as its row sections."
  (let ((magit-status-sections-hook (list #'ygg-git-worktree-insert-section))
        (default-directory root))
    (with-current-buffer (magit-status-setup-buffer root)
      (oref (seq-find (lambda (s) (eq (oref s type) 'worktrees))
                      (oref magit-root-section children))
            children))))

(defun ygg-git-worktree-tests--heading (section)
  (with-current-buffer (marker-buffer (oref section start))
    (buffer-substring-no-properties (oref section start) (oref section content))))

(ert-deftest ygg-git-worktree-status-and-remove-load-without-compare ()
  (ygg-git-worktree-tests--with-repo (outer root)
    (git root "worktree" "add" "-q" (expand-file-name "other" outer) "-b" "other")
    (let* ((shadow (make-temp-file "ygg-broken-compare-" t))
           (lisp (file-name-directory (locate-library "ygg-git-worktree")))
           (builds (expand-file-name "../elpaca/builds/" lisp))
           (form
            `(progn
               (setq load-prefer-newer t
                     load-path (append (list ,shadow ,lisp)
                                       (mapcar (lambda (p) (expand-file-name p ,builds))
                                               '("magit" "magit-section" "compat" "dash"
                                                 "llama" "cond-let" "transient" "with-editor"))
                                       load-path))
               (require 'magit)
               (require 'ygg-git-worktree)
               (let* ((default-directory ,root)
                      (magit-status-sections-hook (list #'ygg-git-worktree-insert-section))
                      (status (magit-status-setup-buffer ,root))
                      (rows (with-current-buffer status
                              (oref (seq-find (lambda (s) (eq (oref s type) 'worktrees))
                                              (oref magit-root-section children))
                                    children))))
                 (kill-emacs
                  (if (and (equal (locate-library "ygg-git-compare")
                                  (expand-file-name "ygg-git-compare.el" ,shadow))
                           (= (length rows) 2)
                           (not (ygg-git-worktree--compared-in ,root))
                           (not (featurep 'ygg-git-compare)))
                      0 1))))))
      (unwind-protect
          (progn
            (with-temp-file (expand-file-name "ygg-git-compare.el" shadow)
              (insert "(error \"ygg-git-compare is broken\")\n"))
            (should (zerop (call-process (expand-file-name invocation-name invocation-directory)
                                         nil nil nil "-Q" "-batch"
                                         "--eval" (prin1-to-string form)))))
        (delete-directory shadow t)))))

(ert-deftest ygg-git-worktree-status-nothing-for-one-tree ()
  (ygg-git-worktree-tests--with-repo (outer root)
    (with-temp-buffer
      (ygg-git-worktree-insert-section)
      (should (= (buffer-size) 0)))))

(ert-deftest ygg-git-worktree-remove-picker-annotates-paths ()
  (ygg-git-worktree-tests--with-repo (outer root)
    (let ((other (expand-file-name "other" outer)))
      (git root "worktree" "add" "-q" other "-b" "other")
      (with-temp-file (expand-file-name "new.txt" other) (insert "n\n"))
      (cl-letf (((symbol-function 'completing-read)
                 (lambda (_prompt table &rest _)
                   (let ((meta (cdr (funcall table "" nil 'metadata))))
                     (should (eq (alist-get 'category meta) 'file))
                     (should (equal (substring-no-properties
                                     (funcall (alist-get 'annotation-function meta) other))
                                    "  other *")))
                   other)))
        (should (equal (ygg-git-worktree--read-removable) other))))))

(ert-deftest ygg-git-worktree-status-rows ()
  (ygg-git-worktree-tests--with-repo (outer root)
    (ygg-git-worktree-tests--spin root '(rev . "feature"))
    (let ((made (expand-file-name "main.feature" outer))
          (detached (expand-file-name "loose" outer)))
      (git root "worktree" "add" "-q" "--detach" detached "main")
      (git root "branch" "-q" "--set-upstream-to=main" "feature")
      (with-temp-file (expand-file-name "a.txt" made) (insert "3\n"))
      (git made "add" "a.txt")
      (with-temp-file (expand-file-name "a.txt" made) (insert "4\n"))
      (with-temp-file (expand-file-name "new.txt" made) (insert "new\n"))
      (let* ((rows (ygg-git-worktree-tests--rows root))
             (heading (lambda (dir)
                        (ygg-git-worktree-tests--heading
                         (seq-find (lambda (s) (equal (directory-file-name (oref s value))
                                                      (directory-file-name dir)))
                                   rows)))))
        (ygg-git-worktree-tests--drain)
        (unwind-protect
            (progn
              (should (equal (mapcar (lambda (s) (directory-file-name (oref s value))) rows)
                             (list (directory-file-name root) detached made)))
              (should (cl-every (lambda (s) (oref s hidden)) rows))
              (should (string-match-p "\\`main .*  main here\n" (funcall heading root)))
              (should-not (string-match-p "made\\|[+~?][0-9]" (funcall heading root)))
              (should (string-match-p "\\`feature .*  \\+1 ~1 \\?1 ↑1  made\n" (funcall heading made)))
              (should (string-match-p (concat "\\`detached " (git root "rev-parse" "--short" "main")
                                              " .*loose\n")
                                      (funcall heading detached)))
              (should-not (string-match-p "made\\|main\\|here" (substring (funcall heading detached) 20))))
          (kill-buffer (marker-buffer (oref (car rows) start))))))))

(ert-deftest ygg-git-worktree-status-row-keys ()
  (ygg-git-worktree-tests--with-repo (outer root)
    (git root "worktree" "add" "-q" (expand-file-name "other" outer) "-b" "other")
    (let ((row (cadr (ygg-git-worktree-tests--rows root))))
      (with-current-buffer (marker-buffer (oref row start))
        (unwind-protect
            (progn
              (goto-char (oref row start))
              (should (eq (key-binding (kbd "RET")) #'magit-worktree-status))
              (should (eq (key-binding "r") #'ygg-git-worktree-run))
              (should (eq (key-binding "x") #'ygg-git-worktree-remove))
              (should (eq (key-binding "=") #'ygg-git-worktree-compare))
              (should (eq (key-binding "s") #'ygg-git-worktree-space))
              (should (eq (key-binding "a") #'ygg-git-worktree-agent))
              (goto-char (point-min))
              (should (eq (key-binding "r") #'magit-rebase))
              (should-not (eq (key-binding "s") #'ygg-git-worktree-space))
              (should-not (eq (key-binding "=") #'ygg-git-worktree-compare)))
          (kill-buffer))))))

(defmacro ygg-git-worktree-tests--with-spaces (&rest body)
  "BODY with space functions stubbed; `closed' holds the spaces closed."
  (declare (indent 0))
  `(let ((closed nil))
     (cl-letf (((symbol-function 'ygg-space--for-dir) (lambda (dir) (list 'tab dir)))
               ((symbol-function 'ygg-space--id-of) #'cadr)
               ((symbol-function 'ygg-space--goto-id) #'ignore)
               ((symbol-function 'ygg-space-close) (lambda () (push t closed))))
       ,@body)))

(ert-deftest ygg-git-worktree-remove-keeps-space-when-git-refuses ()
  (ygg-git-worktree-tests--with-repo (outer root)
    (let ((locked (expand-file-name "locked" outer)))
      (git root "worktree" "add" "-q" locked "-b" "locked")
      (git root "worktree" "lock" locked)
      (ygg-git-worktree-tests--with-spaces
        (setq answers '(t))
        (ygg-git-worktree-tests--finish (ygg-git-worktree-remove locked))
        (should-not closed)
        (should (file-directory-p locked))))))

(ert-deftest ygg-git-worktree-remove-closes-space-once-gone ()
  (ygg-git-worktree-tests--with-repo (outer root)
    (let ((other (expand-file-name "other" outer)))
      (git root "worktree" "add" "-q" other "-b" "other")
      (ygg-git-worktree-tests--with-spaces
        (setq answers '(t))
        (ygg-git-worktree-tests--finish (ygg-git-worktree-remove other))
        (should closed)
        (should-not (file-directory-p other))))))

(defun ygg-git-worktree-tests--lock-and-lose (root outer name)
  "A locked worktree NAME beside ROOT, its directory deleted; its path."
  (let ((path (expand-file-name name outer)))
    (ygg-git-worktree-tests--git root "worktree" "add" "-q" path "-b" name)
    (ygg-git-worktree-tests--git root "worktree" "lock" path)
    (delete-directory path t)
    path))

(ert-deftest ygg-git-worktree-missing-locked-keeps-the-section ()
  (ygg-git-worktree-tests--with-repo (outer root)
    (let ((gone (ygg-git-worktree-tests--lock-and-lose root outer "gone")))
      (let* ((rows (ygg-git-worktree-tests--rows root))
             (heading (ygg-git-worktree-tests--heading (cadr rows))))
        (unwind-protect
            (progn
              (should (= (length rows) 2))
              (should (equal (directory-file-name (oref (cadr rows) value))
                             gone))
              (should (string-match-p "\\`gone .*  missing\n" heading))
              (should-not (string-match-p "[+~?][0-9]" heading)))
          (kill-buffer (marker-buffer (oref (car rows) start))))))))

(ert-deftest ygg-git-worktree-missing-locked-in-the-remove-picker ()
  (ygg-git-worktree-tests--with-repo (outer root)
    (let ((gone (ygg-git-worktree-tests--lock-and-lose root outer "gone")))
      (cl-letf (((symbol-function 'completing-read)
                 (lambda (_prompt table &rest _)
                   (let ((meta (cdr (funcall table "" nil 'metadata))))
                     (should (equal (substring-no-properties
                                     (funcall (alist-get 'annotation-function meta) gone))
                                    "  gone missing")))
                   gone)))
        (should (equal (ygg-git-worktree--read-removable) gone))))))

(ert-deftest ygg-git-worktree-remove-missing-locked ()
  (ygg-git-worktree-tests--with-repo (outer root)
    (let ((gone (ygg-git-worktree-tests--lock-and-lose root outer "gone")))
      (setq answers '(t))
      (ygg-git-worktree-tests--finish (ygg-git-worktree-remove gone))
      (should (= (length asked) 1))
      (should (string-match-p "missing" (car asked)))
      (should (equal (ygg-git-worktree-tests--list root)
                     (list (list (directory-file-name root) "main" nil)))))))

(defun ygg-git-worktree-tests--reset ()
  (clrhash ygg-git-worktree--cache)
  (clrhash ygg-git-worktree--commits)
  (clrhash ygg-git-worktree--inflight)
  (setq ygg-git-worktree--queue nil
        ygg-git-worktree--running 0))

(defun ygg-git-worktree-tests--add (root outer n)
  (dotimes (i n)
    (let ((dir (expand-file-name (format "w%d" i) outer)))
      (ygg-git-worktree-tests--git root "worktree" "add" "-q" "--detach" dir)
      (with-temp-file (expand-file-name (format "u%d.txt" i) dir) (insert "u\n")))))

(defun ygg-git-worktree-tests--drain ()
  (let ((deadline (+ (float-time) 20)))
    (while (and (< (float-time) deadline)
                (or ygg-git-worktree--queue
                    (> (hash-table-count ygg-git-worktree--inflight) 0)))
      (accept-process-output nil 0.05))
    (accept-process-output nil 0.05)))

(defun ygg-git-worktree-tests--render (root)
  (let ((default-directory root)
        (inhibit-read-only t)
        (magit--refresh-cache (list (cons 0 0))))
    (erase-buffer)
    (magit-insert-section (status)
      (ygg-git-worktree-insert-section))))

(defmacro ygg-git-worktree-tests--status (root &rest body)
  (declare (indent 1))
  `(with-temp-buffer
     (magit-status-mode)
     (setq default-directory ,root)
     (ygg-git-worktree-tests--reset)
     (let* ((spawned nil)
            (real-make-process (symbol-function 'make-process)))
       (cl-letf (((symbol-function 'make-process)
                  (lambda (&rest args)
                    (push default-directory spawned)
                    (apply real-make-process args))))
         ,@body))))

(ert-deftest ygg-git-worktree-section-runs-no-status-synchronously ()
  (ygg-git-worktree-tests--with-repo (outer root)
    (ygg-git-worktree-tests--add root outer 4)
    (ygg-git-worktree-tests--status root
      (let ((statuses 0)
            (real-process-file (symbol-function 'process-file)))
        (cl-letf (((symbol-function 'process-file)
                   (lambda (program &rest args)
                     (when (member "status" (nthcdr 3 args)) (cl-incf statuses))
                     (apply real-process-file program args))))
          (ygg-git-worktree-tests--render root))
        (should (= statuses 0))
        (should (= (length spawned) ygg-git-worktree-status-jobs))
        (should (= (cl-count ?… (buffer-string)) 5))
        (ygg-git-worktree-tests--drain)))))

(ert-deftest ygg-git-worktree-counts-land-in-the-live-buffer ()
  (ygg-git-worktree-tests--with-repo (outer root)
    (ygg-git-worktree-tests--add root outer 4)
    (ygg-git-worktree-tests--status root
      (ygg-git-worktree-tests--render root)
      (ygg-git-worktree-tests--drain)
      (should (= (length spawned) 5))
      (should (= (cl-count ?… (buffer-string)) 0))
      (let ((text (buffer-string)))
        (dotimes (i 4)
          (should (string-match-p (format "w%d  \\?1" i) (substring-no-properties text))))))))

(ert-deftest ygg-git-worktree-unchanged-refresh-spawns-nothing ()
  (ygg-git-worktree-tests--with-repo (outer root)
    (ygg-git-worktree-tests--add root outer 3)
    (ygg-git-worktree-tests--status root
      (ygg-git-worktree-tests--render root)
      (ygg-git-worktree-tests--drain)
      (let ((before (length spawned)) (shown (buffer-string)))
        (ygg-git-worktree-tests--render root)
        (ygg-git-worktree-tests--drain)
        (should (= (length spawned) before))
        (should (equal (substring-no-properties (buffer-string))
                       (substring-no-properties shown)))))))

(ert-deftest ygg-git-worktree-only-the-changed-worktree-recomputes ()
  (ygg-git-worktree-tests--with-repo (outer root)
    (ygg-git-worktree-tests--add root outer 3)
    (ygg-git-worktree-tests--status root
      (ygg-git-worktree-tests--render root)
      (ygg-git-worktree-tests--drain)
      (setq spawned nil)
      (let ((dir (expand-file-name "w1" outer)))
        (ygg-git-worktree-tests--git dir "add" "u1.txt")
        (ygg-git-worktree-tests--render root)
        (should (equal (mapcar #'directory-file-name spawned)
                       (list (directory-file-name dir))))
        (ygg-git-worktree-tests--drain)
        (should (string-match-p "w1  \\+1"
                                (substring-no-properties (buffer-string))))))))

(ert-deftest ygg-git-worktree-stale-counts-show-until-replaced ()
  (ygg-git-worktree-tests--with-repo (outer root)
    (ygg-git-worktree-tests--add root outer 2)
    (ygg-git-worktree-tests--status root
      (ygg-git-worktree-tests--render root)
      (ygg-git-worktree-tests--drain)
      (let ((ygg-git-worktree-status-ttl -1))
        (ygg-git-worktree-tests--render root)
        (should (= (cl-count ?… (buffer-string)) 0))
        (should (string-match-p "w0  \\?1" (substring-no-properties (buffer-string))))
        (ygg-git-worktree-tests--drain)))))

(ert-deftest ygg-git-worktree-dead-buffer-while-pending-is-harmless ()
  (ygg-git-worktree-tests--with-repo (outer root)
    (ygg-git-worktree-tests--add root outer 4)
    (let ((buf (generate-new-buffer " *wt-dead*")))
      (with-current-buffer buf
        (magit-status-mode)
        (setq default-directory root)
        (ygg-git-worktree-tests--reset)
        (ygg-git-worktree-tests--render root))
      (kill-buffer buf)
      (ygg-git-worktree-tests--drain)
      (should (zerop ygg-git-worktree--running))
      (should (= (hash-table-count ygg-git-worktree--cache) 5)))))

(ert-deftest ygg-git-worktree-request-during-a-job-reruns-with-the-newer-fingerprint ()
  (ygg-git-worktree-tests--with-repo (outer root)
    (ygg-git-worktree-tests--status root
      (let ((dir (directory-file-name root)))
        (ygg-git-worktree--request dir '("old"))
        (ygg-git-worktree--pump)
        (ygg-git-worktree--request dir '("new"))
        (ygg-git-worktree-tests--drain)
        (should (= (length spawned) 2))
        (should (equal (plist-get (gethash dir ygg-git-worktree--cache) :fp) '("new")))
        (should (zerop ygg-git-worktree--running))))))

(ert-deftest ygg-git-worktree-hung-status-times-out-and-frees-the-queue ()
  (ygg-git-worktree-tests--with-repo (outer root)
    (ygg-git-worktree-tests--add root outer 4)
    (let* ((real (executable-find "git"))
           (fake (expand-file-name "fake-git" outer))
           (magit-git-executable fake)
           (ygg-git-worktree-status-timeout 0.5)
           (ygg-git-worktree-status-jobs 2))
      (with-temp-file fake
        (insert (format "#!/bin/sh\ncase \"$*\" in *status*) exec sleep 30;; esac\nexec %s \"$@\"\n" real)))
      (set-file-modes fake #o755)
      (ygg-git-worktree-tests--status root
        (ygg-git-worktree-tests--render root)
        (should (= ygg-git-worktree--running 2))
        (ygg-git-worktree-tests--drain)
        (should (zerop ygg-git-worktree--running))
        (should (= (length spawned) 5))
        (should (= (hash-table-count ygg-git-worktree--inflight) 0))
        (should (cl-every (lambda (k)
                            (eq (plist-get (gethash k ygg-git-worktree--cache) :counts) :unknown))
                          (hash-table-keys ygg-git-worktree--cache)))
        (should (= (cl-count ?… (buffer-string)) 5))))))

(ert-deftest ygg-git-worktree-timeout-keeps-the-old-counts ()
  (ygg-git-worktree-tests--reset)
  (puthash "/w" (list :fp '(a) :counts '(1 0 0 nil nil) :at 0) ygg-git-worktree--cache)
  (puthash "/w" (cons '(b) '(b)) ygg-git-worktree--inflight)
  (ygg-git-worktree--abandon "/w")
  (should (equal (plist-get (gethash "/w" ygg-git-worktree--cache) :counts) '(1 0 0 nil nil)))
  (should (= (hash-table-count ygg-git-worktree--inflight) 0)))

(ert-deftest ygg-git-worktree-remote-uses-the-remote-git-and-skips-file-attributes ()
  (let ((magit-git-executable "/local/git")
        (magit-remote-git-executable "remote-git")
        (command nil)
        (handler nil))
    (ygg-git-worktree-tests--reset)
    (cl-letf (((symbol-function 'file-remote-p) (lambda (&rest _) "/ssh:h:"))
              ((symbol-function 'file-attributes) (lambda (&rest _) (error "sync stat")))
              ((symbol-function 'make-process)
               (lambda (&rest args)
                 (setq command (plist-get args :command)
                       handler (plist-get args :file-handler))
                 nil)))
      (should (equal (ygg-git-worktree--fingerprint "/ssh:h:/w" "abc") '("abc")))
      (ygg-git-worktree--spawn "/ssh:h:/w" '("abc"))
      (should (equal (car command) "remote-git"))
      (should handler))))

(ert-deftest ygg-git-worktree-unreachable-commit-blanks-only-itself ()
  (ygg-git-worktree-tests--with-repo (outer root)
    (ygg-git-worktree-tests--reset)
    (let ((good (ygg-git-worktree-tests--git root "rev-parse" "main"))
          (bad (make-string 40 ?d)))
      (ygg-git-worktree--load-commits (list good bad))
      (should (equal (cadr (gethash good ygg-git-worktree--commits)) "base"))
      (should (gethash bad ygg-git-worktree--commits))
      (let ((calls 0)
            (real (symbol-function 'magit-git-lines)))
        (cl-letf (((symbol-function 'magit-git-lines)
                   (lambda (&rest args) (cl-incf calls) (apply real args))))
          (ygg-git-worktree--load-commits (list good bad)))
        (should (zerop calls)))
      (should (string-match-p "detached .*" (ygg-git-worktree--head (list "/x" bad nil nil) "/y"))))))

(ert-deftest ygg-git-worktree-parse-list-records ()
  (let ((wts (ygg-git-worktree--parse-list
              '("worktree /r/main" "HEAD aaa" "branch refs/heads/main"
                "worktree /r/with space/wt" "HEAD bbb" "detached"
                "locked in use on usb"
                "worktree /r/gone" "HEAD ccc" "branch refs/heads/gone"
                "locked" "prunable gitdir file points to non-existent location"))))
    (should (equal wts '(("/r/main" "aaa" "main" nil nil nil nil)
                         ("/r/with space/wt" "bbb" nil nil t "in use on usb" nil)
                         ("/r/gone" "ccc" "gone" nil nil t
                          "gitdir file points to non-existent location"))))))

(ert-deftest ygg-git-worktree-parse-list-bare-falls-back ()
  (should-not (ygg-git-worktree--parse-list '("worktree /r/bare.git" "bare" "worktree /r/wt" "HEAD a" "detached"))))

(provide 'ygg-git-worktree-tests)
;;; ygg-git-worktree-tests.el ends here
