;;; ygg-git-compare-tests.el --- comparing two sides of a repository -*- lexical-binding: t; -*-

;;; Code:

(let ((builds (expand-file-name "../elpaca/builds/"
                                (file-name-directory
                                 (or load-file-name buffer-file-name)))))
  (dolist (p '("magit" "magit-section" "compat" "dash" "llama" "cond-let"
               "transient" "with-editor"))
    (add-to-list 'load-path (expand-file-name p builds)))
  (add-to-list 'load-path (expand-file-name "../../lisp/agent-objects" builds)))

(require 'ert)
(require 'cl-lib)
(require 'magit)
(require 'ygg-git-compare)
(require 'aob)
(require 'aob-acp)
(require 'ygg-preset)

(setq aob-acp-persist-file (make-temp-file "ygg-git-compare-sessions-" nil ".eld"))
(setq aob-acp-show-trace nil)

(defvar ygg-magit-diff-line-limit)

(defun ygg-git-compare-tests--git (dir &rest args)
  (let ((default-directory dir))
    (with-temp-buffer
      (unless (zerop (apply #'call-process "git" nil t nil args))
        (error "git %S failed: %s" args (buffer-string)))
      (string-trim (buffer-string)))))

(defun ygg-git-compare-tests--write (file text)
  (with-temp-file file (insert text)))

(defmacro ygg-git-compare-tests--with-repo (vars &rest body)
  "A repo on main with a feature branch checked out in a second worktree.
VARS binds (ROOT TREE): the main worktree and the feature one.  Feature
changes a.txt and adds b.txt in two commits; main then changes shared.txt."
  (declare (indent 1))
  (let ((root (nth 0 vars)) (tree (nth 1 vars)))
    `(let* ((process-environment
             (append '("GIT_CONFIG_GLOBAL=/dev/null" "GIT_CONFIG_NOSYSTEM=1")
                     process-environment))
            (outer (file-name-as-directory
                    (file-truename (make-temp-file "ygg-git-compare-" t))))
            (,root (file-name-as-directory (expand-file-name "main" outer)))
            (,tree (file-name-as-directory (expand-file-name "wt" outer)))
            (default-directory (progn (make-directory ,root) ,root))
            (magit-refresh-verbose nil))
       (unwind-protect
           (cl-flet ((git (&rest args) (apply #'ygg-git-compare-tests--git ,root args))
                     (commit (msg) (ygg-git-compare-tests--git ,root "add" ".")
                       (ygg-git-compare-tests--git ,root "commit" "-q" "-m" msg)))
             (git "init" "-q" "-b" "main")
             (git "config" "user.name" "Compare Test")
             (git "config" "user.email" "compare@example.invalid")
             (git "config" "commit.gpgsign" "false")
             (ygg-git-compare-tests--write (expand-file-name "a.txt" ,root) "1\n2\n3\n")
             (ygg-git-compare-tests--write (expand-file-name "shared.txt" ,root) "s\n")
             (commit "base")
             (git "branch" "feature")
             (git "worktree" "add" "-q" ,tree "feature")
             (ygg-git-compare-tests--write (expand-file-name "a.txt" ,tree) "1\ntwo\n3\n")
             (ygg-git-compare-tests--git ,tree "commit" "-q" "-am" "fix a")
             (ygg-git-compare-tests--write (expand-file-name "b.txt" ,tree) "b1\nb2\n")
             (ygg-git-compare-tests--git ,tree "add" "b.txt")
             (ygg-git-compare-tests--git ,tree "commit" "-q" "-m" "add b")
             (ygg-git-compare-tests--write (expand-file-name "shared.txt" ,root) "s\nmain\n")
             (commit "main moves")
             ,@body)
         (dolist (b (buffer-list))
           (when (and (with-current-buffer b (derived-mode-p 'magit-mode))
                      (file-in-directory-p (buffer-local-value 'default-directory b)
                                           outer))
             (kill-buffer b)))
         (delete-directory outer t)))))

(ert-deftest ygg-git-compare-resolves-branch-and-commit ()
  (ygg-git-compare-tests--with-repo (root _tree)
    (let ((feature (ygg-git-compare-tests--git root "rev-parse" "feature"))
          (short (ygg-git-compare-tests--git root "rev-parse" "--short" "main")))
      (let ((side (ygg-git-compare-resolve '(rev . "feature"))))
        (should (equal (plist-get side :diff) feature))
        (should (equal (plist-get side :log) feature))
        (should-not (plist-get side :uncommitted)))
      (should (equal (plist-get (ygg-git-compare-resolve (cons 'rev short)) :diff)
                     (ygg-git-compare-tests--git root "rev-parse" "main")))
      (should-error (ygg-git-compare-resolve '(rev . "no-such-branch"))
                    :type 'user-error))))

(ert-deftest ygg-git-compare-resolves-clean-worktree-to-head ()
  (ygg-git-compare-tests--with-repo (root tree)
    (let ((side (ygg-git-compare-resolve (cons 'worktree tree)))
          (head (ygg-git-compare-tests--git tree "rev-parse" "HEAD")))
      (should (equal (plist-get side :diff) head))
      (should (equal (plist-get side :log) head))
      (should-not (plist-get side :uncommitted))
      (should (string-match-p "\\`wt \\[feature\\]" (plist-get side :label)))
      (ignore root))))

(defun ygg-git-compare-tests--index-hash (dir)
  (with-temp-buffer
    (set-buffer-multibyte nil)
    (insert-file-contents-literally
     (expand-file-name (ygg-git-compare-tests--git dir "rev-parse" "--git-path" "index")
                       dir))
    (secure-hash 'sha1 (current-buffer))))

(defun ygg-git-compare-tests--loose-objects (dir)
  (let ((counts (ygg-git-compare-tests--git dir "count-objects" "-v")))
    (string-match "^count: \\([0-9]+\\)" counts)
    (match-string 1 counts)))

(defun ygg-git-compare-tests--state (root tree)
  "What a compare must leave as it found it: objects, indexes, stash, refs, status."
  (list (ygg-git-compare-tests--loose-objects root)
        (ygg-git-compare-tests--index-hash root)
        (ygg-git-compare-tests--index-hash tree)
        (ygg-git-compare-tests--git root "stash" "list")
        (ygg-git-compare-tests--git root "for-each-ref")
        (ygg-git-compare-tests--git root "--no-optional-locks" "status" "--porcelain")
        (ygg-git-compare-tests--git tree "--no-optional-locks" "status" "--porcelain")))

(defun ygg-git-compare-tests--right-pane (list file)
  "FILE's diff as LIST's right pane shows it."
  (with-current-buffer list
    (let ((ygg-git-compare--file-window (selected-window)))
      (with-current-buffer (ygg-git-compare--show-file file)
        (list magit-buffer-diff-args (buffer-string))))))

(ert-deftest ygg-git-compare-diffs-dirty-worktree-in-place ()
  (ygg-git-compare-tests--with-repo (root tree)
    (ygg-git-compare-tests--write (expand-file-name ".gitignore" tree) "*.log\n")
    (ygg-git-compare-tests--git tree "add" ".gitignore")
    (ygg-git-compare-tests--git tree "commit" "-q" "-m" "ignore logs")
    (ygg-git-compare-tests--write (expand-file-name "a.txt" tree) "1\ntwo\n3\ndirty\n")
    (ygg-git-compare-tests--write (expand-file-name "b.txt" tree) "b1\nb2\nstaged\n")
    (ygg-git-compare-tests--git tree "add" "b.txt")
    (ygg-git-compare-tests--write (expand-file-name "b.txt" tree) "b1\nb2\nstaged\nmore\n")
    (ygg-git-compare-tests--write (expand-file-name "u.txt" tree) "untracked\n")
    (ygg-git-compare-tests--write (expand-file-name "x.log" tree) "ignored\n")
    (ygg-git-compare-tests--write (expand-file-name "big.txt" tree)
                                  (concat (make-string 300 ?z) "\n"))
    (ygg-git-compare-tests--write (expand-file-name "bin.dat" tree) "b\0in")
    (ygg-git-compare-tests--write (expand-file-name "shared.txt" tree) "s\n")
    (set-file-times (expand-file-name "shared.txt" tree) (time-subtract nil 3600))
    (ygg-git-compare-tests--write (expand-file-name "shared.txt" root) "s\nmain\nloose\n")
    (let* ((ygg-git-compare-untracked-max-size 100)
           (main (ygg-git-compare-tests--git root "rev-parse" "main"))
           (head (ygg-git-compare-tests--git tree "rev-parse" "HEAD"))
           (base (ygg-git-compare-tests--git root "merge-base" "main" "feature"))
           (before (ygg-git-compare-tests--state root tree))
           (side (ygg-git-compare-resolve (cons 'worktree tree))))
      (should (plist-get side :uncommitted))
      (should (equal (plist-get side :diff) head))
      (should (equal (plist-get side :log) head))
      (should (equal (plist-get side :dir) tree))
      (with-current-buffer (ygg-git-compare-buffer root '(rev . "main")
                                                   (cons 'worktree tree))
        (should (equal default-directory tree))
        (should (equal magit-buffer-diff-range base))
        (should (equal (ygg-git-compare-tests--files-shown)
                       '(".gitignore" "a.txt" "b.txt" "big.txt" "bin.dat" "u.txt")))
        (should (string-match-p "B: wt \\[feature\\] \\+ uncommitted (incl\\. untracked)"
                                (format "%s" header-line-format)))
        (let ((text (buffer-string)))
          (should (string-match-p "^\\+dirty" text))
          (should (string-match-p "^\\+more" text))
          (should-not (string-search "x.log" text))
          (should-not (string-search "zzz" text)))
        (pcase-let ((`(,_ ,text) (ygg-git-compare-tests--right-pane (current-buffer) "u.txt")))
          (should (string-match-p "^\\+untracked" text)))
        (pcase-let ((`(,_ ,text) (ygg-git-compare-tests--right-pane (current-buffer) "a.txt")))
          (should (string-match-p "^\\+dirty" text)))
        (pcase-let ((`(,_ ,text) (ygg-git-compare-tests--right-pane (current-buffer)
                                                                    "bin.dat")))
          (should (string-search "bin.dat" text))
          (should-not (string-search "\0" text)))
        (pcase-let ((`(,args ,text) (ygg-git-compare-tests--right-pane (current-buffer)
                                                                       "big.txt")))
          (should (member "--no-patch" args))
          (should (string-search "big.txt" text))
          (should-not (string-search "zzz" text)))
        (let ((prompt (ygg-git-compare-review-prompt)))
          (should (string-search "fix a" prompt))
          (should-not (string-search "main moves" prompt))
          (should (string-match-p "^\\+dirty" prompt))
          (should (string-match-p "^\\+staged" prompt))
          (should (string-match-p "^\\+more" prompt))
          (should (string-match-p "^\\+untracked" prompt))
          (should (string-search "untracked big.txt: 301 bytes, left out" prompt))
          (should-not (string-search "zzz" prompt))
          (should (string-search "Binary files /dev/null and b/bin.dat differ" prompt))
          (should-not (string-search "\0" prompt))
          (should-not (string-search "ignored" prompt)))
        (ygg-git-compare-toggle-dots)
        (should (equal magit-buffer-diff-range main))
        (should (member "shared.txt" (ygg-git-compare-tests--files-shown)))
        (should (string-match-p "^-main" (buffer-string))))
      (with-current-buffer (ygg-git-compare-buffer root (cons 'worktree tree)
                                                   '(rev . "main"))
        (should (equal magit-buffer-diff-range (concat head "..." main)))
        (should (string-match-p "A: wt \\[feature\\] (uncommitted not shown)"
                                (format "%s" header-line-format)))
        (should-not (member "u.txt" (ygg-git-compare-tests--files-shown)))
        (ygg-git-compare-toggle-dots)
        (should (equal default-directory tree))
        (should (equal magit-buffer-diff-range main))
        (should (member "-R" magit-buffer-diff-args))
        (should (string-match-p "A: wt \\[feature\\] \\+ uncommitted"
                                (format "%s" header-line-format)))
        (should (string-match-p "^-dirty" (buffer-string)))
        (should (string-match-p "^\\+main" (buffer-string)))
        (pcase-let ((`(,_ ,text) (ygg-git-compare-tests--right-pane (current-buffer) "u.txt")))
          (should (string-match-p "^-untracked" text)))
        (pcase-let ((`(,_ ,text) (ygg-git-compare-tests--right-pane (current-buffer) "a.txt")))
          (should (string-match-p "^-dirty" text)))
        (let ((prompt (ygg-git-compare-review-prompt)))
          (should (string-match-p "^-dirty" prompt))
          (should (string-match-p "^-untracked" prompt))))
      (with-current-buffer (ygg-git-compare-buffer root (cons 'worktree root)
                                                   (cons 'worktree tree))
        (should (equal default-directory tree))
        (should (string-match-p (concat "A: main \\[main\\] (uncommitted not shown)"
                                        " ↔ B: wt \\[feature\\] \\+ uncommitted")
                                (format "%s" header-line-format)))
        (should-not (string-search "loose" (buffer-string))))
      (should (equal (ygg-git-compare-tests--state root tree) before)))))

(ert-deftest ygg-git-compare-shows-this-worktree-against-its-head ()
  (ygg-git-compare-tests--with-repo (root _tree)
    (should (equal (ygg-git-compare-default-a (ygg-git-compare--here-spec))
                   '(rev . "main")))
    (ygg-git-compare-tests--write (expand-file-name "shared.txt" root) "s\nunstaged\n")
    (ygg-git-compare-tests--write (expand-file-name "new.txt" root) "new\n")
    (let ((b (ygg-git-compare--here-spec)))
      (should (equal (ygg-git-compare-default-a b) '(rev . "HEAD")))
      (should (equal (ygg-git-compare-default-a
                      (seq-find (lambda (spec) (and (eq (car spec) 'worktree)
                                                    (file-equal-p (cdr spec) root)))
                                (mapcar #'cdr (ygg-git-compare-candidates))))
                     '(rev . "HEAD")))
      (with-current-buffer (ygg-git-compare-buffer root '(rev . "HEAD") b)
        (should (equal (ygg-git-compare-tests--files-shown) '("shared.txt" "new.txt")))
        (should (string-match-p "A: HEAD ↔ B: main \\[main\\] \\+ uncommitted"
                                (format "%s" header-line-format)))))))

(defun ygg-git-compare-tests--files-shown ()
  "The files whose diff sections this magit diff buffer holds, in order."
  (let (files)
    (magit-map-sections (lambda (s) (when (and (eq (oref s type) 'file)
                                               (not (eq (oref (oref s parent) type)
                                                        'diffstat)))
                                      (push (oref s value) files))))
    (nreverse files)))

(ert-deftest ygg-git-compare-opens-magit-diff-of-the-range ()
  (ygg-git-compare-tests--with-repo (root tree)
    (ygg-git-compare-tests--write (expand-file-name "a.txt" tree) "1\ntwo\n3\ndirty\n")
    (let* ((start-buffer (window-buffer))
           (main (ygg-git-compare-tests--git root "rev-parse" "main"))
           (base (ygg-git-compare-tests--git root "merge-base" "main" "feature"))
           (list (ygg-git-compare-open '(rev . "main") (cons 'worktree tree))))
      (should (= (length (window-list)) 2))
      (should (eq (window-buffer) list))
      (should (< (abs (- (window-total-width) (round (* 0.38 (frame-width))))) 3))
      (with-current-buffer list
        (should (derived-mode-p 'magit-diff-mode))
        (should magit-buffer-locked-p)
        (should ygg-git-compare-mode)
        (should (equal magit-buffer-diff-range base))
        (should (equal (ygg-git-compare--range)
                       (concat main "..." (abbreviate-file-name tree))))
        (should (member "--stat" magit-buffer-diff-args))
        (should (equal (ygg-git-compare-tests--files-shown) '("a.txt" "b.txt")))
        (should (string-match-p
                 "A: main ↔ B: wt \\[feature\\] \\+ uncommitted (incl\\. untracked)"
                 (format "%s" header-line-format)))
        (should (equal (magit-file-at-point) "a.txt"))
        (let ((prompt (ygg-git-compare-review-prompt)))
          (should (string-match-p "fix a" prompt))
          (should (string-match-p "\\+b1" prompt))
          (should (string-match-p "\\+dirty" prompt))
          (should-not (string-match-p "main moves" prompt))
          (should-not (string-search "<review-comments>" prompt))))
      (with-current-buffer (window-buffer (next-window))
        (should (derived-mode-p 'magit-diff-mode))
        (should (equal magit-buffer-diff-files '("a.txt")))
        (should (string-match-p "^\\+dirty" (buffer-string))))
      (with-current-buffer list
        (magit-section-forward)
        (should (equal (magit-file-at-point) "b.txt"))
        (ygg-git-compare--follow list)
        (with-current-buffer (window-buffer (next-window))
          (should (equal magit-buffer-diff-files '("b.txt")))))
      (with-current-buffer list
        (ygg-git-compare-swap)
        (should (string-match-p "A: wt \\[feature\\] (uncommitted not shown) ↔ B: main "
                                (format "%s" header-line-format)))
        (ygg-git-compare-quit))
      (should-not (buffer-live-p list))
      (should-not (seq-find (lambda (b) (string-prefix-p "magit-diff: compare"
                                                        (buffer-name b)))
                            (buffer-list)))
      (should (= (length (window-list)) 1))
      (should (eq (window-buffer) start-buffer)))))

(ert-deftest ygg-git-compare-swaps-and-toggles-dots ()
  (ygg-git-compare-tests--with-repo (root _tree)
    (let ((main (ygg-git-compare-tests--git root "rev-parse" "main"))
          (feature (ygg-git-compare-tests--git root "rev-parse" "feature")))
      (with-current-buffer (ygg-git-compare-buffer root '(rev . "main")
                                                   '(rev . "feature"))
        (should (equal magit-buffer-diff-range (concat main "..." feature)))
        (ygg-git-compare-toggle-dots)
        (should (equal magit-buffer-diff-range (concat main ".." feature)))
        (should (equal (ygg-git-compare-tests--files-shown)
                       '("a.txt" "b.txt" "shared.txt")))
        (ygg-git-compare-swap)
        (should (equal magit-buffer-diff-range (concat feature ".." main)))
        (should (string-match-p "A: feature ↔ B: main" (format "%s" header-line-format)))
        (ygg-git-compare-toggle-dots)
        (should (equal (ygg-git-compare-tests--files-shown) '("shared.txt")))))))

(ert-deftest ygg-git-compare-switches-base ()
  (ygg-git-compare-tests--with-repo (root _tree)
    (let ((main (ygg-git-compare-tests--git root "rev-parse" "main"))
          (feature (ygg-git-compare-tests--git root "rev-parse" "feature")))
      (with-current-buffer (ygg-git-compare-buffer root '(rev . "feature")
                                                   '(rev . "main"))
        (cl-letf (((symbol-function 'ygg-git-compare-candidates) (lambda (&rest _) nil))
                  ((symbol-function 'ygg-git-compare--read)
                   (lambda (&rest _) '(rev . "main~1"))))
          (ygg-git-compare-switch-base))
        (should (equal ygg-git-compare--a-spec '(rev . "main~1")))
        (should (equal ygg-git-compare--b-spec '(rev . "main")))
        (should-not (string-search feature magit-buffer-diff-range))
        (should (string-suffix-p (concat "..." main) magit-buffer-diff-range))))))

(ert-deftest ygg-git-compare-refresh-diffs-the-worktree-anew ()
  (ygg-git-compare-tests--with-repo (root tree)
    (with-current-buffer (ygg-git-compare-buffer root '(rev . "main")
                                                 (cons 'worktree tree))
      (should-not (plist-get ygg-git-compare--b :uncommitted))
      (ygg-git-compare-tests--write (expand-file-name "c.txt" tree) "new\n")
      (ygg-git-compare-tests--git tree "add" "c.txt")
      (call-interactively (keymap-lookup ygg-git-compare-mode-map
                                         "<remap> <magit-refresh>"))
      (should (plist-get ygg-git-compare--b :uncommitted))
      (should (member "c.txt" (ygg-git-compare-tests--files-shown)))
      (should (equal (ygg-git-compare-tests--git tree "stash" "list") "")))))

(ert-deftest ygg-git-compare-refresh-keeps-a-revision-where-it-was-read ()
  (ygg-git-compare-tests--with-repo (root tree)
    (ygg-git-compare-tests--write (expand-file-name "a.txt" tree) "1\ntwo\n3\ndirty\n")
    (with-current-buffer (ygg-git-compare-buffer root '(rev . "HEAD") (cons 'worktree tree))
      (should (equal default-directory tree))
      (ygg-git-compare-refresh)
      (should (equal (plist-get ygg-git-compare--a :diff)
                     (ygg-git-compare-tests--git root "rev-parse" "HEAD"))))))

(ert-deftest ygg-git-compare-log-shows-each-side ()
  (ygg-git-compare-tests--with-repo (root _tree)
    (with-current-buffer (ygg-git-compare-buffer root '(rev . "main")
                                                 '(rev . "feature"))
      (let ((list (current-buffer)))
        (ygg-git-compare-log)
        (let ((log (seq-find (lambda (b) (eq (buffer-local-value
                                              'ygg-git-compare--list-buffer b)
                                             list))
                             (buffer-list))))
          (with-current-buffer log
            (should (derived-mode-p 'magit-log-mode))
            (should (member "--left-right" magit-buffer-log-args))
            (should (string-match-p "main moves" (buffer-string)))
            (should (string-match-p "add b" (buffer-string)))
            (should (string-match-p "fix a" (buffer-string)))))))))

(ert-deftest ygg-git-compare-leaves-patch-out-of-huge-ranges ()
  (ygg-git-compare-tests--with-repo (root tree)
    (let ((ygg-magit-diff-line-limit 1))
      (with-current-buffer (ygg-git-compare-buffer root '(rev . "main")
                                                   (cons 'worktree tree))
        (should (member "--no-patch" magit-buffer-diff-args))
        (should (equal (ygg-git-compare-tests--files-shown) nil))
        (should (equal (magit-file-at-point) "a.txt"))
        (let ((ygg-git-compare--file-window (selected-window)))
          (with-current-buffer (ygg-git-compare--show-file "b.txt")
            (should (equal magit-buffer-diff-files '("b.txt")))
            (should-not (member "--no-patch" magit-buffer-diff-args))
            (should (string-match-p "^\\+b1" (buffer-string)))))
        (let ((ygg-magit-diff-line-limit 2000)
              (magit-direct-use-buffer-arguments 'selected))
          (ygg-git-compare-toggle-dots)
          (should-not (member "--no-patch" magit-buffer-diff-args))
          (should (equal (ygg-git-compare-tests--files-shown)
                         '("a.txt" "b.txt" "shared.txt"))))))))

(ert-deftest ygg-git-compare-diffs-unrelated-histories-directly ()
  (ygg-git-compare-tests--with-repo (root _tree)
    (ygg-git-compare-tests--git root "checkout" "-q" "--orphan" "pages")
    (ygg-git-compare-tests--git root "rm" "-rq" "--cached" ".")
    (ygg-git-compare-tests--write (expand-file-name "index.html" root) "<p>\n")
    (ygg-git-compare-tests--git root "add" "index.html")
    (ygg-git-compare-tests--git root "commit" "-q" "-m" "pages")
    (with-current-buffer (ygg-git-compare-buffer root '(rev . "main") '(rev . "pages"))
      (should (equal ygg-git-compare--dots ".."))
      (should (member "index.html" (ygg-git-compare-tests--files-shown))))))

(ert-deftest ygg-git-compare-from-a-compare-keeps-the-first-layout ()
  (ygg-git-compare-tests--with-repo (_root tree)
    (let* ((start-buffer (window-buffer))
           (first (ygg-git-compare-open '(rev . "main") (cons 'worktree tree)))
           (second (with-current-buffer first
                     (ygg-git-compare-open '(rev . "feature") '(rev . "main")))))
      (should-not (buffer-live-p first))
      (with-current-buffer second (ygg-git-compare-quit))
      (should (= (length (window-list)) 1))
      (should (eq (window-buffer) start-buffer)))))

(ert-deftest ygg-git-compare-pull-request-fetched-without-branch ()
  (ygg-git-compare-tests--with-repo (root _tree)
    (let ((remote (expand-file-name "../remote.git" root))
          (feature (ygg-git-compare-tests--git root "rev-parse" "feature")))
      (ygg-git-compare-tests--git root "init" "-q" "--bare" remote)
      (ygg-git-compare-tests--git root "remote" "add" "origin" remote)
      (ygg-git-compare-tests--git root "push" "-q" "origin" "main" "feature:refs/pull/7/head")
      (ygg-git-compare-tests--git root "fetch" "-q" "origin")
      (let ((branches (ygg-git-compare-tests--git root "branch" "-a"))
            (gh-calls 0))
        (cl-letf (((symbol-function 'ygg-git-compare--gh-repo-url) #'ignore)
                  ((symbol-function 'ygg-git-compare--gh-pulls)
                   (lambda ()
                     (cl-incf gh-calls)
                     '((:number 7 :title "Feature work" :headRefName "feature"
                                :baseRefName "main")))))
          (should-not (rassq 'pr (mapcar (lambda (c) (cons (car c) (cadr c)))
                                         (ygg-git-compare-candidates))))
          (should (= gh-calls 0))
          (let* ((cands (ygg-git-compare-candidates t))
                 (pr (seq-find (lambda (c) (eq (cadr c) 'pr)) cands))
                 (spec (cdr pr)))
            (should (= gh-calls 1))
            (should (equal (car pr) "#7 Feature work"))
            (should (equal (get-text-property 0 'ygg-git-compare-group (car pr))
                           "Pull requests"))
            (should (equal (ygg-git-compare-default-a spec) '(rev . "origin/main")))
            (let ((prepared (ygg-git-compare--prepare spec)))
              (should (equal (plist-get (cdr prepared) :sha) feature))
              (let ((side (ygg-git-compare-resolve prepared)))
                (should (equal (plist-get side :diff) feature))
                (should (string-prefix-p "#7" (plist-get side :label)))))))
        (should (equal (ygg-git-compare-tests--git root "branch" "-a") branches))
        (should (equal (ygg-git-compare-tests--git root "for-each-ref" "refs/pull") ""))
        (should (equal (ygg-git-compare-tests--git root "stash" "list") ""))))))

(ert-deftest ygg-git-compare-defaults-a-to-default-branch ()
  (ygg-git-compare-tests--with-repo (root tree)
    (should (equal (ygg-git-compare-default-a (cons 'worktree tree)) '(rev . "main")))
    (should (equal (ygg-git-compare--here-spec) (cons 'worktree root)))))

(ert-deftest ygg-git-compare-side-picker-groups-and-notes ()
  (let* ((cands (list (cons (ygg-git-compare--group "main" "Branches") '(rev . "main"))
                      (cons (ygg-git-compare--group "wt [x]" "Worktrees" "~/wt") '(worktree . "/wt/"))))
         meta)
    (cl-letf (((symbol-function 'completing-read)
               (lambda (_p table &rest _)
                 (setq meta (cdr (funcall table "" nil 'metadata)))
                 "wt [x]")))
      (should (equal (ygg-git-compare--read "Compare" cands '(rev . "main"))
                     '(worktree . "/wt/"))))
    (should (eq (alist-get 'category meta) 'ygg-review-side))
    (should (equal (funcall (alist-get 'group-function meta) (car (nth 1 cands)) nil)
                   "Worktrees"))
    (should (equal (substring-no-properties
                    (funcall (alist-get 'annotation-function meta) (car (nth 1 cands))))
                   "  ~/wt"))))

;;; Review

(defmacro ygg-git-compare-tests--with-sessions (specs &rest body)
  "Register sessions from SPECS, each (ID DIR), around BODY."
  (declare (indent 1))
  `(let ((aob--sessions (make-hash-table :test #'equal))
         (aob--order nil))
     (dolist (spec ,specs)
       (aob-create-session :id (car spec) :backend 'acp :name (car spec)
                           :project (cadr spec) :state 'idle))
     ,@body))

(defun ygg-git-compare-tests--goto (text)
  (goto-char (point-min))
  (search-forward text)
  (beginning-of-line))

(defun ygg-git-compare-tests--comment (text)
  "Comment TEXT on the diff line at point, written in the comment buffer."
  (with-current-buffer (ygg-git-compare-comment)
    (insert text)
    (ygg-git-compare-draft-save)))

(defmacro ygg-git-compare-tests--with-compare (root &rest body)
  "BODY in a compare of main against feature, every hunk shown."
  (declare (indent 1))
  `(with-current-buffer (ygg-git-compare-buffer ,root '(rev . "main") '(rev . "feature"))
     (magit-section-show-level-4-all)
     ,@body))

(ert-deftest ygg-git-compare-review-keys-in-both-panes ()
  (ygg-git-compare-tests--with-repo (root _tree)
    (ygg-git-compare-tests--with-compare root
      (let ((list (current-buffer)))
        (ygg-git-compare-tests--goto "+two")
        (should (eq (key-binding "c" nil nil (point)) #'ygg-git-compare-comment))
        (should (eq (key-binding "C" nil nil (point)) #'ygg-git-compare-comment-file))
        (should (eq (key-binding ";") #'ygg-git-compare-dispatch))
        (should (eq (key-binding "@") #'ygg-git-compare-review))
        (let ((ygg-git-compare--file-window (selected-window)))
          (with-current-buffer (ygg-git-compare--show-file "a.txt")
            (ygg-git-compare-tests--goto "+two")
            (should (eq (key-binding "c" nil nil (point)) #'ygg-git-compare-comment))
            (should (eq (key-binding "C" nil nil (point)) #'ygg-git-compare-comment-file))
            (ygg-git-compare-tests--comment "from the file pane")
            (should-not ygg-git-compare--comments)))
        (should (equal (plist-get (car (buffer-local-value 'ygg-git-compare--comments list))
                                  :text)
                       "from the file pane"))))
    (ygg-git-compare-tests--write (expand-file-name "shared.txt" root) "s\nmain\nloose\n")
    (with-current-buffer (magit-status-setup-buffer root)
      (magit-section-show-level-4-all)
      (ygg-git-compare-tests--goto "+loose")
      (should (eq (key-binding "C" nil nil (point)) #'magit-commit-add-log)))))

(ert-deftest ygg-git-compare-comment-anchors-each-side ()
  (ygg-git-compare-tests--with-repo (root _tree)
    (ygg-git-compare-tests--with-compare root
      (ygg-git-compare-tests--goto "+two")
      (ygg-git-compare-tests--comment "  name it better  ")
      (ygg-git-compare-tests--goto "-2")
      (ygg-git-compare-tests--comment "keep this")
      (pcase-let ((`(,old ,new) ygg-git-compare--comments))
        (should (equal (plist-get new :text) "name it better"))
        (should (equal (plist-get new :file) "a.txt"))
        (should (equal (plist-get new :line) 2))
        (should (eq (plist-get new :side) 'new))
        (should (string-search "+two" (plist-get new :quote)))
        (should (string-search " 1" (plist-get new :quote)))
        (should (eq (plist-get old :side) 'old))
        (should (equal (plist-get old :line) 2)))
      (ygg-git-compare-tests--goto "a.txt")
      (ygg-git-compare-tests--comment "on the whole file")
      (should (eq (plist-get (car ygg-git-compare--comments) :level) 'file))
      (should (equal (plist-get (car ygg-git-compare--comments) :file) "a.txt"))
      (ygg-git-compare-tests--goto "@@")
      (ygg-git-compare-tests--comment "on the hunk")
      (should (eq (plist-get (car ygg-git-compare--comments) :level) 'range))
      (ygg-git-compare-tests--goto "+b1")
      (should-error (ygg-git-compare-tests--comment " ") :type 'user-error)
      (should (= (length ygg-git-compare--comments) 4)))))

(defun ygg-git-compare-tests--place (comment)
  (mapcar (lambda (key) (plist-get comment key))
          '(:level :start-side :start-line :side :line)))

(ert-deftest ygg-git-compare-comment-on-a-hunk-spans-its-changed-lines ()
  (ygg-git-compare-tests--with-repo (root _tree)
    (ygg-git-compare-tests--with-compare root
      (ygg-git-compare-tests--goto "@@ -0,0")
      (ygg-git-compare-tests--comment "added only")
      (ygg-git-compare-tests--goto "@@ -1,3")
      (ygg-git-compare-tests--comment "mixed")
      (ygg-git-compare-tests--goto "@@ -1,3")
      (forward-line)
      (with-current-buffer (ygg-git-compare-comment-hunk)
        (insert "from inside")
        (ygg-git-compare-draft-save))
      (pcase-let ((`(,inside ,mixed ,added) ygg-git-compare--comments))
        (should (equal (ygg-git-compare-tests--place added) '(range new 1 new 2)))
        (should (string-search "+b1" (plist-get added :quote)))
        (should (string-search "+b2" (plist-get added :quote)))
        (should (equal (ygg-git-compare-tests--place mixed) '(range old 2 new 2)))
        (should (string-search "-2" (plist-get mixed :quote)))
        (should (string-search "+two" (plist-get mixed :quote)))
        (should (equal (plist-get mixed :file) "a.txt"))
        (should (equal (ygg-git-compare-tests--place inside) '(range old 2 new 2)))))))

(ert-deftest ygg-git-compare-comment-on-a-hunk-of-removed-lines ()
  (ygg-git-compare-tests--with-repo (root _tree)
    (ygg-git-compare-tests--with-compare root
      (ygg-git-compare-swap)
      (ygg-git-compare-toggle-dots)
      (magit-section-show-level-4-all)
      (ygg-git-compare-tests--goto "@@ -1,2")
      (ygg-git-compare-tests--comment "removed only")
      (should (equal (ygg-git-compare-tests--place (car ygg-git-compare--comments))
                     '(range old 1 old 2))))))

(ert-deftest ygg-git-compare-comment-on-a-hunk-in-the-right-pane ()
  (ygg-git-compare-tests--with-repo (root _tree)
    (ygg-git-compare-tests--with-compare root
      (let ((list (current-buffer))
            (ygg-git-compare--file-window (selected-window)))
        (with-current-buffer (ygg-git-compare--show-file "b.txt")
          (ygg-git-compare-tests--goto "@@")
          (ygg-git-compare-tests--comment "right pane"))
        (should (equal (ygg-git-compare-tests--place
                        (car (buffer-local-value 'ygg-git-compare--comments list)))
                       '(range new 1 new 2)))))))

(ert-deftest ygg-git-compare-comments-edit-and-drop ()
  (ygg-git-compare-tests--with-repo (root _tree)
    (ygg-git-compare-tests--with-compare root
      (ygg-git-compare-tests--goto "+two")
      (ygg-git-compare-tests--comment "first")
      (ygg-git-compare-tests--goto "+b2")
      (ygg-git-compare-tests--comment "second")
      (cl-letf (((symbol-function 'y-or-n-p) (lambda (&rest _) t)))
        (ygg-git-compare-tests--goto "+two")
        (ygg-git-compare-comment-delete)
        (ygg-git-compare-tests--goto "+b2")
        (with-current-buffer (ygg-git-compare-comment-edit)
          (should (bobp))
          (erase-buffer)
          (insert "rewritten")
          (ygg-git-compare-draft-save))
        (should (equal (mapcar (lambda (c) (plist-get c :text)) ygg-git-compare--comments)
                       '("rewritten")))
        (ygg-git-compare-comment-delete)
        (should-error (ygg-git-compare-comment-delete) :type 'user-error)))))

(ert-deftest ygg-git-compare-review-sends-comments-and-range-once ()
  (ygg-git-compare-tests--with-repo (root _tree)
    (ygg-git-compare-tests--with-sessions (list (list "here" root))
      (let ((aob-acp-agents '(("claude" :command ("x"))))
            sent shown offered meta)
        (ygg-git-compare-tests--with-compare root
          (ygg-git-compare-tests--goto "+two")
          (ygg-git-compare-tests--comment "why two")
          (ygg-git-compare-tests--goto "-2")
          (ygg-git-compare-tests--comment "keep the digit")
          (cl-letf (((symbol-function 'completing-read)
                     (lambda (_p table &rest _)
                       (setq offered (all-completions "" table)
                             meta (cdr (funcall table "" nil 'metadata)))
                       (car (all-completions "here" table))))
                    ((symbol-function 'aob-prompt)
                     (lambda (s text &rest _) (push (list s text aob-prompt-typed) sent)))
                    ((symbol-function 'aob-trace) (lambda (s) (push s shown))))
            (ygg-git-compare-review))
          (should-not ygg-git-compare--comments))
        (should (equal (car offered) "new: review plan (preset review)"))
        (should (equal (nth 1 offered) "here"))
        (should (eq (alist-get 'category meta) 'ygg-review-reviewer))
        (should (equal (funcall (alist-get 'group-function meta) (nth 1 offered) nil)
                       "Live sessions"))
        (should (string-prefix-p "  idle · "
                                 (funcall (alist-get 'annotation-function meta)
                                          (nth 1 offered))))
        (should (equal (nth 2 offered) "new: claude"))
        (should (= (length sent) 1))
        (pcase-let ((`(,s ,m ,typed) (car sent)))
          (should (equal (aob-session-name s) "here"))
          (should typed)
          (should (equal shown (list s)))
          (should (string-prefix-p ygg-git-compare-review-instructions m))
          (should (< (string-search "a.txt:2\n> " m)
                     (string-search "why two" m)
                     (string-search "a.txt:2 (removed line)" m)
                     (string-search "keep the digit" m)
                     (string-search "<compare>" m)))
          (should (string-search "> +two" m))
          (should (string-search (concat "A: main ↔ B: feature  "
                                         (ygg-git-compare-tests--git root "rev-parse" "main")
                                         "..."
                                         (ygg-git-compare-tests--git root "rev-parse" "feature"))
                                 m))
          (should-not (string-search "made on" m))
          (should (string-search "add b" m))
          (should (string-search "+b1" m))
          (should-not (string-search "main moves" m)))))))

(ert-deftest ygg-git-compare-review-comment-keeps-the-range-it-was-made-on ()
  (ygg-git-compare-tests--with-repo (root _tree)
    (let ((main (ygg-git-compare-tests--git root "rev-parse" "main"))
          (feature (ygg-git-compare-tests--git root "rev-parse" "feature")))
      (ygg-git-compare-tests--with-compare root
        (ygg-git-compare-tests--goto "+two")
        (ygg-git-compare-tests--comment "before the swap")
        (ygg-git-compare-swap)
        (let ((m (ygg-git-compare-review-prompt)))
          (should (string-search (format "a.txt:2 · made on A: main ↔ B: feature  %s...%s\n"
                                         main feature)
                                 m))
          (should (string-search (format "\nA: feature ↔ B: main  %s...%s\n" feature main)
                                 m)))))))

(ert-deftest ygg-git-compare-review-new-agent-starts-in-root ()
  (ygg-git-compare-tests--with-repo (root _tree)
    (ygg-git-compare-tests--with-sessions nil
      (let ((aob-acp-agents '(("claude" :command ("x"))))
            spawned sent)
        (ygg-git-compare-tests--with-compare root
          (cl-letf (((symbol-function 'completing-read) (lambda (&rest _) "new: claude"))
                    ((symbol-function 'aob-acp-spawn)
                     (lambda (agent &rest _)
                       (push (list agent aob-acp-start-dir) spawned)
                       (aob-create-session :id "fresh" :backend 'acp :name "fresh"
                                           :project aob-acp-start-dir :state 'starting)))
                    ((symbol-function 'aob-prompt)
                     (lambda (s text &rest _) (push (list s text) sent)))
                    ((symbol-function 'aob-trace) #'ignore))
            (ygg-git-compare-review)))
        (should (equal spawned (list (list "claude" root))))
        (should (equal (aob-session-name (car (car sent))) "fresh"))
        (should-not (string-search "<review-comments>" (nth 1 (car sent))))))))

(ert-deftest ygg-git-compare-review-failed-start-keeps-comments ()
  (ygg-git-compare-tests--with-repo (root _tree)
    (ygg-git-compare-tests--with-sessions nil
      (let ((aob-acp-agents '(("claude" :command ("x")))))
        (ygg-git-compare-tests--with-compare root
          (ygg-git-compare-tests--goto "+two")
          (ygg-git-compare-tests--comment "kept")
          (cl-letf (((symbol-function 'completing-read) (lambda (&rest _) "new: claude"))
                    ((symbol-function 'aob-acp-spawn) #'ignore))
            (should-error (ygg-git-compare-review) :type 'user-error))
          (should (= (length ygg-git-compare--comments) 1)))))))

(ert-deftest ygg-git-compare-review-spawns-under-review-preset ()
  (ygg-git-compare-tests--with-repo (root _tree)
    (ygg-git-compare-tests--with-sessions nil
      (let* ((ygg-preset-user-directory (make-temp-file "ygg-git-compare-presets-" t))
             spawned prompted
             (aob-compose-spawn-function
              (lambda (text &rest _)
                (push (list text aob-compose--dir aob-prompt-typed) spawned)
                (aob-create-session :id "planner" :backend 'acp :name "planner"
                                    :project aob-compose--dir :state 'starting))))
        (ygg-git-compare-tests--with-compare root
          (ygg-git-compare-tests--goto "+two")
          (ygg-git-compare-tests--comment "plan this @build")
          (cl-letf (((symbol-function 'completing-read)
                     (lambda (_p table &rest _) (car (all-completions "" table))))
                    ((symbol-function 'ygg-aob--expand-presets)
                     (lambda (text)
                       (dolist (p (ygg-preset-list default-directory) text)
                         (when (string-search (concat "@" (ygg-preset-name p)) text)
                           (setq text (format "%s\n\n<preset name=\"%s\">\n%s\n</preset>"
                                              text (ygg-preset-name p)
                                              (ygg-preset-body p)))))))
                    ((symbol-function 'aob-prompt)
                     (lambda (&rest args) (push args prompted)))
                    ((symbol-function 'aob-trace) #'ignore))
            (ygg-git-compare-review))
          (should-not ygg-git-compare--comments))
        (should (= (length spawned) 1))
        (pcase-let ((`(,text ,dir ,typed) (car spawned)))
          (should (string-prefix-p "@review " text))
          (should (string-search "<preset name=\"review\">" text))
          (should-not (string-search "<preset name=\"build\">" text))
          (should (string-search "plan this @build" text))
          (should (equal dir root))
          (should typed))
        (should-not prompted)
        (delete-directory ygg-preset-user-directory t)))))

(ert-deftest ygg-git-compare-review-cap-notes-what-was-cut ()
  (ygg-git-compare-tests--with-repo (root _tree)
    (ygg-git-compare-tests--with-compare root
      (let* ((ygg-git-compare-review-max-chars 20)
             (m (ygg-git-compare-review-prompt)))
        (should (string-match-p "… [0-9]+ more characters left out\n</compare>\\'" m))
        (should-not (string-search "+b1" m))))))

(defconst ygg-git-compare-tests--presets
  (expand-file-name "../presets/" (file-name-directory
                                   (or load-file-name buffer-file-name))))

(ert-deftest ygg-git-compare-review-preset-parses-like-spec ()
  (let* ((dir ygg-git-compare-tests--presets)
         (keys (lambda (file)
                 (let ((fields (car (ygg-preset--parse (expand-file-name file dir))))
                       out)
                   (while fields (push (pop fields) out) (pop fields))
                   (nreverse out))))
         (review (ygg-preset--parse (expand-file-name "review.md" dir))))
    (should (equal (funcall keys "review.md") (funcall keys "spec.md")))
    (should (equal (plist-get (car review) :name) "review"))
    (should (member (plist-get (car review) :mode) ygg-preset-modes))
    (should (string-search "todo_write" (cdr review)))))

;;; Findings

(ert-deftest ygg-git-compare-right-pane-follows-a-rename ()
  (ygg-git-compare-tests--with-repo (root _tree)
    (ygg-git-compare-tests--write (expand-file-name "long.txt" root)
                                  (mapconcat #'number-to-string (number-sequence 1 50) "\n"))
    (ygg-git-compare-tests--git root "add" "long.txt")
    (ygg-git-compare-tests--git root "commit" "-q" "-m" "long")
    (ygg-git-compare-tests--git root "checkout" "-q" "-b" "ren")
    (ygg-git-compare-tests--git root "mv" "long.txt" "c.txt")
    (ygg-git-compare-tests--write (expand-file-name "c.txt" root)
                                  (mapconcat (lambda (n) (if (= n 25) "changed"
                                                           (number-to-string n)))
                                             (number-sequence 1 50) "\n"))
    (ygg-git-compare-tests--git root "commit" "-q" "-am" "move")
    (ygg-git-compare-tests--git root "checkout" "-q" "main")
    (dolist (limit '(2000 1))
      (let ((ygg-magit-diff-line-limit limit))
        (with-current-buffer (ygg-git-compare-buffer root '(rev . "main") '(rev . "ren"))
          (let ((ygg-git-compare--file-window (selected-window)))
            (with-current-buffer (ygg-git-compare--show-file "c.txt")
              (should (equal magit-buffer-diff-files '("long.txt" "c.txt")))
              (magit-section-show-level-4-all)
              (should (string-match-p "^\\+changed" (buffer-string)))
              (should-not (string-match-p "^\\+1$" (buffer-string)))
              (ygg-git-compare-tests--goto "-25")
              (let ((anchor (ygg-git-compare--anchor)))
                (should (equal (plist-get anchor :file) "long.txt"))
                (should (equal (plist-get anchor :line) 25))))))))))

(ert-deftest ygg-git-compare-comments-are-kept-for-the-same-sides ()
  (ygg-git-compare-tests--with-repo (root _tree)
    (cl-letf (((symbol-function 'y-or-n-p) (lambda (&rest _) (error "Asked"))))
      (with-current-buffer (ygg-git-compare-open '(rev . "main") '(rev . "feature"))
        (magit-section-show-level-4-all)
        (ygg-git-compare-tests--goto "+two")
        (ygg-git-compare-tests--comment "keep me")
        (ygg-git-compare-quit))
      (with-current-buffer (ygg-git-compare-open '(rev . "feature") '(rev . "main"))
        (should-not ygg-git-compare--comments)
        (ygg-git-compare-quit))
      (let ((again (ygg-git-compare-open '(rev . "main") '(rev . "feature"))))
        (should (equal (mapcar (lambda (c) (plist-get c :text))
                               (buffer-local-value 'ygg-git-compare--comments again))
                       '("keep me")))
        (with-current-buffer again (ygg-git-compare-quit))
        (should-not (buffer-live-p again))))))

(ert-deftest ygg-git-compare-names-a-nested-repository-without-diffing-it ()
  (ygg-git-compare-tests--with-repo (root tree)
    (let ((nested (expand-file-name "nested/" tree)))
      (make-directory nested)
      (ygg-git-compare-tests--git nested "init" "-q")
      (ygg-git-compare-tests--write (expand-file-name "inner.txt" nested) "inner\n"))
    (ygg-git-compare-tests--write (expand-file-name "u.txt" tree) "untracked\n")
    (with-current-buffer (ygg-git-compare-buffer root '(rev . "main") (cons 'worktree tree))
      (should (equal (plist-get ygg-git-compare--plan :untracked) '("nested/" "u.txt")))
      (should-not (member "nested/" (ygg-git-compare-tests--files-shown)))
      (ygg-git-compare-tests--goto "nested/")
      (should (looking-at-p "nested/  nested repository, not diffed"))
      (should-not (magit-file-at-point))
      (let ((prompt (ygg-git-compare-review-prompt)))
        (should (string-search "untracked nested/: a nested repository, not diffed" prompt))
        (should (string-match-p "^\\+untracked" prompt))
        (should-not (string-search "inner" prompt))))))

(ert-deftest ygg-git-compare-review-names-a-remote-checkout-as-its-agent-sees-it ()
  (let ((remote "/ssh:host:/srv/repo/"))
    (with-temp-buffer
      (setq-local ygg-git-compare--a '(:label "main" :diff "aaa" :log "aaa"))
      (setq-local ygg-git-compare--b (list :label "repo [x]" :diff "bbb" :log "bbb"
                                           :dir remote :uncommitted t))
      (setq-local ygg-git-compare--plan (list :work ygg-git-compare--b :dir remote
                                              :range "aaa"))
      (setq-local ygg-git-compare--dots "...")
      (setq-local default-directory remote)
      (cl-letf (((symbol-function 'ygg-git-compare--git) (lambda (&rest _) "")))
        (let ((prompt (ygg-git-compare-review-prompt)))
          (should (string-search "repository /srv/repo/\n" prompt))
          (should (string-search "aaa.../srv/repo/" prompt))
          (should-not (string-search "/ssh:" prompt)))))))

(ert-deftest ygg-git-compare-review-diff-ignores-external-diff-and-color ()
  (ygg-git-compare-tests--with-repo (root tree)
    (let ((ext (expand-file-name "../ext.sh" root)))
      (ygg-git-compare-tests--write ext "#!/bin/sh\necho EXTERNAL\n")
      (set-file-modes ext #o755)
      (ygg-git-compare-tests--git root "config" "diff.external" ext)
      (ygg-git-compare-tests--git root "config" "color.ui" "always"))
    (ygg-git-compare-tests--write (expand-file-name "a.txt" tree) "1\ntwo\n3\ndirty\n")
    (ygg-git-compare-tests--write (expand-file-name "u.txt" tree) "untracked\n")
    (with-current-buffer (ygg-git-compare-buffer root '(rev . "main") (cons 'worktree tree))
      (let ((prompt (ygg-git-compare-review-prompt)))
        (should (string-match-p "^\\+dirty" prompt))
        (should (string-match-p "^\\+untracked" prompt))
        (should-not (string-search "EXTERNAL" prompt))
        (should-not (string-search "\e[" prompt))))))

(ert-deftest ygg-git-compare-pull-request-comes-from-the-repository-gh-lists ()
  (ygg-git-compare-tests--with-repo (root _tree)
    (let ((fork (expand-file-name "../fork.git" root))
          (upstream (expand-file-name "../upstream.git" root))
          (feature (ygg-git-compare-tests--git root "rev-parse" "feature")))
      (ygg-git-compare-tests--git root "init" "-q" "--bare" fork)
      (ygg-git-compare-tests--git root "init" "-q" "--bare" upstream)
      (ygg-git-compare-tests--git root "remote" "add" "origin" fork)
      (ygg-git-compare-tests--git root "remote" "add" "parent" upstream)
      (ygg-git-compare-tests--git root "push" "-q" "origin" "main~1:refs/heads/main")
      (ygg-git-compare-tests--git root "push" "-q" "parent" "main" "feature:refs/pull/7/head")
      (ygg-git-compare-tests--git root "fetch" "-q" "--all")
      (should (equal (ygg-git-compare--url-key "git@GitHub.com:Owner/Repo.git")
                     (ygg-git-compare--url-key "https://github.com/owner/repo/")))
      (cl-letf (((symbol-function 'ygg-git-compare--gh-repo-url)
                 (lambda () (concat "file://" upstream)))
                ((symbol-function 'ygg-git-compare--gh-pulls)
                 (lambda () '((:number 7 :title "Feature work" :headRefName "feature"
                                       :baseRefName "main")))))
        (let ((spec (cdr (seq-find (lambda (c) (eq (cadr c) 'pr))
                                   (ygg-git-compare-candidates t)))))
          (should (equal (plist-get (cdr spec) :remote) "parent"))
          (should (equal (ygg-git-compare-default-a spec) '(rev . "parent/main")))
          (should (equal (plist-get (cdr (ygg-git-compare--prepare spec)) :sha)
                         feature)))))))

(ert-deftest ygg-git-compare-toggle-without-shared-history-changes-nothing ()
  (ygg-git-compare-tests--with-repo (root tree)
    (ygg-git-compare-tests--git tree "checkout" "-q" "--orphan" "pages")
    (ygg-git-compare-tests--git tree "rm" "-rqf" ".")
    (ygg-git-compare-tests--write (expand-file-name "index.html" tree) "<p>\n")
    (ygg-git-compare-tests--git tree "add" "index.html")
    (ygg-git-compare-tests--git tree "commit" "-q" "-m" "pages")
    (ygg-git-compare-tests--write (expand-file-name "index.html" tree) "<p>dirty\n")
    (with-current-buffer (ygg-git-compare-buffer root '(rev . "main") (cons 'worktree tree))
      (let ((range magit-buffer-diff-range)
            (plan ygg-git-compare--plan)
            (label (ygg-git-compare--range-label)))
        (should (equal ygg-git-compare--dots ".."))
        (should-error (ygg-git-compare-toggle-dots) :type 'user-error)
        (should (equal ygg-git-compare--dots ".."))
        (should (eq ygg-git-compare--plan plan))
        (should (equal magit-buffer-diff-range range))
        (should (equal (ygg-git-compare--range-label) label))
        (ygg-git-compare--header)
        (should (string-search "A..B" (format "%s" header-line-format)))))))

(ert-deftest ygg-git-compare-url-key-leaves-out-the-port ()
  (dolist (url '("ssh://git@h.example:2222/g/p.git" "https://h.example:8443/g/p.git"
                 "git@H.example:g/p.git" "https://h.example/g/p/"))
    (should (equal (ygg-git-compare--url-key url) "h.example/g/p"))))

(provide 'ygg-git-compare-tests)
;;; ygg-git-compare-tests.el ends here
