;;; ygg-git-compare-tests.el --- comparing two sides of a repository -*- lexical-binding: t; -*-

;;; Code:

(let ((builds (expand-file-name "../elpaca/builds/"
                                (file-name-directory
                                 (or load-file-name buffer-file-name)))))
  (dolist (p '("magit" "magit-section" "compat" "dash" "llama" "cond-let"
               "transient" "with-editor"))
    (add-to-list 'load-path (expand-file-name p builds))))

(require 'ert)
(require 'cl-lib)
(require 'magit)
(require 'ygg-git-compare)
(require 'ygg-magit-review)

(defvar ygg-magit-diff-line-limit)

(defun ygg-git-compare-tests--git (dir &rest args)
  (let ((default-directory dir))
    (with-temp-buffer
      (unless (zerop (apply #'call-process "git" nil t nil args))
        (error "git %S failed: %s" args (buffer-string)))
      (string-trim (buffer-string)))))

(defun ygg-git-compare-tests--write (file text)
  (with-temp-file file (insert text)))

(defmacro ygg-git-compare-tests--with-repo (vars &rest body)
  "A repo on main with a feature branch checked out in a second worktree.
VARS binds (ROOT TREE): the main worktree and the feature one.  Feature
changes a.txt and adds b.txt in two commits; main then changes shared.txt."
  (declare (indent 1))
  (let ((root (nth 0 vars)) (tree (nth 1 vars)))
    `(let* ((process-environment
             (append '("GIT_CONFIG_GLOBAL=/dev/null" "GIT_CONFIG_NOSYSTEM=1")
                     process-environment))
            (outer (file-name-as-directory
                    (file-truename (make-temp-file "ygg-git-compare-" t))))
            (,root (file-name-as-directory (expand-file-name "main" outer)))
            (,tree (file-name-as-directory (expand-file-name "wt" outer)))
            (default-directory (progn (make-directory ,root) ,root))
            (magit-refresh-verbose nil))
       (unwind-protect
           (cl-flet ((git (&rest args) (apply #'ygg-git-compare-tests--git ,root args))
                     (commit (msg) (ygg-git-compare-tests--git ,root "add" ".")
                       (ygg-git-compare-tests--git ,root "commit" "-q" "-m" msg)))
             (git "init" "-q" "-b" "main")
             (git "config" "user.name" "Compare Test")
             (git "config" "user.email" "compare@example.invalid")
             (git "config" "commit.gpgsign" "false")
             (ygg-git-compare-tests--write (expand-file-name "a.txt" ,root) "1\n2\n3\n")
             (ygg-git-compare-tests--write (expand-file-name "shared.txt" ,root) "s\n")
             (commit "base")
             (git "branch" "feature")
             (git "worktree" "add" "-q" ,tree "feature")
             (ygg-git-compare-tests--write (expand-file-name "a.txt" ,tree) "1\ntwo\n3\n")
             (ygg-git-compare-tests--git ,tree "commit" "-q" "-am" "fix a")
             (ygg-git-compare-tests--write (expand-file-name "b.txt" ,tree) "b1\nb2\n")
             (ygg-git-compare-tests--git ,tree "add" "b.txt")
             (ygg-git-compare-tests--git ,tree "commit" "-q" "-m" "add b")
             (ygg-git-compare-tests--write (expand-file-name "shared.txt" ,root) "s\nmain\n")
             (commit "main moves")
             ,@body)
         (dolist (b (buffer-list))
           (when (and (with-current-buffer b (derived-mode-p 'magit-mode))
                      (file-in-directory-p (buffer-local-value 'default-directory b)
                                           outer))
             (kill-buffer b)))
         (delete-directory outer t)))))

(ert-deftest ygg-git-compare-resolves-branch-and-commit ()
  (ygg-git-compare-tests--with-repo (root _tree)
    (let ((feature (ygg-git-compare-tests--git root "rev-parse" "feature"))
          (short (ygg-git-compare-tests--git root "rev-parse" "--short" "main")))
      (let ((side (ygg-git-compare-resolve '(rev . "feature"))))
        (should (equal (plist-get side :diff) feature))
        (should (equal (plist-get side :log) feature))
        (should-not (plist-get side :uncommitted)))
      (should (equal (plist-get (ygg-git-compare-resolve (cons 'rev short)) :diff)
                     (ygg-git-compare-tests--git root "rev-parse" "main")))
      (should-error (ygg-git-compare-resolve '(rev . "no-such-branch"))
                    :type 'user-error))))

(ert-deftest ygg-git-compare-resolves-clean-worktree-to-head ()
  (ygg-git-compare-tests--with-repo (root tree)
    (let ((side (ygg-git-compare-resolve (cons 'worktree tree)))
          (head (ygg-git-compare-tests--git tree "rev-parse" "HEAD")))
      (should (equal (plist-get side :diff) head))
      (should (equal (plist-get side :log) head))
      (should-not (plist-get side :uncommitted))
      (should (string-match-p "\\`wt \\[feature\\]" (plist-get side :label)))
      (ignore root))))

(ert-deftest ygg-git-compare-snapshots-dirty-worktree-untouched ()
  (ygg-git-compare-tests--with-repo (root tree)
    (ygg-git-compare-tests--write (expand-file-name "a.txt" tree) "1\ntwo\n3\ndirty\n")
    (ygg-git-compare-tests--write (expand-file-name "u.txt" tree) "untracked\n")
    (let* ((status-before (ygg-git-compare-tests--git tree "status" "--porcelain"))
           (refs-before (ygg-git-compare-tests--git root "for-each-ref"))
           (side (ygg-git-compare-resolve (cons 'worktree tree)))
           (snapshot (plist-get side :diff)))
      (should (plist-get side :uncommitted))
      (should (equal (plist-get side :log)
                     (ygg-git-compare-tests--git tree "rev-parse" "HEAD")))
      (should-not (equal snapshot (plist-get side :log)))
      (should (string-match-p "dirty" (ygg-git-compare-tests--git
                                       root "show" (concat snapshot ":a.txt"))))
      (should-not (zerop (let ((default-directory root))
                           (call-process "git" nil nil nil "cat-file" "-e"
                                         (concat snapshot ":u.txt")))))
      (should (equal (ygg-git-compare-tests--git tree "stash" "list") ""))
      (should (equal (ygg-git-compare-tests--git root "stash" "list") ""))
      (should (equal (ygg-git-compare-tests--git tree "status" "--porcelain")
                     status-before))
      (should (equal (ygg-git-compare-tests--git root "for-each-ref") refs-before))
      (should (equal (ygg-git-compare-tests--git
                      root "diff" "--name-only" (concat "feature..." snapshot))
                     "a.txt")))))

(defun ygg-git-compare-tests--files-shown ()
  "The files whose diff sections this magit diff buffer holds, in order."
  (let (files)
    (magit-map-sections (lambda (s) (when (and (eq (oref s type) 'file)
                                               (not (eq (oref (oref s parent) type)
                                                        'diffstat)))
                                      (push (oref s value) files))))
    (nreverse files)))

(ert-deftest ygg-git-compare-opens-magit-diff-of-the-range ()
  (ygg-git-compare-tests--with-repo (root tree)
    (ygg-git-compare-tests--write (expand-file-name "a.txt" tree) "1\ntwo\n3\ndirty\n")
    (let* ((start-buffer (window-buffer))
           (main (ygg-git-compare-tests--git root "rev-parse" "main"))
           (list (ygg-git-compare-open '(rev . "main") (cons 'worktree tree)))
           (snapshot (with-current-buffer list
                       (plist-get ygg-git-compare--b :diff))))
      (should (= (length (window-list)) 2))
      (should (eq (window-buffer) list))
      (should (< (abs (- (window-total-width) (round (* 0.38 (frame-width))))) 3))
      (with-current-buffer list
        (should (derived-mode-p 'magit-diff-mode))
        (should magit-buffer-locked-p)
        (should ygg-git-compare-mode)
        (should (equal magit-buffer-diff-range (concat main "..." snapshot)))
        (should (member "--stat" magit-buffer-diff-args))
        (should (equal (ygg-git-compare-tests--files-shown) '("a.txt" "b.txt")))
        (should (string-match-p "A: main ↔ B: wt \\[feature\\] \\+ uncommitted"
                                (format "%s" header-line-format)))
        (should (string-match-p "untracked" (format "%s" header-line-format)))
        (should (equal (magit-file-at-point) "a.txt"))
        (should (equal (ygg-magit-review--target) magit-buffer-diff-range))
        (let ((block (ygg-magit-review--block (file-name-as-directory root)
                                              magit-buffer-diff-range)))
          (should (string-match-p "fix a" block))
          (should (string-match-p "\\+b1" block))
          (should-not (string-match-p "main moves" block))))
      (with-current-buffer (window-buffer (next-window))
        (should (derived-mode-p 'magit-diff-mode))
        (should (equal magit-buffer-diff-files '("a.txt")))
        (should (string-match-p "^\\+dirty" (buffer-string))))
      (with-current-buffer list
        (magit-section-forward)
        (should (equal (magit-file-at-point) "b.txt"))
        (ygg-git-compare--follow list)
        (with-current-buffer (window-buffer (next-window))
          (should (equal magit-buffer-diff-files '("b.txt")))))
      (with-current-buffer list
        (ygg-git-compare-swap)
        (should (string-match-p "A: wt \\[feature\\] \\+ uncommitted ↔ B: main "
                                (format "%s" header-line-format)))
        (ygg-git-compare-quit))
      (should-not (buffer-live-p list))
      (should-not (seq-find (lambda (b) (string-prefix-p "magit-diff: compare"
                                                        (buffer-name b)))
                            (buffer-list)))
      (should (= (length (window-list)) 1))
      (should (eq (window-buffer) start-buffer)))))

(ert-deftest ygg-git-compare-swaps-and-toggles-dots ()
  (ygg-git-compare-tests--with-repo (root _tree)
    (let ((main (ygg-git-compare-tests--git root "rev-parse" "main"))
          (feature (ygg-git-compare-tests--git root "rev-parse" "feature")))
      (with-current-buffer (ygg-git-compare-buffer root '(rev . "main")
                                                   '(rev . "feature"))
        (should (equal magit-buffer-diff-range (concat main "..." feature)))
        (ygg-git-compare-toggle-dots)
        (should (equal magit-buffer-diff-range (concat main ".." feature)))
        (should (equal (ygg-git-compare-tests--files-shown)
                       '("a.txt" "b.txt" "shared.txt")))
        (ygg-git-compare-swap)
        (should (equal magit-buffer-diff-range (concat feature ".." main)))
        (should (string-match-p "A: feature ↔ B: main" (format "%s" header-line-format)))
        (ygg-git-compare-toggle-dots)
        (should (equal (ygg-git-compare-tests--files-shown) '("shared.txt")))))))

(ert-deftest ygg-git-compare-refresh-snapshots-again ()
  (ygg-git-compare-tests--with-repo (root tree)
    (with-current-buffer (ygg-git-compare-buffer root '(rev . "main")
                                                 (cons 'worktree tree))
      (should-not (plist-get ygg-git-compare--b :uncommitted))
      (ygg-git-compare-tests--write (expand-file-name "c.txt" tree) "new\n")
      (ygg-git-compare-tests--git tree "add" "c.txt")
      (call-interactively (keymap-lookup ygg-git-compare-mode-map
                                         "<remap> <magit-refresh>"))
      (should (plist-get ygg-git-compare--b :uncommitted))
      (should (member "c.txt" (ygg-git-compare-tests--files-shown)))
      (should (equal (ygg-git-compare-tests--git tree "stash" "list") "")))))

(ert-deftest ygg-git-compare-log-shows-each-side ()
  (ygg-git-compare-tests--with-repo (root _tree)
    (with-current-buffer (ygg-git-compare-buffer root '(rev . "main")
                                                 '(rev . "feature"))
      (let ((list (current-buffer)))
        (ygg-git-compare-log)
        (let ((log (seq-find (lambda (b) (eq (buffer-local-value
                                              'ygg-git-compare--list-buffer b)
                                             list))
                             (buffer-list))))
          (with-current-buffer log
            (should (derived-mode-p 'magit-log-mode))
            (should (member "--left-right" magit-buffer-log-args))
            (should (string-match-p "main moves" (buffer-string)))
            (should (string-match-p "add b" (buffer-string)))
            (should (string-match-p "fix a" (buffer-string)))))))))

(ert-deftest ygg-git-compare-leaves-patch-out-of-huge-ranges ()
  (ygg-git-compare-tests--with-repo (root tree)
    (let ((ygg-magit-diff-line-limit 1))
      (with-current-buffer (ygg-git-compare-buffer root '(rev . "main")
                                                   (cons 'worktree tree))
        (should (member "--no-patch" magit-buffer-diff-args))
        (should (equal (ygg-git-compare-tests--files-shown) nil))
        (should (equal (magit-file-at-point) "a.txt"))
        (let ((ygg-git-compare--file-window (selected-window)))
          (with-current-buffer (ygg-git-compare--show-file "b.txt")
            (should (equal magit-buffer-diff-files '("b.txt")))
            (should-not (member "--no-patch" magit-buffer-diff-args))
            (should (string-match-p "^\\+b1" (buffer-string)))))
        (let ((ygg-magit-diff-line-limit 2000)
              (magit-direct-use-buffer-arguments 'selected))
          (ygg-git-compare-toggle-dots)
          (should-not (member "--no-patch" magit-buffer-diff-args))
          (should (equal (ygg-git-compare-tests--files-shown)
                         '("a.txt" "b.txt" "shared.txt"))))))))

(ert-deftest ygg-git-compare-diffs-unrelated-histories-directly ()
  (ygg-git-compare-tests--with-repo (root _tree)
    (ygg-git-compare-tests--git root "checkout" "-q" "--orphan" "pages")
    (ygg-git-compare-tests--git root "rm" "-rq" "--cached" ".")
    (ygg-git-compare-tests--write (expand-file-name "index.html" root) "<p>\n")
    (ygg-git-compare-tests--git root "add" "index.html")
    (ygg-git-compare-tests--git root "commit" "-q" "-m" "pages")
    (with-current-buffer (ygg-git-compare-buffer root '(rev . "main") '(rev . "pages"))
      (should (equal ygg-git-compare--dots ".."))
      (should (member "index.html" (ygg-git-compare-tests--files-shown))))))

(ert-deftest ygg-git-compare-from-a-compare-keeps-the-first-layout ()
  (ygg-git-compare-tests--with-repo (_root tree)
    (let* ((start-buffer (window-buffer))
           (first (ygg-git-compare-open '(rev . "main") (cons 'worktree tree)))
           (second (with-current-buffer first
                     (ygg-git-compare-open '(rev . "feature") '(rev . "main")))))
      (should-not (buffer-live-p first))
      (with-current-buffer second (ygg-git-compare-quit))
      (should (= (length (window-list)) 1))
      (should (eq (window-buffer) start-buffer)))))

(ert-deftest ygg-git-compare-pull-request-fetched-without-branch ()
  (ygg-git-compare-tests--with-repo (root _tree)
    (let ((remote (expand-file-name "../remote.git" root))
          (feature (ygg-git-compare-tests--git root "rev-parse" "feature")))
      (ygg-git-compare-tests--git root "init" "-q" "--bare" remote)
      (ygg-git-compare-tests--git root "remote" "add" "origin" remote)
      (ygg-git-compare-tests--git root "push" "-q" "origin" "main" "feature:refs/pull/7/head")
      (ygg-git-compare-tests--git root "fetch" "-q" "origin")
      (let ((branches (ygg-git-compare-tests--git root "branch" "-a"))
            (gh-calls 0))
        (cl-letf (((symbol-function 'ygg-git-compare--gh-pulls)
                   (lambda ()
                     (cl-incf gh-calls)
                     '((:number 7 :title "Feature work" :headRefName "feature"
                                :baseRefName "main")))))
          (should-not (rassq 'pr (mapcar (lambda (c) (cons (car c) (cadr c)))
                                         (ygg-git-compare-candidates))))
          (should (= gh-calls 0))
          (let* ((cands (ygg-git-compare-candidates t))
                 (pr (seq-find (lambda (c) (eq (cadr c) 'pr)) cands))
                 (spec (cdr pr)))
            (should (= gh-calls 1))
            (should (equal (car pr) "#7 Feature work"))
            (should (equal (get-text-property 0 'ygg-git-compare-group (car pr))
                           "Pull requests"))
            (should (equal (ygg-git-compare-default-a spec) '(rev . "origin/main")))
            (let ((prepared (ygg-git-compare--prepare spec)))
              (should (equal (plist-get (cdr prepared) :sha) feature))
              (let ((side (ygg-git-compare-resolve prepared)))
                (should (equal (plist-get side :diff) feature))
                (should (string-prefix-p "#7" (plist-get side :label)))))))
        (should (equal (ygg-git-compare-tests--git root "branch" "-a") branches))
        (should (equal (ygg-git-compare-tests--git root "for-each-ref" "refs/pull") ""))
        (should (equal (ygg-git-compare-tests--git root "stash" "list") ""))))))

(ert-deftest ygg-git-compare-defaults-a-to-default-branch ()
  (ygg-git-compare-tests--with-repo (root tree)
    (should (equal (ygg-git-compare-default-a (cons 'worktree tree)) '(rev . "main")))
    (should (equal (ygg-git-compare--here-spec) (cons 'worktree root)))))

(provide 'ygg-git-compare-tests)
;;; ygg-git-compare-tests.el ends here
