;;; ygg-git-compare-comments-tests.el --- review comments on a compare -*- lexical-binding: t; -*-

;;; Code:

(let ((builds (expand-file-name "../elpaca/builds/"
                                (file-name-directory
                                 (or load-file-name buffer-file-name)))))
  (dolist (p '("magit" "magit-section" "compat" "dash" "llama" "cond-let"
               "transient" "with-editor"))
    (add-to-list 'load-path (expand-file-name p builds))))

(require 'ert)
(require 'cl-lib)
(require 'magit)
(require 'ygg-git-compare)
(require 'ygg-git-compare-comments)

(defun ygg-git-compare-comments-tests--git (dir &rest args)
  (let ((default-directory dir))
    (with-temp-buffer
      (unless (zerop (apply #'call-process "git" nil t nil args))
        (error "git %S failed: %s" args (buffer-string)))
      (string-trim (buffer-string)))))

(defmacro ygg-git-compare-comments-tests--with-repo (root &rest body)
  "BODY in a repo bound to ROOT: feature rewrites lines 2 and 3 of a.txt
and adds b.txt; main stays checked out."
  (declare (indent 1))
  `(let* ((process-environment
           (append '("GIT_CONFIG_GLOBAL=/dev/null" "GIT_CONFIG_NOSYSTEM=1")
                   process-environment))
          (,root (file-name-as-directory
                  (file-truename (make-temp-file "ygg-git-compare-comments-" t))))
          (default-directory ,root)
          (magit-refresh-verbose nil)
          (transient-mark-mode t))
     (unwind-protect
         (cl-flet ((git (&rest args) (apply #'ygg-git-compare-comments-tests--git ,root args))
                   (write (file text) (with-temp-file (expand-file-name file ,root)
                                        (insert text))))
           (git "init" "-q" "-b" "main")
           (git "config" "user.name" "Comments Test")
           (git "config" "user.email" "comments@example.invalid")
           (git "config" "commit.gpgsign" "false")
           (write "a.txt" "1\n2\n3\n4\n5\n")
           (git "add" ".")
           (git "commit" "-q" "-m" "base")
           (git "checkout" "-q" "-b" "feature")
           (write "a.txt" "1\ntwo\nthree\n4\n5\n")
           (write "b.txt" "b1\nb2\n")
           (git "add" ".")
           (git "commit" "-q" "-m" "feature")
           (git "checkout" "-q" "main")
           ,@body)
       (dolist (b (buffer-list))
         (when (or (string-prefix-p "compose:review:" (buffer-name b))
                   (and (with-current-buffer b (derived-mode-p 'magit-mode))
                        (file-in-directory-p (buffer-local-value 'default-directory b)
                                             ,root)))
           (kill-buffer b)))
       (delete-directory ,root t))))

(defmacro ygg-git-compare-comments-tests--with-compare (root &rest body)
  (declare (indent 1))
  `(with-current-buffer (ygg-git-compare-buffer ,root '(rev . "main") '(rev . "feature"))
     (magit-section-show-level-4-all)
     ,@body))

(defun ygg-git-compare-comments-tests--goto (text)
  (goto-char (point-min))
  (search-forward text)
  (beginning-of-line))

(defun ygg-git-compare-comments-tests--write (buffer text &optional type)
  "Write TEXT in the comment BUFFER, typed TYPE, and save it."
  (with-current-buffer buffer
    (insert text)
    (setq ygg-git-compare--draft (plist-put ygg-git-compare--draft :type type))
    (aob-compose-send)))

(defun ygg-git-compare-comments-tests--shown ()
  "Every comment block shown in this buffer, as one string."
  (mapconcat (lambda (ov) (concat (overlay-get ov 'before-string)
                                  (overlay-get ov 'after-string)))
             (seq-filter (lambda (ov) (overlay-get ov 'ygg-git-compare-comments))
                         (overlays-in (point-min) (point-max)))
             "\n"))

(defun ygg-git-compare-comments-tests--texts (comments)
  (mapcar (lambda (c) (plist-get c :text)) comments))

(ert-deftest ygg-git-compare-comments-at-every-level ()
  (ygg-git-compare-comments-tests--with-repo root
    (ygg-git-compare-comments-tests--with-compare root
      (ygg-git-compare-comments-tests--goto "+two")
      (ygg-git-compare-comments-tests--write (ygg-git-compare-comment) "on a line")
      (ygg-git-compare-comments-tests--goto " 1")
      (ygg-git-compare-select-lines)
      (should (region-active-p))
      (dotimes (_ 3) (ygg-git-compare-select-down))
      (ygg-git-compare-comments-tests--write (ygg-git-compare-comment) "on a range")
      (should-not (region-active-p))
      (ygg-git-compare-comments-tests--goto "-2")
      (push-mark (point) t t)
      (ygg-git-compare-comments-tests--goto "+two")
      (ygg-git-compare-comments-tests--write (ygg-git-compare-comment) "across sides")
      (ygg-git-compare-comments-tests--goto "+b1")
      (ygg-git-compare-comments-tests--write (ygg-git-compare-comment-file) "on a file")
      (ygg-git-compare-comments-tests--write (ygg-git-compare-comment-review) "on it all")
      (pcase-let ((`(,line ,range ,across ,file ,review) (ygg-git-compare-comments-list)))
        (should (equal (plist-get line :text) "on a line"))
        (should (eq (plist-get line :level) 'line))
        (should (equal (list (plist-get line :side) (plist-get line :line)) '(new 2)))
        (should (eq (plist-get range :level) 'range))
        (should (equal (list (plist-get range :start-side) (plist-get range :start-line)
                             (plist-get range :start-old-line)
                             (plist-get range :side) (plist-get range :line))
                       '(new 1 1 new 2)))
        (should (equal (plist-get range :quote) " 1\n-2\n-3\n+two"))
        (should (equal (list (plist-get across :start-side) (plist-get across :start-line)
                             (plist-get across :start-old-line)
                             (plist-get across :side) (plist-get across :line))
                       '(old 2 nil new 2)))
        (should (eq (plist-get file :level) 'file))
        (should (equal (plist-get file :file) "b.txt"))
        (should-not (plist-get file :line))
        (should (eq (plist-get review :level) 'review))
        (should-not (plist-get review :file))
        (dolist (c (list line range file review))
          (should (stringp (plist-get c :id)))
          (should-not (plist-member c :to))
          (should (equal (plist-get c :range) (ygg-git-compare--range-label)))
          (should-not (plist-get c :type)))
        (should (equal (ygg-git-compare--where range) "a.txt:1-2"))))))

(ert-deftest ygg-git-compare-comments-range-stays-in-one-file ()
  (ygg-git-compare-comments-tests--with-repo root
    (ygg-git-compare-comments-tests--with-compare root
      (ygg-git-compare-comments-tests--goto "+three")
      (push-mark (point) t t)
      (ygg-git-compare-comments-tests--goto "+b1")
      (should-error (ygg-git-compare-comment) :type 'user-error))))

(ert-deftest ygg-git-compare-comments-type-cycles-through-untyped ()
  (ygg-git-compare-comments-tests--with-repo root
    (ygg-git-compare-comments-tests--with-compare root
      (ygg-git-compare-comments-tests--goto "+two")
      (with-current-buffer (ygg-git-compare-comment)
        (should (string-search "a.txt:2" aob-compose--label))
        (should (member "untyped" aob-compose--tags))
        (ygg-git-compare-draft-cycle-type)
        (should (eq (plist-get ygg-git-compare--draft :type) 'issue))
        (ygg-git-compare-draft-cycle-type-back)
        (ygg-git-compare-draft-cycle-type-back)
        (should (eq (plist-get ygg-git-compare--draft :type) 'fix))
        (should (member "[fix]" aob-compose--tags))
        (insert "nice")
        (aob-compose-send))
      (should (eq (plist-get (car (ygg-git-compare-comments-list)) :type) 'fix))
      (ygg-git-compare-comments-tests--goto "+three")
      (with-current-buffer (ygg-git-compare-comment)
        (aob-compose-abort))
      (should (= (length (ygg-git-compare-comments-list)) 1)))))

(ert-deftest ygg-git-compare-comments-are-kept-across-reopening ()
  (ygg-git-compare-comments-tests--with-repo root
    (ygg-git-compare-comments-tests--with-compare root
      (ygg-git-compare-comments-tests--goto "+two")
      (ygg-git-compare-comments-tests--write (ygg-git-compare-comment) "kept")
      (ygg-git-compare-comments-tests--goto "+three")
      (ygg-git-compare-comments-tests--write (ygg-git-compare-comment) "dropped")
      (ygg-git-compare-comments-drop
       (list (plist-get (cadr (ygg-git-compare-comments-list)) :id)))
      (kill-buffer))
    (should (file-exists-p (expand-file-name "ygg-review-comments.eld"
                                             (magit-gitdir root t))))
    (ygg-git-compare-comments-tests--with-compare root
      (should (equal (ygg-git-compare-comments-tests--texts (ygg-git-compare-comments-list))
                     '("kept")))
      (should (equal (cdr ygg-git-compare--store) "branch feature")))))

(ert-deftest ygg-git-compare-comments-shown-and-acted-on-at-point ()
  (ygg-git-compare-comments-tests--with-repo root
    (ygg-git-compare-comments-tests--with-compare root
      (ygg-git-compare-comments-tests--goto "+two")
      (ygg-git-compare-comments-tests--write (ygg-git-compare-comment) "first")
      (ygg-git-compare-comments-tests--goto " 1")
      (push-mark (point) t t)
      (ygg-git-compare-comments-tests--goto "+two")
      (ygg-git-compare-comments-tests--write (ygg-git-compare-comment) "ranged")
      (ygg-git-compare-comments-tests--write (ygg-git-compare-comment-review) "overall")
      (ygg-git-compare-refresh)
      (magit-section-show-level-4-all)
      (let ((shown (ygg-git-compare-comments-tests--shown)))
        (should (string-search "▎ first" shown))
        (should (string-search "L1–L2" shown))
        (should (string-search "overall" shown)))
      (should (string-search "overall" (overlay-get (car (overlays-in (point-min) (point-min)))
                                                    'before-string)))
      (ygg-git-compare-comments-tests--goto " 5")
      (ygg-git-compare-comment-next)
      (should (bobp))
      (ygg-git-compare-comment-next)
      (should (looking-at-p "^\\+two"))
      (ygg-git-compare-comment-previous)
      (should (bobp))
      (ygg-git-compare-comment-previous)
      (should (looking-at-p "^\\+two"))
      (cl-letf (((symbol-function 'completing-read)
                 (lambda (_p table &rest _)
                   (seq-find (lambda (label) (string-search "first" label))
                              (all-completions "" table)))))
        (ygg-git-compare-comment-copy)
        (should (equal (car kill-ring) "first"))
        (with-current-buffer (ygg-git-compare-comment)
          (should (equal (buffer-string) "first"))
          (goto-char (point-max))
          (insert ", again")
          (aob-compose-send))
        (should (equal (plist-get (car (ygg-git-compare-comments-list)) :text)
                       "first, again"))))))

(ert-deftest ygg-git-compare-comments-summary-lists-them-by-file ()
  (ygg-git-compare-comments-tests--with-repo root
    (ygg-git-compare-comments-tests--with-compare root
      (ygg-git-compare-comments-tests--goto "+two")
      (ygg-git-compare-comments-tests--write (ygg-git-compare-comment) "in a")
      (ygg-git-compare-comments-tests--goto "+b2")
      (ygg-git-compare-comments-tests--write (ygg-git-compare-comment) "in b")
      (ygg-git-compare-comments-receive root "feature"
                                        '((:file "a.txt" :line 3 :text "urgent"
                                                 :priority 0 :title "Fix it"))
                                        "claude")
      (let ((list (current-buffer)))
        (with-current-buffer (ygg-git-compare-comments-summary)
          (let ((text (buffer-string)))
            (should (string-search "Pending your check (1)" text))
            (should (< (string-search "urgent" text) (string-search "in a" text)
                       (string-search "in b" text)))
            (should (string-search "b.txt" text)))
          (goto-char (point-min))
          (search-forward "in b")
          (ygg-git-compare-comment-goto)
          (should (eq (current-buffer) list))
          (should (looking-at-p "^\\+b2")))
        (with-current-buffer (ygg-git-compare-comments-summary)
          (ygg-git-compare-comments-filter 0)
          (should (string-search "urgent" (buffer-string)))
          (should-not (string-search "in a" (buffer-string)))
          (goto-char (point-min))
          (search-forward "urgent")
          (ygg-git-compare-comment-delete)
          (should-not (string-search "urgent" (buffer-string))))
        (should (= (length (ygg-git-compare-comments-list t)) 2))))))

(ert-deftest ygg-git-compare-comments-from-an-agent-wait-for-a-check ()
  (ygg-git-compare-comments-tests--with-repo root
    (should (equal (ygg-git-compare-comments-receive
                    root "feature"
                    (vector '(:file "a.txt" :line 2 :side "new" :text "agent says"
                                    :type "issue" :priority 1 :title "Name it"
                                    :confidence 0.9)
                            '(:file "a.txt" :start_line 1 :line 2 :text "two lines")
                            '(:level "review" :correctness "patch is incorrect"
                                     :confidence 0.8 :text "why"))
                    "claude")
                   '(3 . "branch feature")))
    (ygg-git-compare-comments-tests--git root "checkout" "-q" "feature")
    (cl-letf (((symbol-function 'ygg-git-compare--gh) #'ignore))
      (with-current-buffer (with-temp-buffer (ygg-git-compare-review-branch))
        (magit-section-show-level-4-all)
        (should-not (ygg-git-compare-comments-list))
        (pcase-let ((`(,line ,range ,review) (ygg-git-compare-comments-list t)))
          (should (equal (plist-get line :author) "claude"))
          (should (eq (plist-get line :status) 'pending))
          (should (eq (plist-get line :type) 'issue))
          (should (eq (plist-get range :level) 'range))
          (should (equal (list (plist-get range :start-side) (plist-get range :side))
                         '(new new)))
          (should (eq (plist-get review :level) 'review)))
        (let ((shown (ygg-git-compare-comments-tests--shown)))
          (should (string-search "[P1]" shown))
          (should (string-search "Name it" shown))
          (should (string-search "claude" shown))
          (should (string-search "pending" shown))
          (should (string-search "✗ patch is incorrect · 0.8" shown)))
        (ygg-git-compare-comments-tests--goto "+two")
        (should (eq (key-binding "a" nil nil (point)) #'ygg-git-compare-comment-accept))
        (cl-letf (((symbol-function 'completing-read)
                   (lambda (_p table &rest _)
                     (seq-find (lambda (label) (string-search "agent says" label))
                                (all-completions "" table)))))
          (ygg-git-compare-comment-accept))
        (let ((accepted (car (ygg-git-compare-comments-list))))
          (should (equal (plist-get accepted :text) "agent says"))
          (should (equal (plist-get accepted :author) "claude"))
          (should (equal (plist-get accepted :range) (ygg-git-compare--range-label))))
        (cl-letf (((symbol-function 'y-or-n-p) (lambda (&rest _) t)))
          (ygg-git-compare-comments-dismiss-all))
        (should (equal (ygg-git-compare-comments-tests--texts
                        (ygg-git-compare-comments-list t))
                       '("agent says")))
        (ygg-git-compare-comments-receive root "feature" '((:file "a.txt" :line 3 :text "later"))
                                          "claude")
        (should (equal (ygg-git-compare-comments-tests--texts
                        (ygg-git-compare-comments-list t))
                       '("agent says" "later")))
        (ygg-git-compare-comments-tests--goto "+three")
        (ygg-git-compare-comment-delete)
        (should (= (length (ygg-git-compare-comments-list t)) 1))))))

(ert-deftest ygg-git-compare-comments-received-as-review-submit-sends-them ()
  (ygg-git-compare-comments-tests--with-repo root
    (let ((tree (expand-file-name "../wt" root)))
      (ygg-git-compare-comments-tests--git root "worktree" "add" "-q" tree "feature")
      (unwind-protect
          (progn
            (should (equal (ygg-git-compare--store-file tree)
                           (ygg-git-compare--store-file root)))
            (ygg-git-compare-comments-receive
             tree "feature"
             '((:level line :type nit :text "from mcp" :file "a.txt" :new-path "a.txt"
                       :side old :line 2 :start-line nil :start-side old
                       :title "Keep it" :priority 2 :confidence 0.5)
               (:level review :type nil :text "fine" :file nil :new-path nil :side new
                       :line nil :start-line nil :start-side new :title nil :priority nil
                       :confidence 0.7 :correctness "patch is correct"))
             "codex")
            (ygg-git-compare-comments-tests--with-compare root
              (pcase-let ((`(,line ,review) (ygg-git-compare-comments-list t)))
                (should (equal (list (plist-get line :side) (plist-get line :line)
                                     (plist-get line :start-side))
                               '(old 2 nil)))
                (should (eq (plist-get line :type) 'nit))
                (should-not (plist-get review :side)))
              (let ((shown (ygg-git-compare-comments-tests--shown)))
                (should (string-search "[P2] [nit]" shown))
                (should (string-search "✓ patch is correct · 0.7" shown)))))
        (delete-directory tree t)))))

(ert-deftest ygg-git-compare-comments-agent-prompt-renders-every-level ()
  (ygg-git-compare-comments-tests--with-repo root
    (ygg-git-compare-comments-tests--with-compare root
      (ygg-git-compare-comments-tests--goto " 1")
      (push-mark (point) t t)
      (ygg-git-compare-comments-tests--goto "+two")
      (with-current-buffer (ygg-git-compare-comment)
        (dotimes (_ 6) (ygg-git-compare-draft-cycle-type))
        (insert "tidy")
        (aob-compose-send))
      (ygg-git-compare-comments-tests--goto "+b1")
      (ygg-git-compare-comments-tests--write (ygg-git-compare-comment-file) "whole file" 'fix)
      (ygg-git-compare-comments-tests--write (ygg-git-compare-comment-review) "overall" 'todo)
      (let ((prompt (ygg-git-compare-review-prompt)))
        (should (string-search "[todo] a.txt:1-2\n>  1\n> -2\n> -3\n> +two\ntidy" prompt))
        (should (string-search "b.txt\nwhole file" prompt))
        (should (string-search "review\noverall" prompt))
        (should (string-search "\nbranch feature\n" prompt))
        (should (string-search "review_submit" prompt))))))

(ert-deftest ygg-git-compare-comments-keys-in-a-compare ()
  (ygg-git-compare-comments-tests--with-repo root
    (ygg-git-compare-comments-tests--with-compare root
      (run-hooks 'pre-command-hook)
      (ygg-git-compare-comments-tests--goto "+two")
      (ygg-git-compare-comments-tests--write (ygg-git-compare-comment) "mine")
      (ygg-git-compare-comments-receive root "feature" '((:file "a.txt" :line 2 :text "theirs"))
                                        "claude")
      (ygg-git-compare-comments-tests--goto "+two")
      (pcase-dolist (`(,key ,command)
                     '(("C" ygg-git-compare-comment)
                       ("c" ygg-git-compare-comment-moved)
                       ("v" ygg-git-compare-select-lines)
                       ("V" ygg-git-compare-select-lines)
                       ("x" ygg-git-compare-select-lines)
                       ("m" ygg-git-compare-comment-next)
                       ("M" ygg-git-compare-comment-previous)
                       ("] c" ygg-git-compare-next-hunk)
                       ("C-j" ygg-git-compare-next-hunk)
                       ("C-k" ygg-git-compare-previous-hunk)
                       ("[ c" ygg-git-compare-previous-hunk)
                       ("] f" ygg-git-compare-next-file)
                       ("[ f" ygg-git-compare-previous-file)
                       ("}" ygg-git-compare-next-file)
                       ("{" ygg-git-compare-previous-file)
                       ("] u" ygg-git-compare-next-unreviewed)
                       ("[ u" ygg-git-compare-previous-unreviewed)
                       ("] m" ygg-git-compare-comment-next)
                       ("[ m" ygg-git-compare-comment-previous)
                       ("/" isearch-forward-regexp)
                       ("n" ygg-git-compare-search-next)
                       ("N" ygg-git-compare-search-previous)
                       ("i" ygg-git-compare-comment-moved)
                       ("A" ygg-git-compare-comment-moved)
                       ("d d" ygg-git-compare-comment-delete)
                       ("K" ygg-git-compare-comment-moved)
                       ("y" ygg-git-compare-export-markdown)
                       ("Y" ygg-git-compare-comment-copy)
                       ("a" ygg-git-compare-comment-accept)
                       ("r" ygg-git-compare-mark-file-reviewed)
                       ("R" ygg-git-compare-mark-hunk-reviewed)
                       ("I" ygg-git-compare-interdiff)
                       ("e" ygg-git-compare-visit-b)
                       ("'" ygg-git-compare-visit-b)
                       (";" ygg-git-compare-dispatch)
                       ("?" ygg-git-compare-dispatch)
                       ("@" ygg-git-compare-review)
                       ("&" ygg-git-compare-submit)
                       ("b" ygg-git-compare-switch-base)
                       ("~" ygg-git-compare-swap)
                       ("." ygg-git-compare-toggle-dots)
                       ("#" ygg-git-compare-log)
                       ("q" ygg-git-compare-quit)))
        (should (equal (list key (key-binding (kbd key) nil nil (point))) (list key command))))
      (ygg-git-compare-comments-tests--goto "+three")
      (dolist (key '("Y" "a" "d d"))
        (should (string-search "No comment here"
                               (cadr (should-error (call-interactively (key-binding (kbd key)))
                                                   :type 'user-error)))))
      (dolist (key '("s" "S" "u" "U"))
        (should (eq (key-binding key) #'ygg-git-compare-read-only)))
      (should-not (eq (key-binding "k") #'ygg-git-compare-read-only))
      (should (eq (key-binding "C" nil nil (point)) #'ygg-git-compare-comment)))))

(defvar ygg--modeline-tag " NORMAL ")

(ert-deftest ygg-git-compare-comments-selection-stays-in-its-compare ()
  (ygg-git-compare-comments-tests--with-repo root
    (ygg-git-compare-comments-tests--with-compare root
      (let ((compare (current-buffer)))
        (setq-local ygg--modeline-tag " NORMAL ")
        (ygg-git-compare-comments-tests--goto " 1")
        (ygg-git-compare-select-lines)
        (should (equal ygg--modeline-tag " VISUAL "))
        (should (eq (key-binding "x") #'ygg-git-compare-select-down))
        (should (eq (key-binding "j") #'ygg-git-compare-select-down))
        (should (eq (key-binding (kbd "<escape>")) #'ygg-git-compare-select-lines))
        (with-temp-buffer
          (run-hooks 'pre-command-hook)
          (should-not (eq (key-binding "j") #'ygg-git-compare-select-down)))
        (should (equal (buffer-local-value 'ygg--modeline-tag compare) " NORMAL "))))))

(ert-deftest ygg-git-compare-comments-navigation-and-search ()
  (ygg-git-compare-comments-tests--with-repo root
    (ygg-git-compare-comments-tests--with-compare root
      (goto-char (point-min))
      (ygg-git-compare-next-file)
      (should (looking-at-p ".*a\\.txt"))
      (ygg-git-compare-next-hunk)
      (should (looking-at-p "@@"))
      (ygg-git-compare-next-file)
      (should (looking-at-p ".*b\\.txt"))
      (ygg-git-compare-previous-file)
      (should (looking-at-p ".*a\\.txt"))
      (let ((regexp-search-ring '("^\\+b")))
        (ygg-git-compare-search-next)
        (should (looking-at-p "\\+b1"))
        (ygg-git-compare-search-next)
        (should (looking-at-p "\\+b2"))
        (ygg-git-compare-search-next)
        (should (looking-at-p "\\+b1"))
        (ygg-git-compare-search-previous)
        (should (looking-at-p "\\+b2"))))))

(defvar ygg-magit-diff-line-limit)

(ert-deftest ygg-git-compare-comments-hunk-keys-reach-hunks-of-an-unwashed-diff ()
  (ygg-git-compare-comments-tests--with-repo root
    (let ((ygg-magit-diff-line-limit 1)
          (default-directory root))
      (save-window-excursion
        (let ((list (ygg-git-compare-open '(rev . "main") '(rev . "feature"))))
          (cl-flet ((press (command)
                      (set-buffer (window-buffer (selected-window)))
                      (funcall command)
                      (set-buffer (window-buffer (selected-window)))))
            (set-buffer list)
            (should (ygg-git-compare--unwashed-p))
            (should (equal (magit-file-at-point) "a.txt"))
            (should (eq (key-binding (kbd "] c")) #'ygg-git-compare-next-hunk))
            (press #'ygg-git-compare-next-hunk)
            (should (equal magit-buffer-diff-files '("a.txt")))
            (should (looking-at-p "@@"))
            (press #'ygg-git-compare-next-hunk)
            (should (equal magit-buffer-diff-files '("b.txt")))
            (should (looking-at-p "@@"))
            (should-error (press #'ygg-git-compare-next-hunk) :type 'user-error)
            (press #'ygg-git-compare-previous-hunk)
            (should (equal magit-buffer-diff-files '("a.txt")))
            (select-window (get-buffer-window list))
            (set-buffer list)
            (goto-char (point-min))
            (press #'ygg-git-compare-next-file)
            (should (equal (magit-file-at-point) "a.txt"))
            (press #'ygg-git-compare-next-file)
            (should (equal (magit-file-at-point) "b.txt"))))))))

(defun ygg-git-compare-comments-tests--meta (table)
  (cdr (funcall table "" nil 'metadata)))

(ert-deftest ygg-git-compare-comments-pickers-carry-metadata ()
  (ygg-git-compare-comments-tests--with-repo root
    (ygg-git-compare-comments-tests--with-compare root
      (ygg-git-compare-comments-tests--goto "+two")
      (ygg-git-compare-comments-tests--write (ygg-git-compare-comment) "mine")
      (ygg-git-compare-comments-receive root "feature"
                                        '((:file "a.txt" :line 2 :text "theirs" :type "nit"
                                           :priority 1))
                                        "claude")
      (let* ((rows (ygg-git-compare--comment-candidates (ygg-git-compare-comments-list t)))
             (table (ygg-git-compare-table rows 'ygg-review-comment))
             (meta (ygg-git-compare-comments-tests--meta table))
             (theirs (car (rassoc (seq-find (lambda (c) (plist-get c :author))
                                            (ygg-git-compare-comments-list t))
                                  rows))))
        (should (equal (all-completions "" table) '("mine" "theirs")))
        (should (eq (alist-get 'category meta) 'ygg-review-comment))
        (should (eq (alist-get 'display-sort-function meta) #'identity))
        (should (equal (funcall (alist-get 'group-function meta) (car (assoc "mine" rows)) nil)
                       "a.txt"))
        (should (equal (funcall (alist-get 'group-function meta) theirs nil) "Pending · claude"))
        (should (equal (substring-no-properties
                        (funcall (alist-get 'annotation-function meta) theirs))
                       "  [nit] P1 claude a.txt:2")))
      (let* ((rows (ygg-git-compare--priority-candidates))
             (meta (ygg-git-compare-comments-tests--meta
                    (ygg-git-compare-table rows 'ygg-review-priority))))
        (should (equal (mapcar #'car rows) '("all" "P0" "P1" "P2" "P3")))
        (should (eq (alist-get 'category meta) 'ygg-review-priority))
        (should (equal (substring-no-properties
                        (funcall (alist-get 'annotation-function meta) (car (nth 2 rows))))
                       "  1 comment"))
        (should (equal (substring-no-properties
                        (funcall (alist-get 'annotation-function meta) (caar rows)))
                       "  2 comments"))))))

(ert-deftest ygg-git-compare-comments-imenu-lists-files-hunks-and-comments ()
  (ygg-git-compare-comments-tests--with-repo root
    (ygg-git-compare-comments-tests--with-compare root
      (ygg-git-compare-comments-tests--goto "+two")
      (ygg-git-compare-comments-tests--write (ygg-git-compare-comment) "on two\nmore")
      (ygg-git-compare-comments-tests--goto "+b1")
      (ygg-git-compare-comments-tests--write (ygg-git-compare-comment-file) "on b")
      (let* ((index (funcall imenu-create-index-function))
             (a (cdr (assoc "a.txt" index)))
             (hunk (car a))
             (b (cdr (assoc "b.txt" index))))
        (should (equal (mapcar #'car index) '("a.txt" "b.txt")))
        (should (string-prefix-p "@@ -1,5 +1,5 @@" (car hunk)))
        (should (equal (mapcar #'car (cdr hunk)) (list (car hunk) "▎ on two")))
        (should (equal (car (car b)) "▎ on b"))
        (should (string-prefix-p "@@" (car (cadr b))))
        (magit-section-show-level-1-all)
        (goto-char (point-min))
        (imenu (assoc "▎ on two" (cdr hunk)))
        (should (looking-at-p "\\+two"))
        (should-not (invisible-p (point))))
      (let ((ygg-git-compare--file-window (selected-window)))
        (with-current-buffer (ygg-git-compare--show-file "a.txt")
          (let ((index (funcall imenu-create-index-function)))
            (should (equal (mapcar #'car index) '("a.txt")))
            (imenu (assoc "▎ on two" (cdr (cadr (car index)))))
            (should (looking-at-p "\\+two"))))))))

(ert-deftest ygg-git-compare-comments-draft-completes-types-paths-and-words ()
  (ygg-git-compare-comments-tests--with-repo root
    (ygg-git-compare-comments-tests--with-compare root
      (ygg-git-compare-comments-tests--goto "+two")
      (with-current-buffer (ygg-git-compare-comment)
        (should (equal (buffer-local-value 'corfu-auto-prefix (current-buffer)) 1))
        (should (memq #'ygg-git-compare-draft-type-capf completion-at-point-functions))
        (insert "ni")
        (pcase-let ((`(,beg ,end ,table . ,props) (ygg-git-compare-draft-type-capf)))
          (should (equal (all-completions (buffer-substring beg end) table) '("nit")))
          (should (eq (plist-get props :exclusive) 'no))
          (delete-region beg end)
          (insert "nit ")
          (funcall (plist-get props :exit-function) "nit" 'finished))
        (should (eq (plist-get ygg-git-compare--draft :type) 'nit))
        (should (equal (buffer-string) ""))
        (insert "see b.")
        (should-not (ygg-git-compare-draft-type-capf))
        (pcase-let ((`(,beg ,end ,table . ,props) (ygg-git-compare-draft-file-capf)))
          (should (equal (all-completions (buffer-substring beg end) table) '("b.txt")))
          (should (eq (alist-get 'category (cdr (funcall table "" nil 'metadata))) 'file))
          (should (eq (plist-get props :exclusive) 'no)))
        (insert "txt and thr")
        (pcase-let ((`(,beg ,end ,table . ,props) (ygg-git-compare-draft-word-capf)))
          (should (member "three" (all-completions (buffer-substring beg end) table)))
          (should (eq (plist-get props :exclusive) 'no)))
        (aob-compose-abort)))))

(ert-deftest ygg-git-compare-comments-selection-keys-end-with-the-selection ()
  (ygg-git-compare-comments-tests--with-repo root
    (ygg-git-compare-comments-tests--with-compare root
      (ygg-git-compare-comments-tests--goto " 1")
      (ygg-git-compare-select-lines)
      (ygg-git-compare-select-down)
      (let ((draft (ygg-git-compare-comment)))
        (with-current-buffer draft
          (should-not (eq (key-binding "j") #'ygg-git-compare-select-down))
          (should-not (eq (key-binding "C") #'ygg-git-compare-comment))
          (aob-compose-abort)))
      (ygg-git-compare-select-lines)
      (should (eq (key-binding "j") #'ygg-git-compare-select-down))
      (ygg-git-compare-select-lines)
      (should-not (eq (key-binding "j") #'ygg-git-compare-select-down))
      (should-not (eq (key-binding (kbd "<escape>")) #'ygg-git-compare-select-lines)))))

(defun ygg-git-compare-comments-tests--comment-command-p (def)
  (and (symbolp def)
       (string-prefix-p "ygg-git-compare-comment" (symbol-name def))
       (not (memq def '(ygg-git-compare-comment-next ygg-git-compare-comment-previous
                        ygg-git-compare-comment-copy ygg-git-compare-comment-accept ygg-git-compare-comment-moved
                        ygg-git-compare-comment-delete ygg-git-compare-comment-goto)))))

(ert-deftest ygg-git-compare-comments-capital-c-is-the-one-comment-key ()
  (ygg-git-compare-comments-tests--with-repo root
    (ygg-git-compare-comments-tests--with-compare root
      (run-hooks 'pre-command-hook)
      (dolist (at '("+two" "@@ -1" "b.txt"))
        (ygg-git-compare-comments-tests--goto at)
        (should (eq (key-binding "C" nil nil (point)) #'ygg-git-compare-comment))
        (dolist (key '("c" "i" "A" "K"))
          (should-not (ygg-git-compare-comments-tests--comment-command-p
                       (key-binding key nil nil (point))))))
      (ygg-git-compare-comments-tests--goto " 1")
      (ygg-git-compare-select-lines)
      (ygg-git-compare-select-down)
      (should (eq (key-binding "C") #'ygg-git-compare-comment))
      (should (eq (key-binding (kbd "RET")) #'ygg-git-compare-comment))
      (dolist (key '("c" "i" "A" "K"))
        (should-not (ygg-git-compare-comments-tests--comment-command-p (key-binding key))))
      (with-current-buffer (call-interactively (key-binding "C"))
        (should (eq (plist-get ygg-git-compare--draft :level) 'range))
        (aob-compose-abort)))))

(ert-deftest ygg-git-compare-comments-capital-c-on-a-file-heading-comments-on-the-file ()
  (ygg-git-compare-comments-tests--with-repo root
    (ygg-git-compare-comments-tests--with-compare root
      (ygg-git-compare-comments-tests--goto "b.txt")
      (ygg-git-compare-comments-tests--write (call-interactively (key-binding "C")) "whole file")
      (should (eq (plist-get (car (ygg-git-compare-comments-list)) :level) 'file)))))

(ert-deftest ygg-git-compare-comments-capital-c-edits-a-comment-and-saving-it-empty-deletes-it ()
  (ygg-git-compare-comments-tests--with-repo root
    (ygg-git-compare-comments-tests--with-compare root
      (ygg-git-compare-comments-tests--goto "+two")
      (ygg-git-compare-comments-tests--write (ygg-git-compare-comment) "mine")
      (let ((id (plist-get (car (ygg-git-compare-comments-list)) :id)))
        (with-current-buffer (call-interactively (key-binding "C"))
          (should (equal (buffer-string) "mine"))
          (erase-buffer)
          (insert "better")
          (aob-compose-send))
        (should (equal (mapcar (lambda (c) (list (plist-get c :id) (plist-get c :text)))
                               (ygg-git-compare-comments-list))
                       (list (list id "better"))))
        (with-current-buffer (call-interactively (key-binding "C"))
          (should (equal (buffer-string) "better"))
          (erase-buffer)
          (aob-compose-send))
        (should-not (ygg-git-compare-comments-list t))
        (should-not (string-search "better" (ygg-git-compare-comments-tests--shown)))))))

(ert-deftest ygg-git-compare-comments-an-empty-new-comment-is-refused ()
  (ygg-git-compare-comments-tests--with-repo root
    (ygg-git-compare-comments-tests--with-compare root
      (ygg-git-compare-comments-tests--goto "+two")
      (with-current-buffer (ygg-git-compare-comment)
        (should-error (aob-compose-send) :type 'user-error)
        (aob-compose-abort))
      (should-not (ygg-git-compare-comments-list t)))))

(ert-deftest ygg-git-compare-comments-summary-takes-capital-c-and-d-d ()
  (ygg-git-compare-comments-tests--with-repo root
    (ygg-git-compare-comments-tests--with-compare root
      (ygg-git-compare-comments-tests--goto "+two")
      (ygg-git-compare-comments-tests--write (ygg-git-compare-comment) "in a")
      (with-current-buffer (ygg-git-compare-comments-summary)
        (should (eq (key-binding "C") #'ygg-git-compare-comment))
        (should (eq (key-binding (kbd "d d")) #'ygg-git-compare-comment-delete))
        (should (eq (key-binding "A") #'ygg-git-compare-comments-accept-all))
        (should (eq (key-binding "a") #'ygg-git-compare-comment-accept))
        (dolist (key '("i" "K"))
          (should-not (ygg-git-compare-comments-tests--comment-command-p (key-binding key))))
        (should-not (eq (key-binding "K") #'ygg-git-compare-comment-delete))
        (goto-char (point-min))
        (search-forward "in a")
        (with-current-buffer (call-interactively (key-binding "C"))
          (should (equal (buffer-string) "in a"))
          (erase-buffer)
          (aob-compose-send))
        (should-not (ygg-git-compare-comments-list t))))))

(ert-deftest ygg-git-compare-comments-a-new-comment-box-is-its-own-compares ()
  (ygg-git-compare-comments-tests--with-repo root
    (let (first second)
      (ygg-git-compare-comments-tests--with-compare root
        (ygg-git-compare-comments-tests--goto "+two")
        (setq first (ygg-git-compare-comment)))
      (with-current-buffer (ygg-git-compare-buffer root '(rev . "main") '(rev . "feature"))
        (rename-buffer "second compare")
        (magit-section-show-level-4-all)
        (ygg-git-compare-comments-tests--goto "+two")
        (setq second (ygg-git-compare-comment)))
      (should-not (eq first second))
      (with-current-buffer first (aob-compose-abort))
      (with-current-buffer second (aob-compose-abort)))))

(ert-deftest ygg-git-compare-comments-a-box-on-a-deleted-comment-keeps-it-gone ()
  (ygg-git-compare-comments-tests--with-repo root
    (ygg-git-compare-comments-tests--with-compare root
      (ygg-git-compare-comments-tests--goto "+two")
      (ygg-git-compare-comments-tests--write (ygg-git-compare-comment) "mine")
      (let ((box (ygg-git-compare-comment)))
        (ygg-git-compare-comments-drop
         (mapcar (lambda (c) (plist-get c :id)) (ygg-git-compare-comments-list t)))
        (with-current-buffer box
          (erase-buffer)
          (insert "again")
          (should-error (aob-compose-send) :type 'user-error)
          (aob-compose-abort))
        (should-not (ygg-git-compare-comments-list t))))))

(ert-deftest ygg-git-compare-comments-ids-are-unique-within-a-millisecond ()
  (cl-letf (((symbol-function 'float-time) (lambda (&rest _) 1.0))
            ((symbol-function 'random) (lambda (&rest _) 5)))
    (let ((ids (cl-loop repeat 200 collect (ygg-git-compare--new-id))))
      (should (= (length (delete-dups (copy-sequence ids))) 200)))))

(ert-deftest ygg-git-compare-comments-of-another-range-are-not-drawn-on-a-line ()
  (ygg-git-compare-comments-tests--with-repo root
    (ygg-git-compare-comments-tests--with-compare root
      (ygg-git-compare-comments-tests--goto "+two")
      (ygg-git-compare-comments-tests--write (ygg-git-compare-comment) "on two" 'todo)
      (should-not (string-search "Made on another range"
                                 (ygg-git-compare-comments-tests--shown)))
      (ygg-git-compare-swap)
      (let ((shown (ygg-git-compare-comments-tests--shown)))
        (should (string-search "Made on another range" shown))
        (should (string-search "stale" shown))
        (should (string-search "on two" shown)))
      (should (equal (mapcar #'overlay-start
                             (seq-filter (lambda (ov) (overlay-get ov 'ygg-git-compare-comments))
                                         (overlays-in (point-min) (point-max))))
                     (list (point-min))))
      (with-current-buffer (ygg-git-compare-comments-summary)
        (should (string-search "Made on another range (1)" (buffer-string))))
      (should (string-search "made on" (ygg-git-compare-review-prompt)))
      (ygg-git-compare-swap)
      (should-not (string-search "Made on another range"
                                 (ygg-git-compare-comments-tests--shown))))))

(ert-deftest ygg-git-compare-comments-old-side-line-is-found-on-a-context-line ()
  (ygg-git-compare-comments-tests--with-repo root
    (ygg-git-compare-comments-tests--with-compare root
      (ygg-git-compare-comments-receive
       root "feature" '((:file "a.txt" :line 1 :side "old" :text "on context")) "claude")
      (let ((ov (seq-find (lambda (ov) (overlay-get ov 'ygg-git-compare-comments))
                          (overlays-in (point-min) (point-max)))))
        (should-not (string-search "removed line" (overlay-get ov 'after-string)))
        (goto-char (overlay-start ov))
        (should (looking-at-p " 1"))))))

(ert-deftest ygg-git-compare-comments-key-drops-a-remote-without-its-ref ()
  (ygg-git-compare-comments-tests--with-repo root
    (ygg-git-compare-comments-tests--git root "remote" "add" "origin" "git@example.invalid:o/r.git")
    (should (equal (ygg-git-compare--branch-review-key "origin/feature") "branch feature"))
    (should (equal (ygg-git-compare--branch-review-key "origin/topic/x") "branch topic/x"))
    (should (equal (ygg-git-compare--branch-review-key "feature") "branch feature"))
    (should (equal (ygg-git-compare--branch-review-key "topic/x") "branch topic/x"))))

(ert-deftest ygg-git-compare-comments-unreadable-store-is-kept-not-overwritten ()
  (ygg-git-compare-comments-tests--with-repo root
    (ygg-git-compare-comments-tests--with-compare root
      (let ((file (car ygg-git-compare--store)))
        (with-temp-file file (insert "((\"branch feature\" (:id"))
        (should-error (ygg-git-compare--put (list :id "x" :level 'review :text "t"))
                      :type 'user-error)
        (should (equal (with-temp-buffer (insert-file-contents file) (buffer-string))
                       "((\"branch feature\" (:id"))
        (should (directory-files (file-name-directory file) nil "\\.corrupt-"))))))

(ert-deftest ygg-git-compare-comments-store-is-replaced-whole ()
  (ygg-git-compare-comments-tests--with-repo root
    (ygg-git-compare-comments-tests--with-compare root
      (ygg-git-compare--put (list :id "x" :level 'review :text "first"))
      (let ((file (car ygg-git-compare--store))
            (rename (symbol-function 'rename-file))
            seen)
        (cl-letf (((symbol-function 'rename-file)
                   (lambda (from to &rest args)
                     (push (list (file-name-directory from) (file-name-directory to)
                                 (with-temp-buffer (insert-file-contents to) (buffer-string)))
                           seen)
                     (apply rename from to args))))
          (ygg-git-compare--put (list :id "y" :level 'review :text "second")))
        (pcase-let ((`((,from-dir ,to-dir ,old)) seen))
          (should (equal from-dir to-dir))
          (should (string-search "first" old))
          (should-not (string-search "second" old)))
        (should (string-search "second" (with-temp-buffer (insert-file-contents file)
                                                          (buffer-string))))))))

(ert-deftest ygg-git-compare-comments-agent-types-are-not-forge ()
  (should-not (ygg-git-compare--forge-p '(:type todo)))
  (should-not (ygg-git-compare--forge-p '(:type fix))))

(ert-deftest ygg-git-compare-comments-other-types-and-untyped-are-forge ()
  (should (ygg-git-compare--forge-p '(:type nit)))
  (should (ygg-git-compare--forge-p '(:type nil)))
  (should (ygg-git-compare--forge-p '(:text "plain"))))

(ert-deftest ygg-git-compare-comments-stored-destination-is-ignored ()
  (should (ygg-git-compare--forge-p '(:to agent :type nit)))
  (should-not (ygg-git-compare--forge-p '(:to forge :type todo))))

(ert-deftest ygg-git-compare-comments-agent-types-are-selectable ()
  (let ((types (ygg-git-compare-comment-types)))
    (dolist (type (append ygg-git-compare-comment-types ygg-git-compare-agent-types))
      (should (memq type types)))
    (should (equal types (delete-dups (copy-sequence types))))
    (should (equal (ygg-git-compare--next-type 'praise 1) 'todo))))

(ert-deftest ygg-git-compare-comments-received-type-is-downcased ()
  (let ((received (ygg-git-compare--received '(:type "Fix" :text "x") "claude")))
    (should (eq (plist-get received :type) 'fix))
    (should-not (ygg-git-compare--forge-p received))))

(ert-deftest ygg-git-compare-comments-received-symbol-types-are-downcased ()
  (let ((types (mapcar (lambda (type)
                         (ygg-git-compare--received (list :type type :text "x") "claude"))
                       '(Fix FIX Todo Nit))))
    (should (equal (mapcar (lambda (c) (plist-get c :type)) types) '(fix fix todo nit)))
    (should-not (ygg-git-compare--forge-p (nth 0 types)))
    (should-not (ygg-git-compare--forge-p (nth 1 types)))
    (should-not (ygg-git-compare--forge-p (nth 2 types)))
    (should (ygg-git-compare--forge-p (nth 3 types)))))

(ert-deftest ygg-git-compare-comments-dispatch-description-follows-agent-types ()
  (should (equal (ygg-git-compare-comments--review-description) "agent review (+ todo, fix)"))
  (let ((ygg-git-compare-agent-types '(todo)))
    (should (equal (ygg-git-compare-comments--review-description) "agent review (+ todo)"))))

(ert-deftest ygg-git-compare-comments-toggle-destination-is-gone ()
  (should-not (fboundp 'ygg-git-compare-comment-toggle-destination)))

;;; ygg-git-compare-comments-tests.el ends here

(ert-deftest ygg-git-compare-comments-a-second-c-on-a-new-line-reuses-its-box ()
  (ygg-git-compare-comments-tests--with-repo root
    (ygg-git-compare-comments-tests--with-compare root
      (ygg-git-compare-comments-tests--goto "+two")
      (let ((box (ygg-git-compare-comment)))
        (with-current-buffer box (insert "typed"))
        (ygg-git-compare-comments-tests--goto "+two")
        (should (eq (ygg-git-compare-comment) box))
        (should (equal (with-current-buffer box (buffer-string)) "typed"))
        (ygg-git-compare-comments-tests--goto "+three")
        (should-not (eq (ygg-git-compare-comment) box))
        (aob-compose-abort)
        (with-current-buffer box (aob-compose-abort))))))

(ert-deftest ygg-git-compare-comments-a-second-c-on-an-edit-keeps-the-typed-words ()
  (ygg-git-compare-comments-tests--with-repo root
    (ygg-git-compare-comments-tests--with-compare root
      (ygg-git-compare-comments-tests--goto "+two")
      (ygg-git-compare-comments-tests--write (ygg-git-compare-comment) "first")
      (ygg-git-compare-comments-tests--goto "+two")
      (let ((box (ygg-git-compare-comment)))
        (with-current-buffer box (insert " more"))
        (should (eq (ygg-git-compare-comment) box))
        (should (equal (with-current-buffer box (buffer-string)) "first more"))
        (with-current-buffer box (aob-compose-abort))))))

(ert-deftest ygg-git-compare-comments-box-sends-its-words-as-typed ()
  (ygg-git-compare-comments-tests--with-repo root
    (ygg-git-compare-comments-tests--with-compare root
      (ygg-git-compare-comments-tests--goto "+two")
      (let ((aob-compose-history nil))
        (with-current-buffer (ygg-git-compare-comment)
          (insert "see #foo and [[Image1]]  ")
          (aob-compose-send))
        (should-not aob-compose-history)
        (should (equal (plist-get (car (ygg-git-compare-comments-list)) :text)
                       "see #foo and [[Image1]]"))))))

(ert-deftest ygg-git-compare-comments-summary-c-off-a-comment-says-so ()
  (ygg-git-compare-comments-tests--with-repo root
    (ygg-git-compare-comments-tests--with-compare root
      (with-current-buffer (ygg-git-compare-comments-summary)
        (let ((err (should-error (ygg-git-compare-comment) :type 'user-error)))
          (should (string-search "No comment here" (cadr err))))
        (should-not (seq-some (lambda (b) (string-prefix-p "compose:review:" (buffer-name b)))
                              (buffer-list)))))))

(ert-deftest ygg-git-compare-comments-block-names-its-audience ()
  (dolist (case '((todo . "agent") (fix . "agent") (nit . "PR") (issue . "PR") (nil . "PR")))
    (let ((block (substring-no-properties
                  (ygg-git-compare--comment-block (list :id "x" :type (car case) :text "body")))))
      (should (string-match-p (format "\\(^\\|[] ]\\)%s\\($\\| \\)" (cdr case))
                              (car (split-string block "\n"))))
      (should-not (string-match-p (if (equal (cdr case) "PR") "agent" "\\bPR\\b")
                                  (car (split-string block "\n")))))))

(ert-deftest ygg-git-compare-comments-draft-says-where-it-goes ()
  (ygg-git-compare-comments-tests--with-repo root
    (ygg-git-compare-comments-tests--with-compare root
      (ygg-git-compare-comments-tests--goto "+two")
      (with-current-buffer (ygg-git-compare-comment)
        (should (member "to PR" aob-compose--tags))
        (ygg-git-compare-draft-cycle-type-back)
        (should (member "[fix]" aob-compose--tags))
        (should (member "to agent" aob-compose--tags))
        (should-not (member "to PR" aob-compose--tags))
        (ygg-git-compare-draft-cycle-type)
        (ygg-git-compare-draft-cycle-type)
        (should (member "[issue]" aob-compose--tags))
        (should (member "to PR" aob-compose--tags))))))
