;;; ygg-project-setup-tests.el --- Tests for per-project toolchain setup -*- lexical-binding: t; -*-

(require 'ert)
(require 'cl-lib)
(require 'ygg-project-setup)

(defvar ygg-project-setup-tests--started nil)
(defvar ygg-project-setup-tests--exes '("mise" "brew" "corepack"))
(defvar ygg-project-setup-tests--missing "")
(defvar ygg-project-setup-tests--bundle-ok nil)
(defvar ygg-project-setup-tests--answer "y")
(defvar ygg-project-setup-tests--asked nil)

(defmacro ygg-project-setup-tests--with (files &rest body)
  "Run BODY in a temp project holding FILES, with every process and prompt stubbed."
  (declare (indent 1))
  `(let* ((root (file-name-as-directory (make-temp-file "ygg-setup" t)))
          (ygg-project-setup-never-file (expand-file-name "var/never.eld" root))
          (ygg-project-setup--seen (make-hash-table :test #'equal))
          (ygg-project-setup-tools 'ask)
          (ygg-project-setup-tests--started nil)
          (ygg-project-setup-tests--asked nil)
          (ygg-project-setup-tests--answer "y"))
     (unwind-protect
         (progn
           (dolist (f ,files)
             (with-temp-file (expand-file-name (car f) root) (insert (cdr f))))
           (cl-letf (((symbol-function 'executable-find)
                      (lambda (n &rest _) (car (member n ygg-project-setup-tests--exes))))
                     ((symbol-function 'call-process)
                      (lambda (prog _in dest _disp &rest args)
                        (cond ((equal args '("ls" "--missing"))
                               (insert ygg-project-setup-tests--missing) 0)
                              ((equal (cons prog args) '("brew" "bundle" "check" "--file=Brewfile"))
                               (if ygg-project-setup-tests--bundle-ok 0 1))
                              (t 1))))
                     ((symbol-function 'make-process)
                      (lambda (&rest plist)
                        (push (plist-get plist :command) ygg-project-setup-tests--started)
                        (let ((proc (make-symbol "p")))
                          (funcall (plist-get plist :sentinel) proc "finished\n")
                          proc)))
                     ((symbol-function 'process-status) (lambda (_) 'exit))
                     ((symbol-function 'process-exit-status) (lambda (_) 0))
                     ((symbol-function 'run-with-idle-timer)
                      (lambda (_s _r f &rest a) (apply f a)))
                     ((symbol-function 'completing-read)
                      (lambda (prompt &rest _)
                        (push prompt ygg-project-setup-tests--asked)
                        ygg-project-setup-tests--answer))
                     ((symbol-function 'ygg-notify) #'ignore))
             ,@body))
       (delete-directory root t)
       (kill-matching-buffers "\\`\\*setup: ygg-setup" t t))))

(defun ygg-project-setup-tests--labels (root)
  (mapcar #'car (car (ygg-project-setup--plan root))))

(ert-deftest ygg-project-setup-mise-config-runs-mise-install ()
  (dolist (name '("mise.toml" ".mise.toml" ".tool-versions"))
    (ygg-project-setup-tests--with (list (cons name ""))
      (setq ygg-project-setup-tests--missing "node 22 missing\n")
      (should (equal (cadr (car (car (ygg-project-setup--plan root))))
                     '("mise" "install"))))))

(ert-deftest ygg-project-setup-brewfile-runs-brew-bundle-with-the-file-as-an-argument ()
  (ygg-project-setup-tests--with (list (cons "Brewfile" ""))
    (setq ygg-project-setup-tests--bundle-ok nil)
    (should (equal (cadr (car (car (ygg-project-setup--plan root))))
                   '("brew" "bundle" "--file=Brewfile")))))

(ert-deftest ygg-project-setup-satisfied-steps-run-nothing ()
  (ygg-project-setup-tests--with (list (cons "mise.toml" "") (cons "Brewfile" ""))
    (setq ygg-project-setup-tests--missing "  \n" ygg-project-setup-tests--bundle-ok t)
    (should-not (car (ygg-project-setup--plan root)))
    (ygg-project-setup root)
    (should-not ygg-project-setup-tests--started)
    (ygg-project-setup-offer root)
    (should-not ygg-project-setup-tests--asked)))

(ert-deftest ygg-project-setup-version-files-only-note-when-mise-is-absent-from-the-project ()
  (ygg-project-setup-tests--with (list (cons ".nvmrc" "22"))
    (let ((plan (ygg-project-setup--plan root)))
      (should-not (car plan))
      (should (string-match-p "\\.nvmrc: covered by mise if you add it" (car (cdr plan))))))
  (ygg-project-setup-tests--with (list (cons ".nvmrc" "22") (cons "mise.toml" ""))
    (should-not (cdr (ygg-project-setup--plan root)))))

(ert-deftest ygg-project-setup-package-manager-enables-corepack-until-it-is-on-path ()
  (ygg-project-setup-tests--with (list (cons "package.json" "{\"packageManager\":\"pnpm@9.1.0\"}"))
    (should (equal (ygg-project-setup-tests--labels root) '("corepack enable")))
    (setq ygg-project-setup-tests--exes '("mise" "brew" "corepack" "pnpm"))
    (unwind-protect (should-not (car (ygg-project-setup--plan root)))
      (setq ygg-project-setup-tests--exes '("mise" "brew" "corepack")))))

(ert-deftest ygg-project-setup-missing-executable-is-skipped-with-a-note ()
  (ygg-project-setup-tests--with (list (cons "mise.toml" "") (cons "Brewfile" ""))
    (let ((ygg-project-setup-tests--exes '("brew")))
      (let ((plan (ygg-project-setup--plan root)))
        (should (equal (mapcar #'car (car plan)) '("brew bundle")))
        (should (equal (cdr plan) '("mise install: mise not found, skipped")))))))

(ert-deftest ygg-project-setup-ask-yes-runs-every-step-as-argv-lists-in-order ()
  (ygg-project-setup-tests--with (list (cons "mise.toml" "") (cons "Brewfile" ""))
    (setq ygg-project-setup-tests--missing "node\n")
    (ygg-project-setup-offer root)
    (should (= 1 (length ygg-project-setup-tests--asked)))
    (should (string-match-p "mise install, brew bundle" (car ygg-project-setup-tests--asked)))
    (should (equal (reverse ygg-project-setup-tests--started)
                   '(("mise" "install") ("brew" "bundle" "--file=Brewfile"))))))

(ert-deftest ygg-project-setup-ask-no-runs-nothing-and-asks-again-next-session ()
  (ygg-project-setup-tests--with (list (cons "mise.toml" ""))
    (setq ygg-project-setup-tests--missing "node\n" ygg-project-setup-tests--answer "n")
    (ygg-project-setup-offer root)
    (should-not ygg-project-setup-tests--started)
    (should-not (file-exists-p ygg-project-setup-never-file))
    (clrhash ygg-project-setup--seen)
    (ygg-project-setup-offer root)
    (should (= 2 (length ygg-project-setup-tests--asked)))))

(ert-deftest ygg-project-setup-ask-never-is-remembered-in-the-file ()
  (ygg-project-setup-tests--with (list (cons "mise.toml" ""))
    (setq ygg-project-setup-tests--missing "node\n" ygg-project-setup-tests--answer "never")
    (ygg-project-setup-offer root)
    (should-not ygg-project-setup-tests--started)
    (should (equal (ygg-project-setup--never) (list root)))
    (clrhash ygg-project-setup--seen)
    (ygg-project-setup-offer root)
    (should (= 1 (length ygg-project-setup-tests--asked)))))

(ert-deftest ygg-project-setup-offer-fires-once-per-project ()
  (ygg-project-setup-tests--with (list (cons "mise.toml" ""))
    (setq ygg-project-setup-tests--missing "node\n")
    (ygg-project-setup-offer root)
    (ygg-project-setup-offer root)
    (should (= 1 (length ygg-project-setup-tests--asked)))))

(ert-deftest ygg-project-setup-modes-always-and-never ()
  (ygg-project-setup-tests--with (list (cons "mise.toml" ""))
    (setq ygg-project-setup-tests--missing "node\n")
    (let ((ygg-project-setup-tools 'never))
      (ygg-project-setup-offer root)
      (should-not ygg-project-setup-tests--started))
    (let ((ygg-project-setup-tools 'always))
      (ygg-project-setup-offer root)
      (should-not ygg-project-setup-tests--asked)
      (should (equal ygg-project-setup-tests--started '(("mise" "install")))))))

(ert-deftest ygg-project-setup-command-runs-without-asking ()
  (ygg-project-setup-tests--with (list (cons "mise.toml" ""))
    (setq ygg-project-setup-tests--missing "node\n")
    (ygg-project-setup root)
    (should-not ygg-project-setup-tests--asked)
    (should (equal ygg-project-setup-tests--started '(("mise" "install"))))))

(ert-deftest ygg-project-setup-trigger-is-on-add-and-not-on-adding-again ()
  (ygg-project-setup-tests--with (list (cons "mise.toml" ""))
    (setq ygg-project-setup-tests--missing "node\n")
    (require 'ygg-project-scan)
    (cl-letf (((symbol-function 'ygg-project-import) #'ignore)
              ((symbol-function 'project-remember-project) #'ignore)
              ((symbol-function 'project-current) (lambda (&rest _) (cons 'vc root))))
      (ygg-project-add root)
      (ygg-project-add root))
    (should (= 1 (length ygg-project-setup-tests--asked)))))
