;;; ygg-agent-maps-tests.el --- the maps a fresh agent chat is handed -*- lexical-binding: t; -*-

;;; Code:

(require 'ert)
(require 'cl-lib)
(require 'aob)
(require 'aob-acp)
(require 'ygg-agent-maps)

(defvar ygg-agent-maps-tests--calls nil)
(defvar ygg-agent-maps-tests--head "aaa")
(defvar ygg-agent-maps-tests--dirty nil)
(defvar ygg-agent-maps-tests--filter t)
(defvar ygg-agent-maps-tests--hang nil)
(defvar ygg-agent-maps-tests--held nil)
(defvar ygg-agent-maps-tests--attr t)
(defvar ygg-agent-maps-tests--toplevel t)
(defvar ygg-agent-maps-tests--hold-summary nil)
(defvar ygg-agent-maps-tests--held-summary nil)

(defconst ygg-agent-maps-tests--marker "<!-- ice-repo-map:generated -->")

(defun ygg-agent-maps-tests--runner (dir argv done &optional _merge)
  (push argv ygg-agent-maps-tests--calls)
  (if ygg-agent-maps-tests--hang
      (push done ygg-agent-maps-tests--held)
    (let ((cmd (file-name-nondirectory (car argv))))
      (cond
       ((and (equal cmd "git") (member "status" argv))
        (funcall done 0 (concat "# branch.oid " ygg-agent-maps-tests--head "\0"
                                (cond ((stringp ygg-agent-maps-tests--dirty)
                                       ygg-agent-maps-tests--dirty)
                                      (ygg-agent-maps-tests--dirty
                                       "1 .M N... 100644 100644 100644 a b x\0")))))
       ((and (equal cmd "git") (member "rev-parse" argv))
        (cond ((stringp ygg-agent-maps-tests--toplevel)
               (funcall done 0 (concat ygg-agent-maps-tests--toplevel "\n")))
              (ygg-agent-maps-tests--toplevel
               (funcall done 0 (concat (directory-file-name dir) "\n")))
              (t (funcall done 128 ""))))
       ((and (equal cmd "git") (member "check-attr" argv))
        (if ygg-agent-maps-tests--attr
            (funcall done 0 "lat.md/lat.md: filter: latgen\n")
          (funcall done 0 "lat.md/lat.md: filter: unspecified\n")))
       ((and (equal cmd "git") (member "config" argv))
        (pcase ygg-agent-maps-tests--filter
          ('old (funcall done 0 "grep -v GENERATED\n"))
          ('nil (funcall done 1 ""))
          (_ (funcall done 0 (format "grep -vF '%s' || true\n"
                                     ygg-agent-maps-tests--marker)))))
       ((equal cmd "ice-repo-map")
        (funcall done 0 (if (member "--write" argv) "" "MAP-BODY\n")))
       ((and (equal cmd "ice-feature-summary") ygg-agent-maps-tests--hold-summary)
        (push done ygg-agent-maps-tests--held-summary))
       ((equal cmd "ice-feature-summary")
        (funcall done 0 "- Feature A: lead\nDetails: query lat_search on [[features]].\n"))
       (t (funcall done 1 ""))))))

(defun ygg-agent-maps-tests--calls-of (name &optional flag)
  (cl-count-if (lambda (argv)
                 (and (equal (file-name-nondirectory (car argv)) name)
                      (if flag (member flag argv) (not (member "--write" argv)))))
               ygg-agent-maps-tests--calls))

(defmacro ygg-agent-maps-tests--with (lat &rest body)
  "Run BODY in a temp git repo whose lat.md holds the files LAT names."
  (declare (indent 1))
  `(let* ((root (file-name-as-directory (file-truename (make-temp-file "ygg-maps-" t))))
          (tools (file-name-as-directory (make-temp-file "ygg-maps-tools-" t)))
          (ygg-agent-maps-tools-dir tools)
          (ygg-agent-maps-interpreter nil)
          (ygg-agent-maps-enabled t)
          (ygg-agent-maps-wait 0.3)
          (ygg-agent-maps-project-budgets nil)
          (ygg-agent-maps--cache (make-hash-table :test #'equal))
          (ygg-agent-maps-tests--calls nil)
          (ygg-agent-maps-tests--head "aaa")
          (ygg-agent-maps-tests--dirty nil)
          (ygg-agent-maps-tests--filter t)
          (ygg-agent-maps-tests--hang nil)
          (ygg-agent-maps-tests--held nil)
          (ygg-agent-maps-tests--attr t)
          (ygg-agent-maps-tests--toplevel t)
          (ygg-agent-maps-tests--hold-summary nil)
          (ygg-agent-maps-tests--held-summary nil))
     (unwind-protect
         (progn
           (with-temp-file (expand-file-name "ice-latgen-filter" tools)
             (insert "#!/bin/sh\nmarker='" ygg-agent-maps-tests--marker "'\n"))
           (with-temp-file (expand-file-name "x" root) (insert "x\n"))
           (dolist (tool '("ice-repo-map" "ice-feature-summary"))
             (let ((f (expand-file-name tool tools)))
               (with-temp-file f (insert "#!/bin/sh\n"))
               (set-file-modes f #o755)))
           (dolist (f ,lat)
             (let ((p (expand-file-name (concat "lat.md/" f) root)))
               (make-directory (file-name-directory p) t)
               (with-temp-file p (insert "x\n"))))
           (cl-letf (((symbol-function 'ygg-agent-maps--run)
                      #'ygg-agent-maps-tests--runner))
             ,@body))
       (delete-directory root t)
       (delete-directory tools t))))

(defun ygg-agent-maps-tests--session (root &rest props)
  (let ((s (aob-create-session :id (format "acp:maps:%s" (random 100000))
                               :backend 'acp :name "maps" :project root
                               :dir root :state 'idle :refs props)))
    s))

(defun ygg-agent-maps-tests--first-block (s)
  (plist-get (aob-acp--place-block s) :text))

(ert-deftest ygg-agent-maps-new-session-first-prompt-has-block ()
  (ygg-agent-maps-tests--with '("features.md" "repo-map.md")
    (let ((s (ygg-agent-maps-tests--session root)))
      (ygg-agent-maps-on-ready s)
      (let ((text (ygg-agent-maps-tests--first-block s)))
        (should (string-match-p "<project-maps>" text))
        (should (string-match-p "MAP-BODY" text))
        (should (string-match-p "Feature A: lead" text))
        (should (string-match-p "lat_search / lat_section on \\[\\[features\\]\\] and \\[\\[repo-map\\]\\]" text))
        (should (= 1 (with-temp-buffer
                       (insert text)
                       (how-many "lat_search" (point-min) (point-max))))))
      (aob-remove-session s))))

(ert-deftest ygg-agent-maps-second-prompt-has-no-block ()
  (ygg-agent-maps-tests--with '("features.md")
    (let ((s (ygg-agent-maps-tests--session root)))
      (ygg-agent-maps-on-ready s)
      (should (ygg-agent-maps-tests--first-block s))
      (aob-set-state s 'working)
      (aob-set-state s 'idle)
      (should-not (string-match-p "project-maps"
                                  (or (ygg-agent-maps-tests--first-block s) "")))
      (aob-remove-session s))))

(ert-deftest ygg-agent-maps-resume-and-fork-get-no-block ()
  (ygg-agent-maps-tests--with '("features.md")
    (dolist (props '((:restored-by load) (:cost-inherited t)))
      (let ((s (apply #'ygg-agent-maps-tests--session root props)))
        (ygg-agent-maps-on-ready s)
        (should-not (aob-session-ref s :maps-pending))
        (should-not (ygg-agent-maps-tests--first-block s))
        (aob-remove-session s)))
    (should-not ygg-agent-maps-tests--calls)))

(ert-deftest ygg-agent-maps-without-features-only-the-map ()
  (ygg-agent-maps-tests--with nil
    (let ((s (ygg-agent-maps-tests--session root)))
      (ygg-agent-maps-on-ready s)
      (let ((text (ygg-agent-maps-tests--first-block s)))
        (should (string-match-p "MAP-BODY" text))
        (should-not (string-match-p "<features>\\|lat_search" text)))
      (should (zerop (ygg-agent-maps-tests--calls-of "ice-feature-summary")))
      (aob-remove-session s))))

(ert-deftest ygg-agent-maps-no-tools-no-block ()
  (ygg-agent-maps-tests--with nil
    (let ((ygg-agent-maps-tools-dir "/nonexistent/"))
      (let ((s (ygg-agent-maps-tests--session root)))
        (ygg-agent-maps-on-ready s)
        (should-not (ygg-agent-maps-tests--first-block s))
        (aob-remove-session s)))))

(ert-deftest ygg-agent-maps-repo-map-line-only-when-node-exists ()
  (ygg-agent-maps-tests--with '("features.md")
    (let ((s (ygg-agent-maps-tests--session root)))
      (ygg-agent-maps-on-ready s)
      (let ((text (ygg-agent-maps-tests--first-block s)))
        (should (string-match-p "\\[\\[features\\]\\]" text))
        (should-not (string-match-p "\\[\\[repo-map\\]\\]" text)))
      (aob-remove-session s))))

(ert-deftest ygg-agent-maps-cold-cache-waits-only-the-bound-and-keeps-pending ()
  (ygg-agent-maps-tests--with '("features.md")
    (setq ygg-agent-maps-tests--hang t)
    (let ((s (ygg-agent-maps-tests--session root))
          (ygg-agent-maps-wait 0.2))
      (let ((start (float-time)))
        (ygg-agent-maps-on-ready s)
        (should (< (- (float-time) start) 0.1))
        (should-not (ygg-agent-maps-tests--first-block s))
        (should (< (- (float-time) start) 0.6))
        (should (aob-session-ref s :maps-pending)))
      (aob-remove-session s))))

(ert-deftest ygg-agent-maps-missed-first-prompt-arrives-with-the-second ()
  (ygg-agent-maps-tests--with '("features.md")
    (setq ygg-agent-maps-tests--hang t)
    (let ((s (ygg-agent-maps-tests--session root))
          (ygg-agent-maps-wait 0.05))
      (ygg-agent-maps-on-ready s)
      (should-not (ygg-agent-maps-tests--first-block s))
      (setq ygg-agent-maps-tests--hang nil)
      (funcall (car (last ygg-agent-maps-tests--held)) 0 "# branch.oid aaa\n")
      (should (string-match-p "MAP-BODY" (ygg-agent-maps-tests--first-block s)))
      (aob-set-state s 'working)
      (aob-set-state s 'idle)
      (should-not (ygg-agent-maps-tests--first-block s))
      (aob-remove-session s))))

(ert-deftest ygg-agent-maps-block-kept-until-the-first-prompt-succeeds ()
  (ygg-agent-maps-tests--with '("features.md")
    (let ((s (ygg-agent-maps-tests--session root)))
      (ygg-agent-maps-on-ready s)
      (should (string-match-p "MAP-BODY" (ygg-agent-maps-tests--first-block s)))
      (aob-set-state s 'working)
      (aob-session-put s :turn-error t)
      (aob-set-state s 'idle)
      (should (string-match-p "MAP-BODY" (ygg-agent-maps-tests--first-block s)))
      (aob-set-state s 'working)
      (aob-session-put s :turn-error nil)
      (aob-set-state s 'idle)
      (should-not (ygg-agent-maps-tests--first-block s))
      (aob-remove-session s))))

(ert-deftest ygg-agent-maps-warmed-when-the-session-is-created ()
  (ygg-agent-maps-tests--with '("features.md")
    (let ((s (ygg-agent-maps-tests--session root)))
      (should (= 1 (ygg-agent-maps-tests--calls-of "ice-repo-map")))
      (ygg-agent-maps-on-ready s)
      (should (= 1 (ygg-agent-maps-tests--calls-of "ice-repo-map")))
      (aob-remove-session s))))

(ert-deftest ygg-agent-maps-subagents-get-the-pointer-by-default ()
  (ygg-agent-maps-tests--with '("features.md")
    (let ((s (ygg-agent-maps-tests--session root :parent-session "p")))
      (ygg-agent-maps-on-ready s)
      (let ((text (ygg-agent-maps-tests--first-block s)))
        (should (string-match-p "lat_search" text))
        (should-not (string-match-p "MAP-BODY\\|<features>" text)))
      (should-not ygg-agent-maps-tests--calls)
      (aob-remove-session s))))

(ert-deftest ygg-agent-maps-subagents-full-or-nothing ()
  (ygg-agent-maps-tests--with '("features.md")
    (let ((ygg-agent-maps-subagents 'full)
          (s (ygg-agent-maps-tests--session root :parent-session "p")))
      (ygg-agent-maps-on-ready s)
      (should (string-match-p "MAP-BODY" (ygg-agent-maps-tests--first-block s)))
      (aob-remove-session s))
    (let ((ygg-agent-maps-subagents nil)
          (s (ygg-agent-maps-tests--session root :parent-session "p")))
      (ygg-agent-maps-on-ready s)
      (should-not (aob-session-ref s :maps-pending))
      (should-not (ygg-agent-maps-tests--first-block s))
      (aob-remove-session s))))

(ert-deftest ygg-agent-maps-remote-project-touches-no-file ()
  (ygg-agent-maps-tests--with '("features.md")
    (let* ((remote "/ssh:nowhere:/srv/proj/")
           (s (ygg-agent-maps-tests--session remote))
           (touched nil))
      (cl-letf (((symbol-function 'file-directory-p)
                 (lambda (&rest _) (push 'dir touched) nil))
                ((symbol-function 'file-readable-p)
                 (lambda (&rest _) (push 'readable touched) nil))
                ((symbol-function 'file-executable-p)
                 (lambda (&rest _) (push 'exec touched) nil))
                ((symbol-function 'file-attributes)
                 (lambda (&rest _) (push 'attrs touched) nil)))
        (ygg-agent-maps-on-ready s)
        (ygg-agent-maps-refresh remote)
        (ygg-agent-maps-warm s)
        (aob-session-put s :maps-pending t)
        (should-not (plist-get (ygg-agent-maps--place (lambda (_s) nil) s) :text))
        (should-not touched)
        (should-not ygg-agent-maps-tests--calls))
      (aob-remove-session s))))

(ert-deftest ygg-agent-maps-nested-waits-share-one-deadline ()
  (let* ((tools (file-name-as-directory (make-temp-file "ygg-maps-nest-tools-" t)))
         (roots (list (file-name-as-directory (file-truename (make-temp-file "ygg-maps-n1-" t)))
                      (file-name-as-directory (file-truename (make-temp-file "ygg-maps-n2-" t)))))
         (ygg-agent-maps-tools-dir tools)
         (ygg-agent-maps-interpreter nil)
         (ygg-agent-maps-wait 0.3)
         (ygg-agent-maps--cache (make-hash-table :test #'equal))
         (sessions nil)
         (timer nil))
    (unwind-protect
        (progn
          (dolist (tool '("ice-repo-map"))
            (let ((f (expand-file-name tool tools)))
              (with-temp-file f (insert "#!/bin/sh\nsleep 5\n"))
              (set-file-modes f #o755)))
          (dolist (r roots)
            (let ((default-directory r))
              (call-process "git" nil nil nil "init" "-q")
              (call-process "git" nil nil nil "-c" "user.name=t" "-c" "user.email=t@t"
                            "commit" "-q" "--allow-empty" "-m" "i"))
            (let ((s (ygg-agent-maps-tests--session r)))
              (push s sessions)
              (aob-session-put s :maps-pending t)))
          (let ((start (float-time)))
            (setq timer (run-at-time 0.1 nil
                                     (lambda ()
                                       (ygg-agent-maps--place (lambda (_s) nil) (cadr sessions)))))
            (ygg-agent-maps--place (lambda (_s) nil) (car sessions))
            (should (<= (- (float-time) start) 0.4))))
      (when timer (cancel-timer timer))
      (dolist (e (hash-table-values ygg-agent-maps--cache))
        (mapc #'delete-process (plist-get e :procs)))
      (dolist (s sessions) (aob-remove-session s))
      (dolist (r roots) (delete-directory r t))
      (delete-directory tools t))))

(ert-deftest ygg-agent-maps-repeated-edits-on-a-dirty-tree-regenerate ()
  (ygg-agent-maps-tests--with '("features.md")
    (setq ygg-agent-maps-tests--dirty t)
    (let ((file (expand-file-name "x" root)))
      (set-file-times file (seconds-to-time 1000))
      (ygg-agent-maps-refresh root)
      (should (= 1 (ygg-agent-maps-tests--calls-of "ice-repo-map")))
      (ygg-agent-maps-refresh root)
      (should (= 1 (ygg-agent-maps-tests--calls-of "ice-repo-map")))
      (set-file-times file (seconds-to-time 2000))
      (ygg-agent-maps-refresh root)
      (should (= 2 (ygg-agent-maps-tests--calls-of "ice-repo-map")))
      (set-file-times file (seconds-to-time 3000))
      (ygg-agent-maps-refresh root)
      (should (= 3 (ygg-agent-maps-tests--calls-of "ice-repo-map"))))))

(ert-deftest ygg-agent-maps-stale-cache-refreshes-once ()
  (ygg-agent-maps-tests--with '("features.md")
    (ygg-agent-maps-refresh root)
    (should (= 1 (ygg-agent-maps-tests--calls-of "ice-repo-map")))
    (ygg-agent-maps-refresh root)
    (should (= 1 (ygg-agent-maps-tests--calls-of "ice-repo-map")))
    (setq ygg-agent-maps-tests--head "bbb")
    (ygg-agent-maps-refresh root)
    (ygg-agent-maps-refresh root)
    (should (= 2 (ygg-agent-maps-tests--calls-of "ice-repo-map")))
    (setq ygg-agent-maps-tests--dirty t)
    (ygg-agent-maps-refresh root)
    (should (= 3 (ygg-agent-maps-tests--calls-of "ice-repo-map")))
    (should (= 1 (ygg-agent-maps-tests--calls-of "ice-feature-summary")))))

(ert-deftest ygg-agent-maps-refresh-in-flight-is-not-doubled ()
  (ygg-agent-maps-tests--with '("features.md")
    (setq ygg-agent-maps-tests--hang t)
    (ygg-agent-maps-refresh root)
    (ygg-agent-maps-refresh root)
    (should (= 1 (length ygg-agent-maps-tests--calls)))))

(ert-deftest ygg-agent-maps-write-only-with-the-filter ()
  (ygg-agent-maps-tests--with '("features.md")
    (setq ygg-agent-maps-tests--filter nil)
    (ygg-agent-maps-refresh root)
    (should (zerop (ygg-agent-maps-tests--calls-of "ice-repo-map" "--write")))
    (setq ygg-agent-maps-tests--filter 'old)
    (ygg-agent-maps-refresh root)
    (should (zerop (ygg-agent-maps-tests--calls-of "ice-repo-map" "--write")))
    (setq ygg-agent-maps-tests--filter t)
    (ygg-agent-maps-refresh root)
    (should (= 1 (ygg-agent-maps-tests--calls-of "ice-repo-map" "--write")))
    (ygg-agent-maps-refresh root)
    (should (= 1 (ygg-agent-maps-tests--calls-of "ice-repo-map" "--write")))))

(ert-deftest ygg-agent-maps-no-write-without-the-latgen-attribute ()
  (ygg-agent-maps-tests--with '("features.md")
    (setq ygg-agent-maps-tests--attr nil)
    (ygg-agent-maps-refresh root)
    (should (zerop (ygg-agent-maps-tests--calls-of "ice-repo-map" "--write")))
    (setq ygg-agent-maps-tests--attr t)
    (ygg-agent-maps-refresh root)
    (should (= 1 (ygg-agent-maps-tests--calls-of "ice-repo-map" "--write")))))

(ert-deftest ygg-agent-maps-partial-block-then-the-remainder-then-nothing ()
  (ygg-agent-maps-tests--with '("features.md")
    (setq ygg-agent-maps-tests--hold-summary t)
    (let ((s (ygg-agent-maps-tests--session root))
          (ygg-agent-maps-wait 0.05))
      (ygg-agent-maps-on-ready s)
      (let ((text (ygg-agent-maps-tests--first-block s)))
        (should (string-match-p "MAP-BODY" text))
        (should-not (string-match-p "<features>" text))
        (should (string-match-p "still generating" text)))
      (aob-set-state s 'working)
      (aob-set-state s 'idle)
      (should (equal '(map) (aob-session-ref s :maps-sent)))
      (should (aob-session-ref s :maps-pending))
      (funcall (car ygg-agent-maps-tests--held-summary) 0 "- Feature A: lead\n")
      (let ((text (ygg-agent-maps-tests--first-block s)))
        (should (string-match-p "<features>" text))
        (should-not (string-match-p "MAP-BODY\\|still generating" text)))
      (aob-set-state s 'working)
      (aob-set-state s 'idle)
      (should-not (aob-session-ref s :maps-pending))
      (should-not (ygg-agent-maps-tests--first-block s))
      (aob-remove-session s))))

(ert-deftest ygg-agent-maps-failed-prompt-resends-the-partial-block ()
  (ygg-agent-maps-tests--with '("features.md")
    (setq ygg-agent-maps-tests--hold-summary t)
    (let ((s (ygg-agent-maps-tests--session root))
          (ygg-agent-maps-wait 0.05))
      (ygg-agent-maps-on-ready s)
      (should (string-match-p "MAP-BODY" (ygg-agent-maps-tests--first-block s)))
      (aob-set-state s 'working)
      (aob-session-put s :turn-error t)
      (aob-set-state s 'idle)
      (should-not (aob-session-ref s :maps-sent))
      (should (string-match-p "MAP-BODY" (ygg-agent-maps-tests--first-block s)))
      (aob-remove-session s))))

(ert-deftest ygg-agent-maps-dirty-paths-with-spaces-and-renames-are-statted ()
  (ygg-agent-maps-tests--with '("features.md")
    (let ((file (expand-file-name "sp ace.txt" root)))
      (with-temp-file file (insert "a\n"))
      (setq ygg-agent-maps-tests--dirty
            "1 .M N... 100644 100644 100644 a b sp ace.txt\0")
      (set-file-times file (seconds-to-time 1000))
      (ygg-agent-maps-refresh root)
      (should (= 1 (ygg-agent-maps-tests--calls-of "ice-repo-map")))
      (set-file-times file (seconds-to-time 2000))
      (ygg-agent-maps-refresh root)
      (should (= 2 (ygg-agent-maps-tests--calls-of "ice-repo-map")))
      (let ((statted nil))
        (cl-letf (((symbol-function 'ygg-agent-maps--mtime)
                   (lambda (f) (push (file-name-nondirectory f) statted) 1.0)))
          (setq ygg-agent-maps-tests--dirty
                "2 R. N... 100644 100644 100644 a b R100 new name.txt\0old name.txt\0u UU N... 1 2 3 4 a b c merged f.txt\0")
          (ygg-agent-maps--state root (concat "# branch.oid a\0" ygg-agent-maps-tests--dirty)))
        (should (equal '("merged f.txt" "new name.txt") (sort statted #'string<)))))))

(ert-deftest ygg-agent-maps-dirty-stat-work-is-capped ()
  (ygg-agent-maps-tests--with nil
    (let* ((n (* 3 ygg-agent-maps--stat-cap))
           (records (cl-loop for i below n
                             concat (format "1 .M N... 100644 100644 100644 a b f%d\0" i)))
           (statted 0))
      (cl-letf (((symbol-function 'ygg-agent-maps--mtime)
                 (lambda (_f) (cl-incf statted) 1.0)))
        (let ((a (ygg-agent-maps--state root (concat "# branch.oid a\0" records)))
              (b (ygg-agent-maps--state root (concat "# branch.oid a\0" records
                                                      "1 .M N... 100644 100644 100644 a b extra\0"))))
          (should (= statted (* 2 ygg-agent-maps--stat-cap)))
          (should-not (equal (cadr a) (cadr b))))))))

(ert-deftest ygg-agent-maps-no-write-without-lat-dir ()
  (ygg-agent-maps-tests--with nil
    (delete-directory (expand-file-name "lat.md" root) t)
    (ygg-agent-maps-refresh root)
    (should (zerop (ygg-agent-maps-tests--calls-of "ice-repo-map" "--write")))
    (should (= 1 (ygg-agent-maps-tests--calls-of "ice-repo-map")))))

(ert-deftest ygg-agent-maps-off-switch ()
  (ygg-agent-maps-tests--with '("features.md")
    (let* ((ygg-agent-maps-enabled nil)
           (s (ygg-agent-maps-tests--session root)))
      (ygg-agent-maps-on-ready s)
      (should-not ygg-agent-maps-tests--calls)
      (should-not (ygg-agent-maps-tests--first-block s))
      (aob-remove-session s))))

(ert-deftest ygg-agent-maps-budgets-per-project ()
  (ygg-agent-maps-tests--with '("features.md")
    (setq ygg-agent-maps-project-budgets (list (list root :map 500 :summary 90)))
    (ygg-agent-maps-refresh root)
    (let ((argvs ygg-agent-maps-tests--calls))
      (should (cl-some (lambda (a) (and (equal (file-name-nondirectory (car a)) "ice-repo-map")
                                        (member "500" a)))
                       argvs))
      (should (cl-some (lambda (a) (and (equal (file-name-nondirectory (car a))
                                               "ice-feature-summary")
                                        (member "90" a)))
                       argvs)))))

(ert-deftest ygg-agent-maps-placed-with-the-place-note ()
  (ygg-agent-maps-tests--with '("features.md")
    (let ((s (ygg-agent-maps-tests--session root)))
      (ygg-agent-maps-on-ready s)
      (let ((text (plist-get (ygg-agent-maps--place
                              (lambda (_s) (list :type "text" :text "PLACE"))
                              s)
                             :text)))
        (should (string-prefix-p "PLACE\n\n<project-maps>" text)))
      (aob-remove-session s))))

(ert-deftest ygg-agent-maps-real-processes-end-to-end ()
  (let* ((root (file-name-as-directory (file-truename (make-temp-file "ygg-maps-e2e-" t))))
         (tools (file-name-as-directory (make-temp-file "ygg-maps-e2e-tools-" t)))
         (ygg-agent-maps-tools-dir tools)
         (ygg-agent-maps-interpreter nil)
         (ygg-agent-maps-wait 3)
         (ygg-agent-maps--cache (make-hash-table :test #'equal)))
    (unwind-protect
        (progn
          (dolist (spec '(("ice-repo-map" . "echo REAL-MAP")
                          ("ice-feature-summary" . "echo '- F: x'")))
            (let ((f (expand-file-name (car spec) tools)))
              (with-temp-file f (insert "#!/bin/sh\n" (cdr spec) "\n"))
              (set-file-modes f #o755)))
          (make-directory (expand-file-name "lat.md" root))
          (with-temp-file (expand-file-name "lat.md/features.md" root) (insert "x\n"))
          (let ((default-directory root))
            (call-process "git" nil nil nil "init" "-q")
            (call-process "git" nil nil nil "-c" "user.name=t" "-c" "user.email=t@t"
                          "commit" "-q" "--allow-empty" "-m" "i"))
          (let ((s (ygg-agent-maps-tests--session root)))
            (ygg-agent-maps-on-ready s)
            (let ((text (ygg-agent-maps-tests--first-block s)))
              (should (string-match-p "REAL-MAP" text))
              (should (string-match-p "- F: x" text)))
            (aob-remove-session s)))
      (delete-directory root t)
      (delete-directory tools t))))

(defvar ygg-agent-maps-tests--spawned nil)

(defmacro ygg-agent-maps-tests--stubbed (&rest body)
  `(let ((ygg-agent-maps-tests--spawned nil)
         (messages nil))
     (cl-letf (((symbol-function 'aob-acp-spawn)
                (lambda (agent prompt &rest _)
                  (push (list agent prompt) ygg-agent-maps-tests--spawned)
                  'session))
               ((symbol-function 'message)
                (lambda (fmt &rest args) (push (apply #'format fmt args) messages))))
       ,@body)))

(ert-deftest ygg-agent-maps-generate-forces-when-fresh ()
  (ygg-agent-maps-tests--with '("features.md")
    (ygg-agent-maps-tests--stubbed
     (ygg-agent-maps-refresh root)
     (should (= 1 (ygg-agent-maps-tests--calls-of "ice-repo-map")))
     (ygg-agent-maps-generate root)
     (should (= 2 (ygg-agent-maps-tests--calls-of "ice-repo-map")))
     (should (= 2 (ygg-agent-maps-tests--calls-of "ice-feature-summary")))
     (should (= 2 (ygg-agent-maps-tests--calls-of "ice-repo-map" "--write")))
     (should (cl-some (lambda (m) (string-match-p "repo map ~.* tokens.*full map written" m))
                      messages)))))

(ert-deftest ygg-agent-maps-generate-without-filter-declined-writes-condensed-only ()
  (ygg-agent-maps-tests--with '("features.md")
    (ygg-agent-maps-tests--stubbed
     (let ((ygg-agent-maps-tests--filter nil) asked)
       (set-file-modes (expand-file-name "ice-latgen-filter" tools) #o755)
       (cl-letf (((symbol-function 'y-or-n-p)
                  (lambda (prompt) (setq asked prompt) nil)))
         (ygg-agent-maps-generate root))
       (should (string-match-p "\.gitattributes" asked))
       (should (string-match-p "filter\.latgen" asked))
       (should (= 1 (ygg-agent-maps-tests--calls-of "ice-repo-map")))
       (should (= 0 (ygg-agent-maps-tests--calls-of "ice-repo-map" "--write")))
       (should (cl-some (lambda (m) (string-match-p "not written: git filter latgen" m))
                        messages))))))

(ert-deftest ygg-agent-maps-generate-without-filter-accepted-installs ()
  (ygg-agent-maps-tests--with '("features.md")
    (ygg-agent-maps-tests--stubbed
     (let ((ygg-agent-maps-tests--filter nil) installed)
       (set-file-modes (expand-file-name "ice-latgen-filter" tools) #o755)
       (cl-letf (((symbol-function 'y-or-n-p) (lambda (_) t))
                 ((symbol-function 'ygg-agent-maps--run)
                  (lambda (dir argv done &optional merge)
                    (if (equal (file-name-nondirectory (car argv)) "ice-latgen-filter")
                        (progn (setq installed t
                                     ygg-agent-maps-tests--filter t)
                               (funcall done 0 "set\n"))
                      (ygg-agent-maps-tests--runner dir argv done merge)))))
         (ygg-agent-maps-generate root))
       (should installed)
       (should (= 1 (ygg-agent-maps-tests--calls-of "ice-repo-map" "--write")))))))

(ert-deftest ygg-agent-maps-generate-starts-feature-session-by-features-md ()
  (ygg-agent-maps-tests--with '("features.md")
    (ygg-agent-maps-tests--stubbed
     (ygg-agent-maps-generate root)
     (should (string-match-p "maintain-verification-skill"
                             (cadr (car ygg-agent-maps-tests--spawned))))))
  (ygg-agent-maps-tests--with '()
    (ygg-agent-maps-tests--stubbed
     (ygg-agent-maps-generate root)
     (should (string-match-p "create-verification-skill"
                             (cadr (car ygg-agent-maps-tests--spawned)))))))

(ert-deftest ygg-agent-maps-generate-live-session-skips-agent-only ()
  (ygg-agent-maps-tests--with '("features.md")
    (ygg-agent-maps-tests--stubbed
     (let* ((s (ygg-agent-maps-tests--session root))
            (before (ygg-agent-maps-tests--calls-of "ice-repo-map")))
       (ygg-agent-maps-generate root)
       (should-not ygg-agent-maps-tests--spawned)
       (should (= (1+ before) (ygg-agent-maps-tests--calls-of "ice-repo-map")))
       (should (cl-some (lambda (m) (string-match-p "skipped: 1 live" m)) messages))
       (should-error (ygg-agent-maps-features root) :type 'user-error)
       (aob-remove-session s)))))

(ert-deftest ygg-agent-maps-generate-asks-before-the-feature-agent-starts ()
  (ygg-agent-maps-tests--with '("features.md")
    (let ((ygg-agent-maps-tests--filter nil) order)
      (set-file-modes (expand-file-name "ice-latgen-filter" tools) #o755)
      (cl-letf (((symbol-function 'aob-acp-spawn)
                 (lambda (&rest _) (push 'spawn order) 'session))
                ((symbol-function 'message) #'ignore)
                ((symbol-function 'y-or-n-p) (lambda (_) (push 'ask order) nil)))
        (ygg-agent-maps-generate root))
      (should (equal '(ask spawn) (reverse order))))))

(ert-deftest ygg-agent-maps-generate-install-counts-as-pending-and-reports-stderr ()
  (ygg-agent-maps-tests--with '("features.md")
    (ygg-agent-maps-tests--stubbed
     (let ((ygg-agent-maps-tests--filter nil) during)
       (set-file-modes (expand-file-name "ice-latgen-filter" tools) #o755)
       (cl-letf (((symbol-function 'y-or-n-p) (lambda (_) t))
                 ((symbol-function 'ygg-agent-maps--run)
                  (lambda (dir argv done &optional merge)
                    (if (equal (file-name-nondirectory (car argv)) "ice-latgen-filter")
                        (progn
                          (setq during (plist-get (ygg-agent-maps--entry root) :pending))
                          (should merge)
                          (funcall done 1 "boom: no .git\nmore\n"))
                      (ygg-agent-maps-tests--runner dir argv done merge)))))
         (ygg-agent-maps-generate root))
       (should (> during 0))
       (should (cl-some (lambda (m) (string-match-p "install failed: boom: no \\.git$" m))
                        messages))))))

(ert-deftest ygg-agent-maps-generate-no-install-offer-outside-git-toplevel ()
  (dolist (case '((nil . "not a git repo") ("/elsewhere" . "not at the git toplevel")))
    (ygg-agent-maps-tests--with '("features.md")
      (ygg-agent-maps-tests--stubbed
       (let ((ygg-agent-maps-tests--filter nil)
             (ygg-agent-maps-tests--toplevel (car case)) asked)
         (set-file-modes (expand-file-name "ice-latgen-filter" tools) #o755)
         (cl-letf (((symbol-function 'y-or-n-p) (lambda (_) (setq asked t) t)))
           (ygg-agent-maps-generate root))
         (should-not asked)
         (should (cl-some (lambda (m) (string-match-p (regexp-quote (cdr case)) m))
                          messages)))))))

(defconst ygg-agent-maps-tests--claude-md-off
  "provider: gemini\neditor_files:\n  claude_md: false\nhooks:\n  x: true\n")

(defmacro ygg-agent-maps-tests--with-repowise (exit repowise-dir &rest body)
  "Run BODY with a fake repowise exiting EXIT; REPOWISE-DIR non-nil adds .repowise; a string is its config.yaml."
  (declare (indent 2))
  `(ygg-agent-maps-tests--with '("features.md")
     (ygg-agent-maps-tests--stubbed
      (let* ((bin (file-name-as-directory (make-temp-file "ygg-maps-bin-" t)))
             (rec (expand-file-name "rec" bin))
             (exec-path (list bin))
             (order nil))
        (when ,repowise-dir
          (make-directory (expand-file-name ".repowise" root))
          (when (stringp ,repowise-dir)
            (with-temp-file (expand-file-name ".repowise/config.yaml" root)
              (insert ,repowise-dir))))
        (when ,exit
          (with-temp-file (expand-file-name "repowise" bin)
            (insert (format "#!/bin/sh\n{ echo \"ARGV $*\"; env | grep -E '^(DO_NOT_TRACK|REPOWISE_TELEMETRY_DISABLED)='; env | cut -d= -f1 | grep -E '^((ANTHROPIC|OPENAI|GEMINI|OPENROUTER|LITELLM|DEEPSEEK)_API_KEY|REPOWISE_(DB_URL|DATABASE_URL|REASONING))$' | sed 's/^/LEAK /'; } > %s\nexit %d\n" rec ,exit)))
          (set-file-modes (expand-file-name "repowise" bin) #o755))
        (unwind-protect
            (cl-letf (((symbol-function 'ygg-agent-maps--run)
                       (lambda (dir argv done &optional merge)
                         (if (equal (file-name-nondirectory (car argv)) "repowise")
                             (let ((default-directory dir))
                               (push 'update order)
                               (funcall done (apply #'call-process (car argv) nil nil nil
                                                    (cdr argv))
                                        ""))
                           (when (equal (file-name-nondirectory (car argv)) "ice-repo-map")
                             (push 'generate order))
                           (ygg-agent-maps-tests--runner dir argv done merge))))
                      ((symbol-function 'aob-acp-spawn) (lambda (&rest _) 'session))
                      ((symbol-function 'message) #'ignore))
              (let ((process-environment
                     (append '("ANTHROPIC_API_KEY=secret" "OPENAI_API_KEY=secret"
                               "GEMINI_API_KEY=secret" "OPENROUTER_API_KEY=secret"
                               "LITELLM_API_KEY=secret" "DEEPSEEK_API_KEY=secret"
                               "REPOWISE_DB_URL=x" "REPOWISE_DATABASE_URL=x"
                               "REPOWISE_REASONING=x"
                               "DO_NOT_TRACK=0")
                             process-environment)))
                ,@body))
          (delete-directory bin t))))))

(ert-deftest ygg-agent-maps-generate-updates-repowise-first-without-keys ()
  (ygg-agent-maps-tests--with-repowise 0 ygg-agent-maps-tests--claude-md-off
    (ygg-agent-maps-generate root)
    (should (equal '(update generate) (seq-uniq (reverse order))))
    (let ((text (with-temp-buffer (insert-file-contents rec) (buffer-string))))
      (should (string-match-p "^ARGV update --index-only --no-agents$" text))
      (should (string-match-p "^DO_NOT_TRACK=1$" text))
      (should (string-match-p "^REPOWISE_TELEMETRY_DISABLED=1$" text))
      (should-not (string-match-p "^LEAK " text)))))

(ert-deftest ygg-agent-maps-generate-runs-after-a-failed-repowise-update ()
  (ygg-agent-maps-tests--with-repowise 1 ygg-agent-maps-tests--claude-md-off
    (let (shown)
      (cl-letf (((symbol-function 'message)
                 (lambda (fmt &rest args) (push (apply #'format fmt args) shown))))
        (ygg-agent-maps-generate root))
      (should (equal '(update generate) (seq-uniq (reverse order))))
      (should (member "aob: repowise update failed (exit 1)" shown)))))

(ert-deftest ygg-agent-maps-generate-skips-repowise-without-index-dir ()
  (ygg-agent-maps-tests--with-repowise 0 nil
    (ygg-agent-maps-generate root)
    (should (equal '(generate) (seq-uniq (reverse order))))
    (should-not (file-exists-p rec))))

(ert-deftest ygg-agent-maps-generate-skips-repowise-update-unless-claude-md-is-off ()
  (dolist (config (list t
                        "provider: gemini\n"
                        "editor_files:\n  agents_md: false\n"
                        "editor_files:\n  claude_md: true\n"
                        "editor_files:\n  claude_md: false_ish\n"
                        "editor_files:\n  agents_md: true\nclaude_md: false\n"
                        "hooks:\n  claude_md: false\n"))
    (ygg-agent-maps-tests--with-repowise 0 config
      (let (shown)
        (cl-letf (((symbol-function 'message)
                   (lambda (fmt &rest args) (push (apply #'format fmt args) shown))))
          (ygg-agent-maps-generate root))
        (should (equal '(generate) (seq-uniq (reverse order))))
        (should-not (file-exists-p rec))
        (should (cl-some (lambda (m) (string-match-p "repowise update skipped.*claude_md: false" m))
                         shown))))))

(ert-deftest ygg-agent-maps-generate-updates-repowise-for-each-claude-md-off-layout ()
  (dolist (config '("editor_files:\n  claude_md: false\n"
                    "editor_files:\n  agents_md: true\n  claude_md: false  # no\n"
                    "editor_files: {claude_md: false}\n"
                    "editor_files: {agents_md: true, claude_md: false}\n"
                    "editor_files:\n    claude_md: False\nhooks: {}\n"))
    (ygg-agent-maps-tests--with-repowise 0 config
      (ygg-agent-maps-generate root)
      (should (equal '(update generate) (seq-uniq (reverse order)))))))

(ert-deftest ygg-agent-maps-generate-skips-repowise-when-not-installed ()
  (ygg-agent-maps-tests--with-repowise nil t
    (ygg-agent-maps-generate root)
    (should (equal '(generate) (seq-uniq (reverse order))))))

(ert-deftest ygg-agent-maps-generate-skips-repowise-when-turned-off ()
  (ygg-agent-maps-tests--with-repowise 0 ygg-agent-maps-tests--claude-md-off
    (let ((ygg-agent-maps-repowise-update nil))
      (ygg-agent-maps-generate root))
    (should-not (file-exists-p rec))))

(ert-deftest ygg-agent-maps-generate-refuses-a-second-run-during-repowise-update ()
  (ygg-agent-maps-tests--with-repowise 0 ygg-agent-maps-tests--claude-md-off
    (let (held)
      (cl-letf (((symbol-function 'ygg-agent-maps--run)
                 (lambda (_dir _argv done &optional _merge) (setq held done))))
        (ygg-agent-maps-generate root)
        (should held)
        (should-error (ygg-agent-maps-generate root) :type 'user-error)))))

;; Real make-process/sentinel path: only the fake repowise on exec-path is stubbed in.
(defconst ygg-agent-maps-tests--real-run (symbol-function 'ygg-agent-maps--run))

(defmacro ygg-agent-maps-tests--with-real-repowise (script &rest body)
  (declare (indent 1))
  `(ygg-agent-maps-tests--with '("features.md")
     (let ((ygg-agent-maps-tests--spawned nil))
      (let* ((bin (file-name-as-directory (make-temp-file "ygg-maps-real-" t)))
             (exec-path (list bin))
             (order nil)
             (shown nil))
        (make-directory (expand-file-name ".repowise" root))
        (with-temp-file (expand-file-name ".repowise/config.yaml" root)
          (insert ygg-agent-maps-tests--claude-md-off))
        (with-temp-file (expand-file-name "repowise" bin)
          (insert "#!/bin/sh\n" ,script "\n"))
        (set-file-modes (expand-file-name "repowise" bin) #o755)
        (unwind-protect
            (cl-letf (((symbol-function 'ygg-agent-maps--run)
                       (lambda (dir argv done &optional merge)
                         (if (equal (file-name-nondirectory (car argv)) "repowise")
                             (progn (push 'update order)
                                    (funcall ygg-agent-maps-tests--real-run dir argv done merge))
                           (when (equal (file-name-nondirectory (car argv)) "ice-repo-map")
                             (push 'generate order))
                           (ygg-agent-maps-tests--runner dir argv done merge))))
                      ((symbol-function 'aob-acp-spawn) (lambda (&rest _) 'session))
                      ((symbol-function 'message)
                       (lambda (fmt &rest args) (push (apply #'format fmt args) shown))))
              ,@body)
          (dolist (p (process-list))
            (when (and (process-live-p p) (process-command p)
                       (equal (file-name-nondirectory (car (process-command p))) "repowise"))
              (kill-process p)))
          (delete-directory bin t))))))

(defun ygg-agent-maps-tests--await (pred)
  (let ((deadline (+ (float-time) 15)))
    (while (and (not (funcall pred)) (< (float-time) deadline))
      (accept-process-output nil 0.05))
    (should (funcall pred))))

(ert-deftest ygg-agent-maps-real-repowise-success-then-generates ()
  (ygg-agent-maps-tests--with-real-repowise "exit 0"
    (ygg-agent-maps-generate root)
    (ygg-agent-maps-tests--await (lambda () (memq 'generate order)))
    (should (equal '(update generate) (seq-uniq (reverse order))))
    (should-not (cl-some (lambda (m) (string-match-p "repowise update" m)) shown))))

(ert-deftest ygg-agent-maps-real-repowise-success-leaves-no-timer ()
  (ygg-agent-maps-tests--with-real-repowise "exit 0"
    (let ((before (copy-sequence timer-list)))
      (ygg-agent-maps-generate root)
      (ygg-agent-maps-tests--await (lambda () (memq 'generate order)))
      (should-not (cl-set-difference timer-list before)))))

(ert-deftest ygg-agent-maps-real-repowise-start-failure-generates-without-timer ()
  (ygg-agent-maps-tests--with-real-repowise "exit 0"
    (let ((before (copy-sequence timer-list))
          (ygg-agent-maps-repowise-update-timeout 1)
          (real-make-process (symbol-function 'make-process))
          (killed nil))
      (cl-letf (((symbol-function 'make-process)
                 (lambda (&rest args)
                   (if (equal (file-name-nondirectory (car (plist-get args :command)))
                              "repowise")
                       (error "cannot start")
                     (apply real-make-process args))))
                ((symbol-function 'kill-process)
                 (lambda (&rest _) (setq killed t))))
        (ygg-agent-maps-generate root)
        (should (memq 'generate order))
        (should-not (cl-set-difference timer-list before))
        (sleep-for 1.5)
        (should-not killed)
        (should (member "aob: repowise update failed (exit -1)" shown))))))

(ert-deftest ygg-agent-maps-real-repowise-failure-still-generates ()
  (ygg-agent-maps-tests--with-real-repowise "exit 3"
    (ygg-agent-maps-generate root)
    (ygg-agent-maps-tests--await (lambda () (memq 'generate order)))
    (should (equal '(update generate) (seq-uniq (reverse order))))
    (should (member "aob: repowise update failed (exit 3)" shown))))

(ert-deftest ygg-agent-maps-real-repowise-hang-is-killed-and-generates ()
  (ygg-agent-maps-tests--with-real-repowise "exec sleep 30"
    (let ((ygg-agent-maps-repowise-update-timeout 1))
      (ygg-agent-maps-generate root)
      (ygg-agent-maps-tests--await (lambda () (memq 'generate order)))
      (should (equal '(update generate) (seq-uniq (reverse order))))
      (should (cl-some (lambda (m) (string-match-p "aob: repowise update timed out" m)) shown))
      (ygg-agent-maps-tests--await
       (lambda () (zerop (plist-get (ygg-agent-maps--entry root) :pending))))
      (let ((once (cl-count 'generate order)))
        (ygg-agent-maps-generate root)
        (ygg-agent-maps-tests--await (lambda () (= 2 (cl-count 'update order))))
        (ygg-agent-maps-tests--await (lambda () (= (* 2 once) (cl-count 'generate order))))))))

(ert-deftest ygg-agent-maps-features-works-in-the-root-never-a-worktree ()
  (ygg-agent-maps-tests--with '("features.md")
    (let (seen)
      (cl-letf (((symbol-function 'aob-acp-spawn)
                 (lambda (agent prompt &rest _)
                   (setq seen (list (aob-acp--project)
                                    (plist-get (aob-acp-preset agent) :worktree)
                                    (plist-get (aob-acp-preset agent) :mode)
                                    aob-acp-start-worktree
                                    prompt))
                   'session))
                (aob-acp-start-worktree '("/elsewhere" . "br"))
                (aob-acp-presets (list (cons aob-acp-default-agent
                                             '(:agent "claude" :worktree t :mode "bypass")))))
        (ygg-agent-maps-features root))
      (should (equal (file-truename root) (file-truename (car seen))))
      (should-not (nth 1 seen))
      (should (equal "bypass" (nth 2 seen)))
      (should-not (nth 3 seen))
      (should (string-match-p "not available" (nth 4 seen)))
      (should (string-match-p "verify each feature's keys and commands" (nth 4 seen)))
      (should-not (string-match-p "live" (nth 4 seen))))))

(ert-deftest ygg-agent-maps-works-without-ice ()
  (should-not (featurep 'ygg-ice))
  (should (commandp 'ygg-agent-maps-generate))
  (should (commandp 'ygg-agent-maps-features)))

(defun ygg-agent-maps-tests--sent-once (s)
  (ygg-agent-maps-on-ready s)
  (ygg-agent-maps-tests--first-block s)
  (aob-set-state s 'working)
  (aob-set-state s 'idle)
  (should-not (ygg-agent-maps-tests--first-block s)))

(defun ygg-agent-maps-tests--sent-once-more (s)
  (aob-set-state s 'working)
  (aob-set-state s 'idle)
  (should-not (ygg-agent-maps-tests--first-block s)))

(ert-deftest ygg-agent-maps-claude-clear-sends-the-maps-again ()
  (ygg-agent-maps-tests--with '("features.md")
    (let ((s (ygg-agent-maps-tests--session root :agent "claude" :acp-id "sess-1")))
      (ygg-agent-maps-tests--sent-once s)
      (should (aob-session-ref s :maps-sent))
      (cl-letf (((symbol-function 'aob-acp--request)
                 (lambda (_s _m _p cb) (funcall cb '(:stopReason "end_turn") nil))))
        (aob-acp--prompt s "/clear"))
      (should (eq (aob-session-ref s :maps-pending) t))
      (should-not (aob-session-ref s :maps-sent))
      (should (string-match-p "MAP-BODY" (ygg-agent-maps-tests--first-block s)))
      (ygg-agent-maps-tests--sent-once-more s)
      (aob-remove-session s))))

(ert-deftest ygg-agent-maps-pi-clear-sends-the-maps-again ()
  (ygg-agent-maps-tests--with '("features.md")
    (let* ((proc (make-process :name "maps-cat" :command '("cat")
                               :connection-type 'pipe :noquery t))
           (s (ygg-agent-maps-tests--session root :agent "pi")))
      (unwind-protect
          (progn
            (process-put proc 'aob-sessions (make-hash-table :test #'equal))
            (process-put proc 'aob-init '(done (:agentCapabilities nil)))
            (setf (aob-session-conn s) proc)
            (ygg-agent-maps-tests--sent-once s)
            (cl-letf (((symbol-function 'aob-acp--request)
                       (lambda (_s _m _p cb) (funcall cb '(:sessionId "fresh") nil))))
              (aob-acp-clear s))
            (should (eq (aob-session-ref s :maps-pending) t))
            (should-not (aob-session-ref s :maps-sent))
            (should (string-match-p "MAP-BODY" (ygg-agent-maps-tests--first-block s)))
            (ygg-agent-maps-tests--sent-once-more s))
        (delete-process proc)
        (aob-remove-session s)))))

(provide 'ygg-agent-maps-tests)
;;; ygg-agent-maps-tests.el ends here
