;;; ygg-lsp-extra-servers-tests.el --- marksman, docker, sql, toml servers and semantic tokens -*- lexical-binding: t; -*-

(setq load-prefer-newer t)
(require 'ert)
(require 'cl-lib)
(require 'yggdrasil)

(defvar ygg-lsp-extra-servers-tests--bare (make-temp-file "ygg-bare" t))

(let ((exec-path (list ygg-lsp-extra-servers-tests--bare)))
  (require 'layer-lsp))
(require 'eglot)

(defun ygg-lsp-extra-servers-tests--contact (mode)
  (cdr (seq-find (lambda (entry)
                   (let ((modes (car entry)))
                     (memq mode (mapcar (lambda (m) (if (consp m) (car m) m))
                                        (if (listp modes) modes (list modes))))))
                 eglot-server-programs)))

(ert-deftest ygg-lsp-extra-servers-programs-registered ()
  (dolist (case '((dockerfile-ts-mode "docker-langserver" "--stdio")
                  (dockerfile-mode "docker-langserver" "--stdio")
                  (sql-mode "sqruff" "lsp")
                  (toml-ts-mode "taplo" "lsp" "stdio")
                  (conf-toml-mode "taplo" "lsp" "stdio")))
    (should (equal (ygg-lsp-extra-servers-tests--contact (car case)) (cdr case))))
  (dolist (mode '(markdown-mode gfm-mode))
    (should (eq (ygg-lsp-extra-servers-tests--contact mode) 'ygg-lsp-markdown-contact))))

(ert-deftest ygg-lsp-extra-servers-markdown-prefers-marksman ()
  (let ((exec-path (list ygg-lsp-extra-servers-tests--bare)))
    (should (equal (ygg-lsp-markdown-contact) '("harper-ls" "--stdio"))))
  (let* ((dir (make-temp-file "ygg-bin" t))
         (file (expand-file-name "marksman" dir))
         (exec-path (list dir)))
    (with-temp-file file (insert "#!/bin/sh\nexit 0\n"))
    (set-file-modes file #o755)
    (should (equal (ygg-lsp-markdown-contact) '("marksman" "server")))))

(defun ygg-lsp-extra-servers-tests--fire (hook binaries)
  (let* ((dir (make-temp-file "ygg-bin" t))
         (exec-path (list dir))
         (ygg-lsp--warned nil)
         (ensured 0))
    (dolist (name binaries)
      (let ((file (expand-file-name name dir)))
        (with-temp-file file (insert "#!/bin/sh\nexit 0\n"))
        (set-file-modes file #o755)))
    (cl-letf (((symbol-function 'eglot-ensure) (lambda () (cl-incf ensured)))
              ((symbol-function 'message) #'ignore))
      (with-temp-buffer (run-hooks hook)))
    ensured))

(ert-deftest ygg-lsp-extra-servers-hooks-wait-for-binary ()
  (dolist (case '((dockerfile-ts-mode-hook "docker-langserver")
                  (dockerfile-mode-hook "docker-langserver")
                  (sql-mode-hook "sqruff")
                  (toml-ts-mode-hook "taplo")
                  (conf-toml-mode-hook "taplo")
                  (markdown-mode-hook "marksman")
                  (gfm-mode-hook "harper-ls")))
    (should (= 1 (ygg-lsp-extra-servers-tests--fire (car case) (cdr case))))
    (should (= 0 (ygg-lsp-extra-servers-tests--fire (car case) nil)))))

(ert-deftest ygg-lsp-extra-servers-semantic-tokens-only-in-listed-modes ()
  (should-not (memq :semanticTokensProvider eglot-ignored-server-capabilities))
  (dolist (case '((dart-mode . t) (rust-ts-mode . t) (python-mode . nil)))
    (with-temp-buffer
      (cl-letf (((symbol-function 'eglot-server-capable) (lambda (&rest _) t)))
        (setq major-mode (car case))
        (eglot-semantic-tokens-mode 1)
        (ygg-lsp--semantic-tokens-sync)
        (should (eq (cdr case) (and eglot-semantic-tokens-mode t)))))))

(ert-deftest ygg-lsp-extra-servers-semantic-toggle-key ()
  (should (eq (lookup-key ygg-leader-code-map "k") #'ygg-toggle-semantic-tokens))
  (should (eq (lookup-key ygg-leader-code-map "i") #'ygg-toggle-inlay-hints)))

(provide 'ygg-lsp-extra-servers-tests)
