;;; ygg-review-file.el --- a compare review as one markdown file -*- lexical-binding: t; -*-

;;; Commentary:
;; Pure printer and parser between a compare review (its comment and forge
;; thread plists) and a markdown review file: YAML front matter for the
;; review's own fields, the diff quoted with "> ", and every comment or
;; thread a fenced div placed under the quoted line it anchors to.
;;
;; A comment div carries only what its position and the front matter cannot
;; tell.  A range comment sits right after the range's last quoted line and
;; carries span=N, the number of quoted content lines it covers that are on
;; its start-side or side (a context line counts as a new-side line).

;;; Code:

(require 'cl-lib)
(require 'subr-x)
(require 'seq)

(defgroup ygg-review-file nil "The markdown file a compare review lives in." :group 'tools)

(defcustom ygg-review-file-snip-threshold 8
  "A context run longer than this, far from any comment, prints as a snip.
Nil keeps every line."
  :type '(choice (const :tag "Never" nil) integer) :group 'ygg-review-file)

(defcustom ygg-review-file-snip-margin 3
  "Context lines kept around a comment, a thread and each change."
  :type 'integer :group 'ygg-review-file)

(define-error 'ygg-review-file-bad "Bad review file syntax")

(defvar read-eval)
(defvar ygg-review-file--problems nil)
(defvar ygg-review-file--id-count 0)

(defconst ygg-review-file--symbol-keys '(:level :side :start-side :type :status :verdict))
(defconst ygg-review-file--derived-keys
  '(:level :file :old-path :new-path :side :line :old-line :start-side :start-line :start-old-line))
(defconst ygg-review-file--thread-derived '(:level :file :new-path :side :line :start-line))
(defconst ygg-review-file--entry-keys '(:id :author :created :text :url))
(defconst ygg-review-file--front-order '(:repo :pr :base :head :round :verdict :range :author))
(defconst ygg-review-file--attr-order
  '(:level :type :priority :confidence :correctness :title :file :old-path :new-path :side :line
    :old-line :start-side :start-line :start-old-line :range :created :author :status :unknown
    :span :quote :diff-hunk :url :text))

(defun ygg-review-file--note (line message)
  (push (cons (or line 1) message) ygg-review-file--problems))

(defun ygg-review-file--new-id ()
  (format "%x%04x%x" (truncate (* 1000 (float-time))) (random #x10000)
          (cl-incf ygg-review-file--id-count)))

(defun ygg-review-file--bad (message)
  (signal 'ygg-review-file-bad (list message)))

;;; Scalars

(defun ygg-review-file--plain-p (string)
  (and (string-match-p "\\`[A-Za-z][A-Za-z0-9_./@-]*\\'" string)
       (not (member (downcase string) '("true" "false" "null" "yes" "no" "on" "off" "y" "n")))))

(defun ygg-review-file--quote (string)
  (concat "\""
          (mapconcat
           (lambda (c)
             (cond ((eq c ?\") "\\\"") ((eq c ?\\) "\\\\") ((eq c ?\n) "\\n")
                   ((eq c ?\t) "\\t") ((eq c ?\r) "\\r")
                   ((or (< c 32) (<= #x7f c #x9f) (memq c '(#x2028 #x2029 #xfeff)))
                    (format "\\u%04X" c))
                   (t (string c))))
           string "")
          "\""))

(defun ygg-review-file--float (value)
  (cond ((isnan value) ".nan")
        ((= value 1.0e+INF) ".inf")
        ((= value -1.0e+INF) "-.inf")
        (t (let ((s (number-to-string value)))
             (if (string-match-p "\\." s) s (replace-regexp-in-string "e" ".0e" s))))))

(defun ygg-review-file--days (year month day)
  (let* ((y (if (<= month 2) (1- year) year))
         (era (floor y 400))
         (yoe (- y (* era 400)))
         (doy (+ (/ (+ (* 153 (+ month (if (> month 2) -3 9))) 2) 5) (1- day)))
         (doe (+ (* yoe 365) (/ yoe 4) (- (/ yoe 100)) doy)))
    (+ (* era 146097) doe -719468)))

(defun ygg-review-file--iso-parse (token)
  (when (string-match (concat "\\`\\([0-9]\\{4\\}\\)-\\([0-9]\\{2\\}\\)-\\([0-9]\\{2\\}\\)"
                              "T\\([0-9]\\{2\\}\\):\\([0-9]\\{2\\}\\):\\([0-9]\\{2\\}\\)"
                              "\\(?:\\.\\([0-9]+\\)\\)?"
                              "\\(Z\\|\\([-+]\\)\\([0-9]\\{2\\}\\):\\([0-9]\\{2\\}\\)\\)?\\'")
                      token)
    (let* ((n (mapcar (lambda (k) (string-to-number (match-string k token))) '(1 2 3 4 5 6)))
           (frac (match-string 7 token))
           (sign (match-string 9 token))
           (hours (if sign (string-to-number (match-string 10 token)) 0))
           (minutes (if sign (string-to-number (match-string 11 token)) 0))
           (offset (* (if (equal sign "-") -1 1) (+ (* 3600 hours) (* 60 minutes))))
           (local (+ (* 86400 (ygg-review-file--days (nth 0 n) (nth 1 n) (nth 2 n)))
                     (* 3600 (nth 3 n)) (* 60 (nth 4 n)) (nth 5 n)))
           (secs (- local offset)))
      (when (and (<= hours 23) (<= minutes 59)
                 (string= (format-time-string "%Y-%m-%dT%H:%M:%S" local t) (substring token 0 19)))
        (cond ((null frac) secs)
              ((>= secs 0) (string-to-number (format "%d.%s" secs frac)))
              (t (+ secs (string-to-number (concat "0." frac)))))))))

(defun ygg-review-file--iso (value)
  (when (and (numberp value) (>= value 0) (< value 253402300800))
    (let ((s (number-to-string value)))
      (when (string-match "\\`\\([0-9]+\\)\\(?:\\.\\([0-9]+\\)\\)?\\'" s)
        (let ((text (concat (format-time-string "%Y-%m-%dT%H:%M:%S" (string-to-number (match-string 1 s)) t)
                            (and (match-string 2 s) (concat "." (match-string 2 s)))
                            "Z")))
          (and (equal (ygg-review-file--iso-parse text) value) text))))))

(defun ygg-review-file--name (key)
  (when (keywordp key)
    (let ((name (substring (symbol-name key) 1)))
      (and (string-match-p "\\`[A-Za-z][A-Za-z0-9_-]*\\'" name) name))))

(defun ygg-review-file--show (value)
  (condition-case nil (format "%S" value) (error "#<unprintable>")))

(defun ygg-review-file--safe-p (value)
  (let ((budget 10000))
    (named-let walk ((x value) (depth 0))
      (and (> (cl-decf budget) 0) (< depth 40)
           (cond ((or (null x) (numberp x) (stringp x) (symbolp x)) t)
                 ((consp x)
                  (let ((ok t))
                    (while (and ok (consp x))
                      (setq ok (walk (car x) (1+ depth)) x (cdr x)))
                    (and ok (walk x (1+ depth)))))
                 ((vectorp x) (seq-every-p (lambda (e) (walk e (1+ depth))) x)))))))

(defun ygg-review-file--lisp (value)
  (if (ygg-review-file--safe-p value)
      (concat "~" (ygg-review-file--quote
                   (let ((print-length nil) (print-level nil) (print-circle nil))
                     (prin1-to-string value))))
    (ygg-review-file--quote (ygg-review-file--show value))))

(defun ygg-review-file--value (key value)
  (let ((symbolic (memq key ygg-review-file--symbol-keys)))
    (cond ((null value) "null")
          ((eq value t) "true")
          ((and (eq key :created) (ygg-review-file--iso value)))
          ((integerp value) (number-to-string value))
          ((floatp value) (ygg-review-file--float value))
          ((stringp value)
           (if (and (not symbolic) (ygg-review-file--plain-p value)) value
             (ygg-review-file--quote value)))
          ((symbolp value)
           (let* ((name (symbol-name value)) (plain (ygg-review-file--plain-p name)))
             (concat (if (and symbolic plain) "" ":")
                     (if plain name (ygg-review-file--quote name)))))
          ((or (consp value) (vectorp value)) (ygg-review-file--lisp value))
          (t (ygg-review-file--quote (ygg-review-file--show value))))))

(defun ygg-review-file--hex (s i digits)
  (let ((end (+ i digits)))
    (unless (and (<= end (length s)) (string-match-p "\\`[0-9A-Fa-f]+\\'" (substring s i end)))
      (ygg-review-file--bad "bad escape"))
    (let ((code (string-to-number (substring s i end) 16)))
      (unless (characterp code) (ygg-review-file--bad "bad escape"))
      (cons code end))))

(defun ygg-review-file--read-quoted (s i)
  (let ((n (length s)) (j (1+ i)) chars)
    (while (and (< j n) (/= (aref s j) ?\"))
      (let ((c (aref s j)))
        (setq j (1+ j))
        (if (/= c ?\\) (push c chars)
          (when (>= j n) (ygg-review-file--bad "unterminated string"))
          (let ((e (aref s j)))
            (setq j (1+ j))
            (pcase e
              (?n (push ?\n chars))
              (?t (push ?\t chars))
              (?r (push ?\r chars))
              ((or ?x ?u ?U)
               (let ((h (ygg-review-file--hex s j (pcase e (?x 2) (?u 4) (_ 8)))))
                 (push (car h) chars)
                 (setq j (cdr h))))
              (_ (push e chars)))))))
    (unless (< j n) (ygg-review-file--bad "unterminated string"))
    (cons (concat (nreverse chars)) (1+ j))))

(defun ygg-review-file--read-lisp (text)
  (let* ((read-eval nil)
         (value (condition-case nil (car (read-from-string text))
                  (error (ygg-review-file--bad "unreadable value")))))
    (unless (ygg-review-file--safe-p value) (ygg-review-file--bad "unsafe value"))
    value))

(defun ygg-review-file--prefix-p (s i prefix)
  (let ((end (+ i (length prefix))))
    (and (<= end (length s)) (string= prefix (substring s i end)))))

(defun ygg-review-file--bare (token key)
  (cond ((member token '("null" "~")) nil)
        ((equal token "true") t)
        ((equal token "false") nil)
        ((equal token ".inf") 1.0e+INF)
        ((equal token "-.inf") -1.0e+INF)
        ((equal token ".nan") 0.0e+NaN)
        ((string-match-p "\\`-?[0-9]+\\'" token) (string-to-number token))
        ((string-match-p "\\`-?[0-9]+\\(\\.[0-9]*\\)?\\([eE][-+]?[0-9]+\\)?\\'" token)
         (float (string-to-number token)))
        ((and (eq key :created) (ygg-review-file--iso-parse token)))
        ((string-prefix-p ":" token) (intern (substring token 1)))
        ((memq key ygg-review-file--symbol-keys) (intern token))
        (t token)))

(defun ygg-review-file--read-value (s i key)
  (cond ((>= i (length s)) (ygg-review-file--bad "missing value"))
        ((eq (aref s i) ?\") (ygg-review-file--read-quoted s i))
        ((ygg-review-file--prefix-p s i ":\"")
         (let ((q (ygg-review-file--read-quoted s (1+ i)))) (cons (intern (car q)) (cdr q))))
        ((ygg-review-file--prefix-p s i "~\"")
         (let ((q (ygg-review-file--read-quoted s (1+ i))))
           (cons (ygg-review-file--read-lisp (car q)) (cdr q))))
        ((memq (aref s i) '(?\s ?\t ?}))
         (ygg-review-file--bad "missing value"))
        (t (string-match "[^ \t}\"]+" s i)
           (let ((token (match-string 0 s)) (end (match-end 0)))
             (cons (ygg-review-file--bare token key) end)))))

(defun ygg-review-file--name-end (s i)
  (let ((n (length s)))
    (while (and (< i n) (let ((c (aref s i)))
                          (or (<= ?a c ?z) (<= ?A c ?Z) (<= ?0 c ?9) (memq c '(?_ ?-)))))
      (setq i (1+ i)))
    i))

(defun ygg-review-file--token-start-p (s i)
  (and (< i (length s)) (not (memq (aref s i) '(?\s ?\t ?} ?\" ?=)))))

(defun ygg-review-file--read-attrs (s brace line)
  (let ((n (length s)) (i 0) classes id pairs closed (seen (make-hash-table :test 'eq)))
    (while (progn (while (and (< i n) (memq (aref s i) '(?\s ?\t))) (setq i (1+ i)))
                  (and (< i n) (not (setq closed (eq (aref s i) ?})))))
      (let ((c (aref s i)))
        (cond
         ((and (memq c '(?. ?#)) (ygg-review-file--token-start-p s (1+ i)))
          (string-match "[^ \t}\"=]+" s (1+ i))
          (if (eq c ?.) (push (match-string 0 s) classes) (setq id (match-string 0 s)))
          (setq i (match-end 0)))
         ((and (or (<= ?a c ?z) (<= ?A c ?Z))
               (let ((e (ygg-review-file--name-end s i))) (and (< e n) (eq (aref s e) ?=) e)))
          (let* ((e (ygg-review-file--name-end s i))
                 (name (substring s i e))
                 (start (1+ e))
                 (key (intern (concat ":" name))))
            (condition-case err
                (let ((v (ygg-review-file--read-value s start key)))
                  (if-let* ((pair (gethash key seen))) (setcdr pair (car v))
                    (let ((pair (cons key (car v))))
                      (puthash key pair seen)
                      (push pair pairs)))
                  (setq i (cdr v)))
              (ygg-review-file-bad
               (ygg-review-file--note line (format "bad attribute %s: %s" name (cadr err)))
               (string-match "[^ \t}]*" s start)
               (setq i (match-end 0))))))
         (t (string-match "[^ \t}]+" s i)
            (ygg-review-file--note line (format "bad attribute %s" (match-string 0 s)))
            (setq i (match-end 0))))))
    (when (and brace (not closed))
      (ygg-review-file--note line "attributes are not closed with }"))
    (list (nreverse classes) id (cl-loop for pair in (nreverse pairs) append (list (car pair) (cdr pair))))))

(defun ygg-review-file--ordered (plist order skip)
  (let (keys)
    (cl-loop for (key value) on plist by #'cddr
             unless (or (memq key skip) (null value) (memq key keys)) do (push key keys))
    (sort (nreverse keys)
          (lambda (a b) (< (or (cl-position a order) 99) (or (cl-position b order) 99))))))

(defun ygg-review-file--rank (key)
  (or (cl-position key ygg-review-file--attr-order)
      (cl-position :unknown ygg-review-file--attr-order)))

(defun ygg-review-file--attrs (pairs)
  (mapconcat (lambda (p) (format " %s=%s" (ygg-review-file--name (car p))
                                 (ygg-review-file--value (car p) (cdr p))))
             (sort (seq-filter (lambda (p) (ygg-review-file--name (car p))) pairs)
                   (lambda (a b) (< (ygg-review-file--rank (car a)) (ygg-review-file--rank (car b)))))
             ""))

(defun ygg-review-file--idstr (id)
  (if (stringp id) id (format "%s" id)))

(defun ygg-review-file--id-attr (id)
  (when id
    (let ((s (ygg-review-file--idstr id)))
      (if (string-match-p "\\`[A-Za-z0-9_.:-]+\\'" s)
          (concat " #" s)
        (format " id=%s" (ygg-review-file--quote s))))))

;;; Front matter

(defun ygg-review-file--default-author (comments)
  (let ((counts (make-hash-table :test 'equal)) best)
    (dolist (c comments)
      (when-let* ((a (plist-get c :author))) (puthash a (1+ (gethash a counts 0)) counts)))
    (maphash (lambda (a n)
               (when (or (null best) (> n (gethash best counts))
                         (and (= n (gethash best counts)) (string< (format "%S" a) (format "%S" best))))
                 (setq best a)))
             counts)
    (and best (>= (gethash best counts) 2) best)))

(defun ygg-review-file--front-print (review default)
  (let* ((review (append (cl-loop for (k v) on review by #'cddr unless (eq k :author) append (list k v))
                         (and default (list :author default))))
         (keys (seq-filter #'ygg-review-file--name
                           (ygg-review-file--ordered review ygg-review-file--front-order
                                                     '(:comments :threads :text :problems)))))
    (concat "---\n"
            (mapconcat (lambda (key) (format "%s: %s\n" (ygg-review-file--name key)
                                             (ygg-review-file--value key (plist-get review key))))
                       keys "")
            "---\n")))

(defun ygg-review-file--front-checked (key value row)
  (let ((ok (and value (ygg-review-file--field key value))))
    (cond ((null value) (list nil))
          (ok (list (car ok)))
          (t (ygg-review-file--note row (format "bad value for %s, ignored" (substring (symbol-name key) 1)))
             nil))))

(defun ygg-review-file--front-value (key text row)
  (if (string-empty-p text) (list nil)
    (condition-case err
        (if (string-match-p "\\`\\(?::\\|~\\)?\"" text)
            (let ((v (ygg-review-file--read-value text 0 key)))
              (unless (string-blank-p (substring text (cdr v)))
                (ygg-review-file--note row (format "text after the value of %s" key)))
              (ygg-review-file--front-checked key (car v) row))
          (ygg-review-file--front-checked key (ygg-review-file--bare text key) row))
      (ygg-review-file-bad
       (ygg-review-file--note row (format "bad front matter value for %s: %s" key (cadr err)))
       nil))))

(defun ygg-review-file--front (lines)
  (let ((n (length lines)) (fence "\\`---[ \t]*\\'")
        (key-re "\\`\\([A-Za-z][A-Za-z0-9_-]*\\):[ \t]*\\(.*?\\)[ \t]*\\'"))
    (if (not (and (> n 0) (string-match-p fence (aref lines 0))))
        (cons nil 0)
      (let* ((close (cl-loop for j from 1 below n when (string-match-p fence (aref lines j)) return j))
             (j 1) plist)
        (unless close (ygg-review-file--note 1 "front matter is not closed"))
        (while (and (< j (or close n))
                    (or close (string-match-p key-re (aref lines j))))
          (let ((line (aref lines j)))
            (cond ((string-match key-re line)
                   (let* ((key (intern (concat ":" (match-string 1 line))))
                          (v (ygg-review-file--front-value key (match-string 2 line) (1+ j))))
                     (when v (setq plist (plist-put plist key (car v))))))
                  ((not (string-blank-p line))
                   (ygg-review-file--note (1+ j) (format "bad front matter line: %s" line)))))
          (cl-incf j))
        (cons plist (if close (1+ close) j))))))

;;; Diff scanning

(cl-defstruct (ygg-review-file--scan (:conc-name ygg-review-file--s-) (:constructor ygg-review-file--scan-new ())
                                     (:copier nil))
  old-path new-path (old 0) (new 0) (rem-old 0) (rem-new 0) (pos 0) hunk notify flagged)

(defun ygg-review-file--flag (scan message)
  (when (and (ygg-review-file--s-notify scan) (not (ygg-review-file--s-flagged scan)))
    (setf (ygg-review-file--s-flagged scan) t)
    (funcall (ygg-review-file--s-notify scan) (ygg-review-file--s-pos scan) message)))

(defun ygg-review-file--rec (scan kind text &rest props)
  (append (list :kind kind :text text :old-path (ygg-review-file--s-old-path scan)
                :new-path (ygg-review-file--s-new-path scan) :hunk (ygg-review-file--s-hunk scan))
          props))

(defun ygg-review-file--git-quoted (s i)
  (let ((n (length s)) (j (1+ i)) bytes)
    (while (and (< j n) (/= (aref s j) ?\"))
      (let ((c (aref s j)))
        (setq j (1+ j))
        (if (/= c ?\\)
            (dolist (b (string-to-list (encode-coding-string (string c) 'utf-8)))
              (push b bytes))
          (when (< j n)
            (let ((e (aref s j)))
              (setq j (1+ j))
              (if (<= ?0 e ?7)
                  (let ((code (- e ?0)) (digits 1))
                    (while (and (< digits 3) (< j n) (<= ?0 (aref s j) ?7))
                      (setq code (+ (* code 8) (- (aref s j) ?0)) j (1+ j) digits (1+ digits)))
                    (push (logand code #xff) bytes))
                (push (pcase e (?a 7) (?b 8) (?f 12) (?n 10) (?r 13) (?t 9) (?v 11) (_ e)) bytes)))))))
    (when (< j n)
      (cons (decode-coding-string (apply #'unibyte-string (nreverse bytes)) 'utf-8) (1+ j)))))

(defun ygg-review-file--git-path (text prefix)
  (let ((path (if (string-prefix-p "\"" text)
                  (car (ygg-review-file--git-quoted text 0))
                (substring text 0 (string-search "\t" text)))))
    (when (and path (string-prefix-p prefix path) (> (length path) (length prefix)))
      (substring path (length prefix)))))

(defun ygg-review-file--diff-paths (rest)
  (cond
   ((string-prefix-p "\"" rest)
    (when-let* ((q (ygg-review-file--git-quoted rest 0))
                (tail (substring rest (cdr q)))
                ((string-prefix-p " " tail))
                (old (and (string-prefix-p "a/" (car q)) (substring (car q) 2)))
                (new (ygg-review-file--git-path (substring tail 1) "b/")))
      (cons old new)))
   ((string-prefix-p "a/" rest)
    (let* ((half (/ (- (length rest) 5) 2)) (name (and (>= half 1) (substring rest 2 (+ 2 half)))))
      (cond
       ((and name (= (length rest) (+ 5 (* 2 half))) (string= (substring rest (+ 2 half)) (concat " b/" name)))
        (cons name name))
       ((string-match "\\`a/\\(.+\\) \\(\"b/.*\\)\\'" rest)
        (when-let* ((new (ygg-review-file--git-path (match-string 2 rest) "b/")))
          (cons (match-string 1 rest) new)))
       ((string-match "\\`a/\\(.+\\) b/\\(.+\\)\\'" rest)
        (cons (match-string 1 rest) (match-string 2 rest))))))))

(defconst ygg-review-file--hunk-header
  "\\`@@ -\\([0-9]+\\)\\(?:,\\([0-9]+\\)\\)? \\+\\([0-9]+\\)\\(?:,\\([0-9]+\\)\\)? @@")

(defun ygg-review-file--step (scan text)
  (let* ((active (or (> (ygg-review-file--s-rem-old scan) 0) (> (ygg-review-file--s-rem-new scan) 0)))
         (boundary (string-match-p "\\`\\(?:@@ -\\|diff --git \\)" text))
         (hunk (and active (not boundary)))
         paths)
    (when (and active boundary)
      (ygg-review-file--flag scan "hunk has fewer lines than its header says")
      (setf (ygg-review-file--s-rem-old scan) 0 (ygg-review-file--s-rem-new scan) 0))
    (cond
     ((and hunk (string-match "\\`\\[\\.\\.\\. \\([0-9]+\\) lines\\]\\'" text))
      (let ((n (string-to-number (match-string 1 text))))
        (when (or (> n (ygg-review-file--s-rem-old scan)) (> n (ygg-review-file--s-rem-new scan)))
          (ygg-review-file--flag scan "snip is longer than the rest of its hunk"))
        (cl-incf (ygg-review-file--s-old scan) n) (cl-incf (ygg-review-file--s-new scan) n)
        (cl-decf (ygg-review-file--s-rem-old scan) n) (cl-decf (ygg-review-file--s-rem-new scan) n)
        (ygg-review-file--rec scan 'snip text :count n)))
     ((and hunk (not (string-prefix-p "\\" text)))
      (pcase (and (not (string-empty-p text)) (aref text 0))
        (?- (when (<= (ygg-review-file--s-rem-old scan) 0)
              (ygg-review-file--flag scan "hunk has more lines than its header says"))
            (prog1 (ygg-review-file--rec scan 'del text :side 'old :line (ygg-review-file--s-old scan))
              (cl-incf (ygg-review-file--s-old scan)) (cl-decf (ygg-review-file--s-rem-old scan))))
        (?+ (when (<= (ygg-review-file--s-rem-new scan) 0)
              (ygg-review-file--flag scan "hunk has more lines than its header says"))
            (prog1 (ygg-review-file--rec scan 'add text :side 'new :line (ygg-review-file--s-new scan))
              (cl-incf (ygg-review-file--s-new scan)) (cl-decf (ygg-review-file--s-rem-new scan))))
        (_ (when (or (<= (ygg-review-file--s-rem-old scan) 0) (<= (ygg-review-file--s-rem-new scan) 0))
             (ygg-review-file--flag scan "hunk has more lines than its header says"))
           (prog1 (ygg-review-file--rec scan 'ctx text :side 'new :line (ygg-review-file--s-new scan)
                                        :old-line (ygg-review-file--s-old scan))
             (cl-incf (ygg-review-file--s-old scan)) (cl-incf (ygg-review-file--s-new scan))
             (cl-decf (ygg-review-file--s-rem-old scan)) (cl-decf (ygg-review-file--s-rem-new scan))))))
     ((string-prefix-p "\\" text) (ygg-review-file--rec scan 'note text))
     ((and (string-prefix-p "diff --git " text)
           (setq paths (ygg-review-file--diff-paths (substring text 11))))
      (setf (ygg-review-file--s-old-path scan) (car paths)
            (ygg-review-file--s-new-path scan) (cdr paths)
            (ygg-review-file--s-hunk scan) nil
            (ygg-review-file--s-flagged scan) nil)
      (ygg-review-file--rec scan 'diff text))
     ((string-match ygg-review-file--hunk-header text)
      (setf (ygg-review-file--s-old scan) (string-to-number (match-string 1 text))
            (ygg-review-file--s-rem-old scan) (if (match-string 2 text) (string-to-number (match-string 2 text)) 1)
            (ygg-review-file--s-new scan) (string-to-number (match-string 3 text))
            (ygg-review-file--s-rem-new scan) (if (match-string 4 text) (string-to-number (match-string 4 text)) 1)
            (ygg-review-file--s-hunk scan) (ygg-review-file--s-pos scan)
            (ygg-review-file--s-flagged scan) nil)
      (ygg-review-file--rec scan 'hunk text))
     (t
      (cond ((and (string-prefix-p "--- " text) (setq paths (ygg-review-file--git-path (substring text 4) "a/")))
             (setf (ygg-review-file--s-old-path scan) paths))
            ((and (string-prefix-p "+++ " text) (setq paths (ygg-review-file--git-path (substring text 4) "b/")))
             (setf (ygg-review-file--s-new-path scan) paths))
            ((and (string-prefix-p "rename from " text) (setq paths (ygg-review-file--git-path (substring text 12) "")))
             (setf (ygg-review-file--s-old-path scan) paths))
            ((and (string-prefix-p "rename to " text) (setq paths (ygg-review-file--git-path (substring text 10) "")))
             (setf (ygg-review-file--s-new-path scan) paths))
            ((and (ygg-review-file--s-old-path scan)
                  (string-match-p "\\`[-+ ]" text)
                  (not (string-match-p "\\`\\(?:---\\|\\+\\+\\+\\) \\(?:a/\\|b/\\|/dev/null\\|\"\\)" text)))
             (ygg-review-file--flag scan "diff line outside any hunk, its hunk header is missing or the hunk is longer than its header says")))
      (ygg-review-file--rec scan 'header text)))))

(defun ygg-review-file--lines (string)
  (let ((lines (split-string string "\n")))
    (if (equal (car (last lines)) "") (butlast lines) lines)))

(defun ygg-review-file--records-of (lines &optional notify)
  (let ((scan (ygg-review-file--scan-new)) (i 0) out)
    (setf (ygg-review-file--s-notify scan) notify)
    (dolist (line lines)
      (setf (ygg-review-file--s-pos scan) i)
      (push (ygg-review-file--step scan line) out)
      (cl-incf i))
    (when (or (> (ygg-review-file--s-rem-old scan) 0) (> (ygg-review-file--s-rem-new scan) 0))
      (setf (ygg-review-file--s-pos scan) (max 0 (1- i)))
      (ygg-review-file--flag scan "hunk has fewer lines than its header says"))
    (vconcat (nreverse out))))

(defun ygg-review-file--records (diff)
  (ygg-review-file--records-of (ygg-review-file--lines diff)))

(defun ygg-review-file--content-p (rec)
  (memq (plist-get rec :kind) '(ctx add del)))

(defun ygg-review-file--rec-anchor (rec)
  (if (ygg-review-file--content-p rec)
      (list :level 'line :file (plist-get rec (if (eq (plist-get rec :side) 'old) :old-path :new-path))
            :old-path (plist-get rec :old-path) :new-path (plist-get rec :new-path)
            :side (plist-get rec :side) :line (plist-get rec :line)
            :old-line (plist-get rec :old-line))
    (list :level 'file :file (plist-get rec :new-path) :old-path (plist-get rec :old-path)
          :new-path (plist-get rec :new-path))))

;;; Derivation from position

(defun ygg-review-file--join (recs from to)
  (mapconcat (lambda (k) (plist-get (aref recs k) :text)) (number-sequence from to) "\n"))

(defun ygg-review-file--window (recs i)
  (let ((hunk (plist-get (aref recs i) :hunk)) (n (length recs)) (lo i) (hi i) (k (1- i)) (c 0))
    (while (and (>= k 0) (< c 2) (eql (plist-get (aref recs k) :hunk) hunk)
                (not (eq (plist-get (aref recs k) :kind) 'snip)))
      (when (ygg-review-file--content-p (aref recs k)) (setq lo k) (cl-incf c))
      (cl-decf k))
    (setq k (1+ i) c 0)
    (while (and (< k n) (< c 2) (eql (plist-get (aref recs k) :hunk) hunk)
                (not (eq (plist-get (aref recs k) :kind) 'snip)))
      (when (ygg-review-file--content-p (aref recs k)) (setq hi k) (cl-incf c))
      (cl-incf k))
    (ygg-review-file--join recs lo hi)))

(defun ygg-review-file--hunk-text (recs i)
  (when-let* ((h (plist-get (aref recs i) :hunk))) (ygg-review-file--join recs h i)))

(defvar ygg-review-file--prefix-cache (make-hash-table :test 'eq :weakness 'key))

(defun ygg-review-file--prefixes (recs)
  (or (gethash recs ygg-review-file--prefix-cache)
      (puthash
       recs
       (let* ((n (length recs)) (old (make-vector (1+ n) 0)) (new (make-vector (1+ n) 0))
              (diff (make-vector (1+ n) 0)))
         (dotimes (k n)
           (let* ((rec (aref recs k)) (content (ygg-review-file--content-p rec))
                  (side (plist-get rec :side)))
             (aset old (1+ k) (+ (aref old k) (if (and content (eq side 'old)) 1 0)))
             (aset new (1+ k) (+ (aref new k) (if (and content (eq side 'new)) 1 0)))
             (aset diff (1+ k) (+ (aref diff k) (if (eq (plist-get rec :kind) 'diff) 1 0)))))
         (vector old new diff))
       ygg-review-file--prefix-cache)))

(defun ygg-review-file--cum (pre sides k)
  (+ (if (memq 'old sides) (aref (aref pre 0) k) 0)
     (if (memq 'new sides) (aref (aref pre 1) k) 0)))

(defun ygg-review-file--count (recs from to sides)
  (let ((pre (ygg-review-file--prefixes recs)))
    (max 0 (- (ygg-review-file--cum pre sides (1+ to)) (ygg-review-file--cum pre sides from)))))

(defun ygg-review-file--span-start (recs end n sides)
  (let* ((pre (ygg-review-file--prefixes recs))
         (target (- (ygg-review-file--cum pre sides (1+ end)) (1- n)))
         (lo 0) (hi end))
    (when (>= target 1)
      (while (< lo hi)
        (let ((mid (/ (+ lo hi) 2)))
          (if (>= (ygg-review-file--cum pre sides (1+ mid)) target) (setq hi mid) (setq lo (1+ mid)))))
      (and (= (aref (aref pre 2) (1+ end)) (aref (aref pre 2) lo)) lo))))

(defun ygg-review-file--anchor-at (recs i span attrs)
  (let* ((rec (aref recs i)) (anchor (ygg-review-file--rec-anchor rec)) start note)
    (cond
     ((and span (ygg-review-file--content-p rec))
      (let* ((side (plist-get rec :side))
             (sides (delq nil (list (or (plist-get attrs :start-side) side)
                                    (or (plist-get attrs :side) side))))
             (s (ygg-review-file--span-start recs i span sides)))
        (if (not s) (setq note "span reaches past the quoted lines of the file")
          (let ((r (aref recs s)))
            (setq start s
                  anchor (append (list :start-side (plist-get r :side) :start-line (plist-get r :line)
                                       :start-old-line (plist-get r :old-line))
                                 (plist-put anchor :level 'range)))))))
     (span (setq note "span on a line that is not diff content"))
     ((eq (plist-get rec :kind) 'snip) (setq note "comment after a snip marker anchors to the file")))
    (list anchor start note)))

(defun ygg-review-file--comment-derive (recs i span attrs)
  (let* ((a (ygg-review-file--anchor-at recs i span attrs))
         (start (nth 1 a)))
    (cons (append (nth 0 a)
                  (list :quote (cond (start (ygg-review-file--join recs start i))
                                     ((ygg-review-file--content-p (aref recs i))
                                      (ygg-review-file--window recs i)))))
          (nth 2 a))))

(defun ygg-review-file--github-p (ids urls)
  (or (seq-some (lambda (id) (and id (string-prefix-p "remote:gh:" (ygg-review-file--idstr id)))) ids)
      (seq-some (lambda (url)
                  (and (stringp url)
                       (string-match "\\`[A-Za-z][A-Za-z0-9+.-]*://\\([^/?#]*\\)" url)
                       (string-match-p "github" (downcase (match-string 1 url)))))
                urls)))

(defun ygg-review-file--thread-derive (recs i span attrs github)
  (let* ((a (ygg-review-file--anchor-at recs i span attrs)) d)
    (dolist (k ygg-review-file--thread-derived)
      (when (plist-get (nth 0 a) k) (setq d (append d (list k (plist-get (nth 0 a) k))))))
    (setq d (append d (list :remote t)))
    (when (and github (ygg-review-file--content-p (aref recs i)) (not (plist-member attrs :diff-hunk)))
      (setq d (append d (list :diff-hunk (ygg-review-file--hunk-text recs i)))))
    (cons d (nth 2 a))))

(defun ygg-review-file--settle (c derive keys)
  (let (attrs forced d)
    (dotimes (_ 3)
      (setq d (car (funcall derive attrs)))
      (dolist (k keys)
        (unless (equal (plist-get c k) (plist-get d k))
          (cl-pushnew k forced)
          (when (plist-get c k) (setq attrs (plist-put attrs k (plist-get c k)))))))
    (cons (car (funcall derive attrs)) forced)))

;;; Divs

(defun ygg-review-file--colons (line)
  (if (string-match "\\`[ \t]*\\(:+\\)" line) (length (match-string 1 line)) 0))

(defun ygg-review-file--fence-len (strings)
  (1+ (apply #'max 2 (mapcar #'ygg-review-file--colons
                             (mapcan (lambda (s) (split-string s "\n")) strings)))))

(defun ygg-review-file--div (class head pairs text)
  (let* ((text (and text (ygg-review-file--idstr text)))
         (inline (and text (string-search "\r" text)))
         (pairs (cond (inline (append pairs (list (cons :text text))))
                      ((null text) (append pairs (list (cons :text nil))))
                      (t pairs)))
         (text (if inline nil text))
         (fence (make-string (ygg-review-file--fence-len (list (or text ""))) ?:)))
    (concat fence " {." class head (ygg-review-file--attrs pairs) "}\n"
            (if (member text '(nil "")) "" (concat text "\n"))
            fence "\n")))

;;; Scanning

(defun ygg-review-file--normalize (string)
  (let* ((lines (split-string string "\n"))
         (lines (if (equal (car (last lines)) "") (butlast lines) lines))
         (ended (string-suffix-p "\n" string))
         (checked (if ended lines (butlast lines)))
         (crlf (and checked (seq-every-p (lambda (l) (string-suffix-p "\r" l)) checked))))
    (vconcat (mapcar (lambda (l)
                       (if (and (string-suffix-p "\r" l) (or crlf (not (string-prefix-p ">" l))))
                           (substring l 0 -1)
                         l))
                     lines))))

(defun ygg-review-file--fence (line)
  (when (and (string-match-p "\\`[ \t]*:::" line)
             (string-match "\\`[ \t]*\\(:\\{3,\\}\\)[ \t]*\\(.*?\\)[ \t]*\\'" line))
    (cons (length (match-string 1 line)) (match-string 2 line))))

(defun ygg-review-file--div-end (lines i to n quote-ends)
  (let ((j (1+ i)) first res)
    (while (and (< j to) (not res))
      (let* ((line (aref lines j)) (f (ygg-review-file--fence line)))
        (cond ((and f (>= (car f) n))
               (setq res (if (string-empty-p (cdr f))
                             (list j (1+ j) t)
                           (list (or first j) (or first j) nil))))
              ((and quote-ends (not first) (string-prefix-p ">" line)) (setq first j))))
      (cl-incf j))
    (or res (let ((e (or first to))) (list e e nil)))))

(defun ygg-review-file--trim-blank (list)
  (while (and list (string-blank-p (car list))) (setq list (cdr list)))
  (setq list (reverse list))
  (while (and list (string-blank-p (car list))) (setq list (cdr list)))
  (nreverse list))

(defconst ygg-review-file--position-keys
  '(:line :start-line :old-line :start-old-line :side :start-side :level))

(defun ygg-review-file--field (key value)
  "The list of KEY's VALUE as it is kept, or nil when VALUE does not fit KEY."
  (pcase key
    ((or :line :start-line :old-line :start-old-line) (and (integerp value) (list value)))
    ((or :side :start-side) (and (memq value '(old new)) (list value)))
    (:level (and (memq value '(review file line range)) (list value)))
    (:created (let ((time (if (stringp value) (ygg-review-file--iso-parse value) value)))
                (and (numberp time) (list time))))
    (:priority (and (integerp value) (<= 0 value 3) (list value)))
    (:confidence (and (numberp value) (<= 0 value 1) (list value)))
    (:type (and (symbolp value) (not (eq value t)) (list value)))
    (_ (list value))))

(defun ygg-review-file--sanitize (plist line)
  (cl-loop for (k v) on plist by #'cddr
           for ok = (and v (ygg-review-file--field k v))
           if (or (null v) ok) append (list k (if ok (car ok) v))
           else do (ygg-review-file--note
                    line (format "bad value for %s, %s" (substring (symbol-name k) 1)
                                 (if (memq k ygg-review-file--position-keys)
                                     "using the one its position gives"
                                   "ignored")))))

(defun ygg-review-file--div-parse (lines i to f quote-ends)
  (let* ((rest (cdr f))
         (brace (string-prefix-p "{" rest))
         (attrs (ygg-review-file--read-attrs (if brace (substring rest 1) (concat "." rest)) brace (1+ i)))
         (end (ygg-review-file--div-end lines i to (car f) quote-ends))
         (body (append (cl-subseq lines (1+ i) (nth 0 end)) nil))
         (plist (ygg-review-file--sanitize (nth 2 attrs) (1+ i))))
    (unless (nth 2 end)
      (setq body (reverse (seq-drop-while #'string-blank-p (reverse body))))
      (ygg-review-file--note (1+ i) "unclosed div, closed at the next div or quoted line"))
    (list :classes (nth 0 attrs)
          :id (when-let* ((id (or (nth 1 attrs) (plist-get plist :id)))) (ygg-review-file--idstr id))
          :attrs (cl-loop for (key value) on plist by #'cddr unless (eq key :id) append (list key value))
          :body body :next (nth 1 end) :line (1+ i) :from (1+ i) :to (nth 0 end))))

(defun ygg-review-file--body-text (div)
  (let ((attrs (plist-get div :attrs)))
    (if (plist-member attrs :text) (plist-get attrs :text)
      (string-join (plist-get div :body) "\n"))))

(defun ygg-review-file--replies (lines div)
  (let ((j (plist-get div :from)) (to (plist-get div :to)) out)
    (while (< j to)
      (let* ((line (aref lines j)) (f (ygg-review-file--fence line)))
        (cond ((and f (not (string-empty-p (cdr f))))
               (let ((d (ygg-review-file--div-parse lines j to f nil)))
                 (if (equal (car (plist-get d :classes)) "reply") (push d out)
                   (ygg-review-file--note (1+ j) "div inside a thread that is not a reply"))
                 (setq j (plist-get d :next))))
              (t (unless (string-blank-p line)
                   (ygg-review-file--note (1+ j) (format "stray text in a thread: %s" line)))
                 (cl-incf j)))))
    (nreverse out)))

(defun ygg-review-file--quote-text (line)
  (cond ((string-prefix-p "> " line) (substring line 2))
        ((= (length line) 1) " ")
        (t (substring line 1))))

(defun ygg-review-file--scan (string)
  (let* ((lines (ygg-review-file--normalize string))
         (n (length lines))
         (front (ygg-review-file--front lines))
         (i (cdr front)) (qn 0)
         quotes qlines events pieces run)
    (cl-flet ((flush ()
                (when run
                  (let ((text (string-join (ygg-review-file--trim-blank (reverse run)) "\n")))
                    (unless (string-empty-p text) (push text pieces)))
                  (setq run nil))))
      (while (< i n)
        (let* ((line (aref lines i)) (f (ygg-review-file--fence line)))
          (cond
           ((and f (not (string-empty-p (cdr f))))
            (flush)
            (let* ((d (ygg-review-file--div-parse lines i n f t))
                   (class (car (plist-get d :classes))))
              (cond ((equal class "summary") (push (ygg-review-file--body-text d) pieces))
                    ((equal class "thread")
                     (push (list :kind 'thread :anchor (and (> qn 0) (1- qn)) :div d
                                 :replies (ygg-review-file--replies lines d))
                           events))
                    ((member class '("c" "comment"))
                     (push (list :kind 'comment :anchor (and (> qn 0) (1- qn)) :div d) events))
                    (class (ygg-review-file--note (1+ i) (format "unknown div class %s" class)))
                    (t (ygg-review-file--note (1+ i) "div without a class")))
              (setq i (1- (plist-get d :next)))))
           (f (ygg-review-file--note (1+ i) "closing fence without an open div"))
           ((string-prefix-p ">" line)
            (flush)
            (push (ygg-review-file--quote-text line) quotes)
            (push (1+ i) qlines)
            (cl-incf qn))
           ((string-blank-p line) (when run (push "" run)))
           ((zerop qn) (push line run))
           (t (ygg-review-file--note (1+ i) (format "stray text outside a comment: %s" line)))))
        (cl-incf i))
      (flush))
    (list :front (car front) :quotes (nreverse quotes) :qlines (vconcat (nreverse qlines))
          :events (nreverse events) :pieces (nreverse pieces))))

;;; Live diff

(defun ygg-review-file--check-live (quotes qlines live)
  (let* ((strip (lambda (l) (if (string-suffix-p "\r" l) (substring l 0 -1) l)))
         (live-lines (vconcat (mapcar strip (ygg-review-file--lines live))))
         (qv (vconcat (mapcar strip quotes)))
         (m (length live-lines)) (nq (length qv)) (p 0) (k 0) (shown 0) (hidden 0))
    (cl-flet ((report (message)
                (if (< shown 30)
                    (progn (cl-incf shown) (ygg-review-file--note (aref qlines k) message))
                  (cl-incf hidden))))
      (while (< k nq)
        (let ((q (aref qv k)))
          (cond
           ((string-match "\\`\\[\\.\\.\\. \\([0-9]+\\) lines\\]\\'" q)
            (cl-incf p (string-to-number (match-string 1 q)))
            (cl-incf k))
           ((and (< p m) (equal q (aref live-lines p)))
            (cl-incf p)
            (cl-incf k))
           (t
            (let ((extra-live (cl-loop for x from (1+ p) below (min m (+ p 21))
                                       when (equal q (aref live-lines x)) return (- x p)))
                  (extra-quoted (and (< p m)
                                     (cl-loop for y from (1+ k) below (min nq (+ k 21))
                                              when (equal (aref qv y) (aref live-lines p)) return (- y k))))
                  (swapped (and (< (1+ p) m) (< (1+ k) nq)
                                (equal (aref qv (1+ k)) (aref live-lines (1+ p))))))
              (cond
               ((and extra-live (not swapped) (or (null extra-quoted) (<= extra-live extra-quoted)))
                (report (format "live diff has %d more lines here" extra-live))
                (cl-incf p extra-live))
               ((and extra-quoted (not swapped))
                (report (if (= extra-quoted 1) (format "quoted line is not in the live diff: %s" q)
                          (format "%d quoted lines are not in the live diff" extra-quoted)))
                (cl-incf k extra-quoted))
               (t
                (report (format "quoted line differs from the live diff: %s" q))
                (cl-incf p)
                (cl-incf k)))))))))
    (when (> hidden 0)
      (ygg-review-file--note (aref qlines (1- (length qlines)))
                             (format "%d more quoted lines differ from the live diff" hidden)))
    (when (and (> nq 0) (< p m))
      (ygg-review-file--note (aref qlines (1- nq))
                             "live diff has extra files or hunks beyond the quoted diff"))
    (concat "\n" (string-join live-lines "\n") "\n")))

;;; Parsing

(defun ygg-review-file--created-key (c)
  (let ((v (plist-get c :created))) (if (numberp v) v 0)))

(defun ygg-review-file--by-created (comments)
  (sort (copy-sequence comments)
        (lambda (a b) (< (ygg-review-file--created-key a) (ygg-review-file--created-key b)))))

(defun ygg-review-file--span-attr (attrs line anchor)
  (when (plist-member attrs :span)
    (let ((v (plist-get attrs :span)))
      (cond ((not (and (integerp v) (> v 0)))
             (ygg-review-file--note line "span must be a positive integer") nil)
            ((not anchor) (ygg-review-file--note line "span without a quoted line above it") nil)
            ((= v 1) nil)
            (t v)))))

(defun ygg-review-file--span-attrs (attrs span line)
  (if (and span (eq (plist-get attrs :level) 'line))
      (progn (ygg-review-file--note line "span together with level=line, the span wins")
             (cl-loop for (k v) on attrs by #'cddr unless (eq k :level) append (list k v)))
    attrs))

(defun ygg-review-file--check-range (fields line)
  (let ((start (plist-get fields :start-line)) (end (plist-get fields :line)))
    (when (and (integerp start) (integerp end) (> start end)
               (eq (or (plist-get fields :start-side) (plist-get fields :side) 'new)
                   (or (plist-get fields :side) 'new)))
      (ygg-review-file--note line "range starts after its end"))))

(defun ygg-review-file--fields (derived attrs skip)
  (let (fields)
    (cl-loop for (k v) on derived by #'cddr when v do (setq fields (plist-put fields k v)))
    (cl-loop for (k v) on attrs by #'cddr unless (memq k skip) do (setq fields (plist-put fields k v)))
    fields))

(defun ygg-review-file--build-comment (ev precs front-range seen live-text author)
  (let* ((d (plist-get ev :div)) (line (plist-get d :line))
         (attrs (plist-get d :attrs)) (a (plist-get ev :anchor))
         (span (ygg-review-file--span-attr attrs line a))
         (attrs (ygg-review-file--span-attrs attrs span line))
         (derived (and a (ygg-review-file--comment-derive precs a span attrs)))
         (fields (ygg-review-file--fields (car derived) attrs '(:text :span)))
         (id (plist-get d :id)) (fresh nil)
         (text (ygg-review-file--body-text d)))
    (when (cdr derived) (ygg-review-file--note line (cdr derived)))
    (ygg-review-file--check-range fields line)
    (when (and (not a) (not (plist-member attrs :level))) (setq fields (plist-put fields :level 'review)))
    (when (and a (eq (plist-get fields :level) 'range)
               (not (plist-get fields :start-line)) (not (plist-get fields :start-old-line)))
      (ygg-review-file--note line "range comment without a span or a start line"))
    (when (and front-range (not (plist-member attrs :range))) (setq fields (plist-put fields :range front-range)))
    (when (and author (not (plist-member attrs :author))) (setq fields (plist-put fields :author author)))
    (cond ((null id) (setq fresh t))
          ((gethash id seen)
           (ygg-review-file--note line (format "duplicate id %s" id))
           (setq fresh t)))
    (when fresh
      (setq id (ygg-review-file--new-id))
      (unless (plist-member attrs :created) (setq fields (plist-put fields :created (float-time)))))
    (puthash id t seen)
    (let ((c (append (list :id id) fields (list :text text))))
      (when (and live-text (stringp (plist-get c :quote)) (not (string-empty-p (plist-get c :quote)))
                 (not (string-search (concat "\n" (plist-get c :quote) "\n") live-text)))
        (ygg-review-file--note line (format "quote of %s no longer matches the live diff" id)))
      c)))

(defun ygg-review-file--build-thread (ev precs seen)
  (let* ((d (plist-get ev :div)) (line (plist-get d :line))
         (attrs (plist-get d :attrs)) (a (plist-get ev :anchor))
         (span (ygg-review-file--span-attr attrs line a))
         (tid (plist-get d :id))
         (github (ygg-review-file--github-p
                  (cons tid (mapcar (lambda (r) (plist-get r :id)) (plist-get ev :replies)))
                  (mapcar (lambda (r) (plist-get (plist-get r :attrs) :url)) (plist-get ev :replies))))
         (derived (and a (ygg-review-file--thread-derive precs a span attrs github)))
         (base (ygg-review-file--fields (append (car derived) (list :remote t)) attrs '(:span)))
         entries)
    (when (cdr derived) (ygg-review-file--note line (cdr derived)))
    (ygg-review-file--check-range base line)
    (if tid
        (progn (when (gethash tid seen) (ygg-review-file--note line (format "duplicate thread id %s" tid)))
               (puthash tid t seen))
      (ygg-review-file--note line "thread without an id"))
    (unless (plist-member attrs :thread) (when tid (setq base (plist-put base :thread tid))))
    (dolist (r (plist-get ev :replies))
      (let ((fields (copy-sequence base)) (rattrs (plist-get r :attrs)))
        (cl-loop for (k v) on rattrs by #'cddr unless (eq k :text) do (setq fields (plist-put fields k v)))
        (when (plist-get r :id) (setq fields (plist-put fields :id (plist-get r :id))))
        (setq fields (plist-put fields :text (ygg-review-file--body-text r)))
        (push fields entries)))
    (unless entries (ygg-review-file--note line "thread without replies"))
    (nreverse entries)))

(defun ygg-review-file--assemble (scan live)
  (let* ((front (plist-get scan :front))
         (quotes (plist-get scan :quotes))
         (precs (ygg-review-file--records-of
                 quotes (lambda (pos message)
                          (ygg-review-file--note (aref (plist-get scan :qlines) pos) message))))
         (live-text (and live (ygg-review-file--check-live quotes (plist-get scan :qlines) live)))
         (front-range (plist-get front :range))
         (author (plist-get front :author))
         (seen (make-hash-table :test 'equal)) (tseen (make-hash-table :test 'equal))
         comments threads)
    (dolist (ev (plist-get scan :events))
      (if (eq (plist-get ev :kind) 'comment)
          (push (ygg-review-file--build-comment ev precs front-range seen live-text author) comments)
        (push (ygg-review-file--build-thread ev precs tseen) threads)))
    (let ((pieces (plist-get scan :pieces)) review)
      (cl-loop for (k v) on front by #'cddr
               do (cond ((memq k '(:comments :threads :problems :text))
                         (ygg-review-file--note 1 (format "reserved front matter key %s" k)))
                        ((eq k :author))
                        (t (setq review (plist-put review k v)))))
      (append review
              (and pieces (list :text (string-join pieces "\n\n")))
              (list :comments (ygg-review-file--by-created (nreverse comments))
                    :threads (apply #'append (nreverse threads)))))))

(defun ygg-review-file-parse (string &optional live-diff)
  "The review plist of the review file STRING, anchors read from the quoted diff.
Never signals: what cannot be read comes back as :problems, a list of
\(LINE . MESSAGE).  With LIVE-DIFF, quoted lines and comment quotes that differ
from it are problems too."
  (let ((ygg-review-file--problems nil))
    (condition-case err
        (let ((review (ygg-review-file--assemble (ygg-review-file--scan (or string "")) live-diff)))
          (append review (list :problems (sort (nreverse ygg-review-file--problems)
                                               (lambda (a b) (< (car a) (car b)))))))
      (error (list :comments nil :threads nil
                   :problems (list (cons 1 (format "internal error: %S" err))))))))

(defun ygg-review-file-diff (string)
  "The diff quoted in the review file STRING, snips kept as their marker lines.
Never signals."
  (let ((ygg-review-file--problems nil))
    (condition-case nil
        (let ((quotes (plist-get (ygg-review-file--scan (or string "")) :quotes)))
          (and quotes (concat (string-join quotes "\n") "\n")))
      (error nil))))

;;; Printing

(defun ygg-review-file--index (recs)
  (let ((lines (make-hash-table :test 'equal)) (files (make-hash-table :test 'equal)))
    (cl-loop for rec across recs for i from 0
             do (if (eq (plist-get rec :kind) 'diff)
                    (unless (gethash (plist-get rec :new-path) files)
                      (puthash (plist-get rec :new-path) i files))
                  (when (ygg-review-file--content-p rec)
                    (puthash (list (plist-get rec :new-path) (plist-get rec :side) (plist-get rec :line))
                             i lines))))
    (cons lines files)))

(defun ygg-review-file--place (index comment)
  (let ((lines (car index)) (files (cdr index)) (path (plist-get comment :new-path)))
    (pcase (plist-get comment :level)
      ('file (when-let* ((i (gethash path files))) (list i i nil)))
      ('line (when-let* ((i (gethash (list path (plist-get comment :side) (plist-get comment :line)) lines)))
               (list i i nil)))
      ('range (let ((end (gethash (list path (plist-get comment :side) (plist-get comment :line)) lines))
                    (start (gethash (list path (plist-get comment :start-side)
                                          (plist-get comment :start-line))
                                    lines)))
                (and start end (<= start end) (list end start t)))))))

(defun ygg-review-file--thread-place (index entries)
  (let* ((root (car entries))
         (path (or (plist-get root :new-path) (plist-get root :file)))
         (side (or (plist-get root :side) 'new))
         (end (and (plist-get root :line) (gethash (list path side (plist-get root :line)) (car index)))))
    (if end
        (let ((start (and (plist-get root :start-line)
                          (gethash (list path side (plist-get root :start-line)) (car index)))))
          (if (and start (<= start end)) (list end start t) (list end end nil)))
      (when-let* ((i (gethash path (cdr index)))) (list i i nil)))))

(defun ygg-review-file--group (threads)
  (let ((table (make-hash-table :test 'equal)) keys)
    (dolist (entry threads)
      (let ((key (or (plist-get entry :thread) (plist-get entry :id))))
        (unless (gethash key table) (push key keys))
        (puthash key (cons entry (gethash key table)) table)))
    (mapcar (lambda (key) (reverse (gethash key table))) (nreverse keys))))

(defun ygg-review-file--sides (c keys)
  (delq nil (mapcar (lambda (k) (plist-get c k)) keys)))

(defun ygg-review-file--author-pairs (c author)
  (let ((own (plist-get c :author)))
    (and (or own author) (not (equal own author)) (list (cons :author own)))))

(defun ygg-review-file--comment-pairs (c recs j span front-range author)
  (let* ((s (ygg-review-file--settle
             c (lambda (attrs) (ygg-review-file--comment-derive recs j span attrs)) '(:side :start-side)))
         (d (car s)) (forced (cdr s))
         (skip (append '(:id :text :span :quote :range :author) ygg-review-file--derived-keys)))
    (append
     (mapcar (lambda (k) (cons k (plist-get c k)))
             (ygg-review-file--ordered c ygg-review-file--attr-order skip))
     (cl-loop for k in ygg-review-file--derived-keys
              when (or (memq k forced) (not (equal (plist-get c k) (plist-get d k))))
              collect (cons k (plist-get c k)))
     (unless (equal (plist-get c :range) front-range) (list (cons :range (plist-get c :range))))
     (ygg-review-file--author-pairs c author)
     (and span (list (cons :span span)))
     (unless (equal (plist-get c :quote) (plist-get d :quote)) (list (cons :quote (plist-get c :quote)))))))

(defun ygg-review-file--orphan-pairs (c front-range author)
  (append
   (mapcar (lambda (k) (cons k (plist-get c k)))
           (ygg-review-file--ordered c ygg-review-file--attr-order '(:id :text :span :range :level :author)))
   (ygg-review-file--author-pairs c author)
   (unless (eq (plist-get c :level) 'review) (list (cons :level (plist-get c :level))))
   (unless (equal (plist-get c :range) front-range) (list (cons :range (plist-get c :range))))))

(defun ygg-review-file--comment-div (c recs j span front-range author)
  (ygg-review-file--div
   "c" (ygg-review-file--id-attr (plist-get c :id))
   (if j (ygg-review-file--comment-pairs c recs j span front-range author)
     (ygg-review-file--orphan-pairs c front-range author))
   (plist-get c :text)))

(defun ygg-review-file--thread-pairs (root recs j span github)
  (let* ((s (and j (ygg-review-file--settle
                    root (lambda (attrs) (ygg-review-file--thread-derive recs j span attrs github)) '(:side))))
         (d (car s)) (forced (cdr s))
         (skip (append ygg-review-file--entry-keys ygg-review-file--thread-derived
                       '(:thread :span :remote :diff-hunk))))
    (append
     (mapcar (lambda (k) (cons k (plist-get root k)))
             (ygg-review-file--ordered root ygg-review-file--attr-order skip))
     (cl-loop for k in ygg-review-file--thread-derived
              when (or (memq k forced) (not (equal (plist-get root k) (plist-get d k))))
              collect (cons k (plist-get root k)))
     (unless (eq (plist-get root :remote) t) (list (cons :remote (plist-get root :remote))))
     (and span (list (cons :span span)))
     (unless (equal (plist-get root :diff-hunk) (plist-get d :diff-hunk))
       (list (cons :diff-hunk (plist-get root :diff-hunk)))))))

(defun ygg-review-file--thread-div (entries recs j span)
  (let* ((root (car entries))
         (key (ygg-review-file--idstr (or (plist-get root :thread) (plist-get root :id))))
         (github (ygg-review-file--github-p
                  (cons key (mapcar (lambda (e) (plist-get e :id)) entries))
                  (mapcar (lambda (e) (plist-get e :url)) entries)))
         (skip (append ygg-review-file--entry-keys '(:thread)))
         (rest (ygg-review-file--ordered root nil skip))
         (replies
          (mapcar
           (lambda (entry)
             (let ((pairs (append
                           (cl-loop for k in '(:author :created :url)
                                    when (plist-get entry k) collect (cons k (plist-get entry k)))
                           (cl-loop for k in (seq-uniq (append rest (ygg-review-file--ordered entry nil skip)))
                                    unless (equal (plist-get entry k) (plist-get root k))
                                    collect (cons k (plist-get entry k))))))
               (ygg-review-file--div "reply" (ygg-review-file--id-attr (plist-get entry :id))
                                     pairs (plist-get entry :text))))
           entries))
         (fence (make-string (1+ (apply #'max 3 (mapcar #'ygg-review-file--colons replies))) ?:)))
    (concat fence " {.thread" (ygg-review-file--id-attr key)
            (ygg-review-file--attrs
             (append (unless (equal (plist-get root :thread) key)
                       (list (cons :thread (plist-get root :thread))))
                     (ygg-review-file--thread-pairs root recs j span github)))
            "}\n"
            (mapconcat #'identity replies "\n")
            fence "\n")))

(defun ygg-review-file--snips (recs anchored)
  (let* ((n (length recs)) (snips (make-hash-table)) (margin ygg-review-file-snip-margin)
         (threshold ygg-review-file-snip-threshold) (keep (make-vector n nil)) (i 0)
         (prefix (make-vector (1+ n) 0)))
    (when threshold
      (dotimes (k n)
        (aset prefix (1+ k) (+ (aref prefix k) (if (aref anchored k) 1 0))))
      (dotimes (k n)
        (when (> (- (aref prefix (min n (+ k margin 1))) (aref prefix (max 0 (- k margin)))) 0)
          (aset keep k t)))
      (while (< i n)
        (if (not (eq (plist-get (aref recs i) :kind) 'ctx))
            (cl-incf i)
          (let ((j i) (start nil))
            (while (and (< j n) (eq (plist-get (aref recs j) :kind) 'ctx)) (cl-incf j))
            (cl-loop for k from i below (min j (+ i margin)) do (aset keep k t))
            (cl-loop for k from (max i (- j margin)) below j do (aset keep k t))
            (cl-loop for k from i to j
                     do (if (and (< k j) (not (aref keep k)))
                            (unless start (setq start k))
                          (when (and start (> (- k start) threshold))
                            (puthash start (cons (- k start) (1- k)) snips))
                          (setq start nil)))
            (setq i j)))))
    snips))

(defun ygg-review-file--mark (delta place)
  (cl-incf (aref delta (nth 1 place)))
  (cl-decf (aref delta (1+ (nth 0 place)))))

(defun ygg-review-file--printed (full snips)
  (let ((n (length full)) (pmap nil) (lines nil) (k 0) (i 0))
    (setq pmap (make-vector n nil))
    (while (< i n)
      (if-let* ((snip (gethash i snips)))
          (progn (push (format "[... %d lines]" (car snip)) lines)
                 (cl-incf k)
                 (setq i (1+ (cdr snip))))
        (aset pmap i k)
        (push (plist-get (aref full i) :text) lines)
        (cl-incf k)
        (cl-incf i)))
    (cons pmap (nreverse lines))))

(defun ygg-review-file--span-count (recs place pmap sides dpre)
  (let ((je (aref pmap (nth 0 place))) (js (aref pmap (nth 1 place))))
    (and je js (= (aref dpre (1+ je)) (aref dpre js))
         (ygg-review-file--count recs js je sides))))

(defun ygg-review-file-print (review diff)
  "REVIEW, its fields, comments and forge threads, as a review file quoting DIFF."
  (let* ((full (ygg-review-file--records (if (stringp diff) diff "")))
         (index (ygg-review-file--index full))
         (n (length full))
         (front-range (plist-get review :range))
         (author (ygg-review-file--default-author (plist-get review :comments)))
         (delta (make-vector (1+ n) 0))
         (anchored (make-vector n nil))
         (cplaces (mapcar (lambda (c) (cons c (ygg-review-file--place index c)))
                          (ygg-review-file--by-created (plist-get review :comments))))
         (tplaces (mapcar (lambda (g) (cons g (ygg-review-file--thread-place index g)))
                          (ygg-review-file--group (plist-get review :threads)))))
    (dolist (p (append cplaces tplaces))
      (when (cdr p) (ygg-review-file--mark delta (cdr p))))
    (let ((sum 0))
      (dotimes (i n)
        (cl-incf sum (aref delta i))
        (aset anchored i (> sum 0))))
    (let* ((printed (ygg-review-file--printed full (ygg-review-file--snips full anchored)))
           (pmap (car printed))
           (recs (ygg-review-file--records-of (cdr printed)))
           (cat (make-hash-table)) (tat (make-hash-table))
           (dpre (let ((v (make-vector (1+ (length recs)) 0)))
                   (dotimes (k (length recs))
                     (aset v (1+ k) (+ (aref v k) (if (eq (plist-get (aref recs k) :kind) 'diff) 1 0))))
                   v))
           orphans orphan-threads after-div)
      (dolist (p cplaces)
        (let* ((c (car p)) (place (cdr p))
               (j (and place (aref pmap (nth 0 place))))
               (count (and j (nth 2 place)
                           (ygg-review-file--span-count
                            recs place pmap
                            (or (ygg-review-file--sides c '(:start-side :side)) '(new)) dpre)))
               (span (and count (> count 1) count))
               (div (and j (or count (not (nth 2 place)))
                         (ygg-review-file--comment-div c recs j span front-range author))))
          (if div (puthash j (append (gethash j cat) (list div)) cat)
            (push (ygg-review-file--comment-div c nil nil nil front-range author) orphans))))
      (dolist (p tplaces)
        (let* ((g (car p)) (place (cdr p))
               (j (and place (aref pmap (nth 0 place))))
               (count (and j (nth 2 place)
                           (ygg-review-file--span-count
                            recs place pmap (list (or (plist-get (car g) :side) 'new)) dpre)))
               (span (and count (> count 1) count))
               (div (and j (ygg-review-file--thread-div g recs j span))))
          (if div (puthash j (append (gethash j tat) (list div)) tat)
            (push (ygg-review-file--thread-div g nil nil nil) orphan-threads))))
      (with-temp-buffer
        (cl-flet ((block (s) (when after-div (insert "\n")) (insert s) (setq after-div t)))
          (insert (ygg-review-file--front-print review author))
          (when (plist-get review :text)
            (block (ygg-review-file--div "summary" nil nil (plist-get review :text))))
          (dolist (s (nreverse orphans)) (block s))
          (dolist (s (nreverse orphan-threads)) (block s))
          (when after-div (insert "\n"))
          (setq after-div nil)
          (dotimes (j (length recs))
            (insert "> " (plist-get (aref recs j) :text) "\n")
            (setq after-div nil)
            (dolist (s (append (gethash j tat) (gethash j cat))) (block s))))
        (buffer-string)))))

(provide 'ygg-review-file)

;;; ygg-review-file.el ends here
